### ISSUE TITLE
Notification sound doesn't play

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#975] opened 2015-02-09 06:44 UTC
I've been experiencing an issue where intermittently when a phone is locked, a new message will come in, the phone will vibrate and a notification will appear in the notification tray however no sound is ever played. Other application on the same phone don't seem to have an issue with this and I've double checked all the notification settings are enabled for sound. 

I've also noticed other occasions where a message is received, the phone vibrates but no notification is displayed and no light is flashed.

**Comment by iNPUTmice** [comment] 2015-02-21 10:11
could this be duplicate of: #758

**Comment by knoy** [comment] 2015-02-21 20:11
I havent had the same issue with the read markers but it sounds very similar. I've added the https://github.com/siacs/Conversations/commit/bcd3be59ce78609e608f4a8f7a868be977fdb4bb fix to the fork and will see if that fixes the issue

**Closed** 2015-02-23 09:56 UTC
