### ISSUE TITLE
Some OpenPGP are sent corrupted

### ISSUE THREAD

**Issue by github-k8n** [siacs/Conversations#1013] opened 2015-03-03 20:49 UTC
I had now the problem for a while that some OpenPGP messages were arriving as not being possible to decrypt when sent from Conversations. (Decryption fails in Conversations as well as in Pidgin)

Now I have finally one example message here that shows this issue (jabber ID changed):

```<message id='01db2aa2-43fb-439b-bcd1-0b89b569d183' type='chat' to='xxx@xxx' from='yyy@yyy/conversations'><body>This is an XEP-0027 encryted message</body><markable xmlns='urn:xmpp:chat-markers:0'/><request xmlns='urn:xmpp:receipts'/><x xmlns='jabber:x:encrypted'>hQIMAyxiLwdR0wDSARAAiPts2lAdxCgpqQ4bDT9xlgGk1VdKXgLJF/kjzqYQvuNIxJhnnZYy7fBgjUhcWR+3/uIfKJDyZTfFtERnPvlymcqBEHk3NzKMY2GoTzLB51ZOYAcsDUASIgBTYFmlDqNDkw+C1RlxM+q0BfNGRx+ghX7R6P0FtLlSzhC442GUIfMI0S0HLhO2HbOWjUWsMzhQOkhdOg32/eYpF5BiHnBNRM5bE8+ErFgK9rX8XL3lrJV1PYqLvyXacfjpBfQJcwjQT09KVpA6AJezHnmNgPhUMyo5cQlmPDAI82CkcdXTOPm9kg8ab+AiEVKqtJ+iU6DaMDyXV02AXalL+/nUomMEOaKpSFOTLtZcDZSdBZ0et0/CPgbzd5XDd1YcgqxxnuMX44z6ovliorGInfcjAAdtMrSJda2NftmDe+VnOuoSzw63GAq4nn5o5WrKvyynwXM8zLwGVsGkZa7KpnCvk06ETy+szU7vbQLA2ocNhi51NWtSMT9cQ3KAed36+ehz40cTKNgtqCyIvc0fcADV4PZUXUOjXnIYfc7OrBS+YIUDp6bDx0AxTUWRpuEcUX8K5YKq1b8PrkiPiUyJ/kcmb2TMlSYgy/S6tXW6zjCVyR/hjpxK2TxaayBcmxXqDpAU+/5wwQdVUIl6CYE4txdhPgGwKfoyEbWYm5Rr2E6m3EbBJuaFAgwDuyhZeLA6OSwBD/0WNJqHosU53wOYx0P+5KBwXpEx92EIQb4qCT2uwcM60yJlWmx9c2t5o7SZ+sQV8IcFy0A2KZM2VCZOT31b24MvahXKtBLs4Q34U9q872N6eOdYLWi7WXPKMwo/5SEuc5VisvRcd5WqkS/tj1KxZu+PxDc3VTzCdPf/ukoCrii6THP/YpXQpscvvc9mqyyyNEUkze9/w+OiuYqHi1zApmHA19K4JakPbWzwysdzfjj6Vg/LES+zR9Ei/g/2+44eZ/OvEvX5I60zWAk92o+7c89DqEHPlHhAc0q7uEemUKmIj5pUAGFFka3/gjqoMT08OQ83md46swRxi8RD6mGDq9IpMOg+uu08Eiog7Idew1hh0LoPSwC8KEjsnbqIXFqYuQYdpMa05ZWC6u12tkjetpCcOeo80O/C+zbaLv9HkUJH+7nv0JNUDqWsnaT7XMm2qdKeFOeXrsrPDFV6D5E6XMgNdBP2TZ9Pfi4kP7eidilEsL5/oEE80usNEskaeb/qAITbQHthCrsO8dz0SV6hcysTjZ7XeQWEbvyOjpiFqKxB2FwszYvNlXw09wYY8eIE8Qi+1BJNkFTa1r5fzjgRi5QqCIFDdGCx19MUkpmZg5n8AszkK6yy5ArnN4it5jR4hzut3WWRIggxgngybGLRLbB3FKPs9mbbUmMiB2W8SYTz1tJRATO7TYi0t1tlgSeLMkrxP5nFJoOR+fhY8FFnAEt9gMdsB90aPkvc50zdc5FJCk13</x></message>```

The only difference I see to other messages is that at almost at the end there is no equal sign.
e.g. with other messages it is:

`aWleI==TLAs</x></message>`
`hhMw===5SJp</x></message>`
`g5ALo==O2br</x></message>`
`L3Zliv=ZWWJ</x></message>`
`CSGw=klU9</x></message>`

but the problematic message ends in 
`dc5FJCk13</x></message>`

Maybe something got cut off?

**Comment by SamWhited** [comment] 2015-03-03 20:53
Did not check to make sure the length is actually correct, but the equals sign is just padding in case the base64 encoding doesn't end on a proper boundary length (they're not necessary unless padding is required).

**Comment by github-k8n** [comment] 2015-03-03 20:56
Thought so first too, however the base64 padding should be at the end (not a few characters before) and it should not be there with probability > 90% (looking at the messages now, they are ALWAYS there .. ALL of the working messages have an equal sign there.. )

**Comment by github-k8n** [comment] 2015-03-03 21:07
Well, adding the BEGIN and END headers, GnuPG (gpg --list-packets) definitely complains about the message, while it shows the used keys for other messages.
Whatever happened, the message is not valid.

**Comment by github-k8n** [comment] 2015-03-03 21:11
Ok, the equal sign has to be there, it seems the checksum is missing:

   OpenPGP's Radix-64 encoding is composed of two parts: a base64
   encoding of the binary data and a checksum.  The base64 encoding is
   identical to the MIME base64 content-transfer-encoding [RFC2045].

   The checksum is a 24-bit Cyclic Redundancy Check (CRC) converted to
   four characters of radix-64 encoding by the same MIME base64
   transformation, preceded by an equal sign (=).

**Comment by github-k8n** [comment] 2015-04-25 18:47
Any update on this?
Messages are still arriving corrupted from time to time.
Those messages are always from Conversations so it could be either Conversations itself or OpenKeychain that is creating those invalid messages.

**Comment by dschuermann** [comment] 2015-04-25 20:32
Developer of OpenKeychain here.
These problems could be caused by non-closing streams in our client lib. We will soon release a new stable of OpenKeychain with a new client library that hopefully fixes these problems. Stay tuned.

**Comment by iNPUTmice** [comment] 2015-07-23 11:27
I personally have stopped using PGP encryption a while ago. That means I can no longer eat my own dog food. And dogfooding generally is what makes Conversations such a great product. While I don't see an immediate reason to remove OpenPGP support from Conversations I think everyone would be better of if the PGP encryption part would be handled by someone who actually uses this on a daily basis.

So I'm calling out for someone to take over the responsibilities with OpenPGP. A first step would be to migrate to the new API version of openpgp-api. Later on you there are several open issues like:

#632
#711 (Decryption when in background) - Important one imho
#822
#957
#1013
#1299

If you are interested in that you would be given a lot of freedom in the architectural decisions.
Changing the way keys are discovered (JID lookup, instead of presence announcement) might also be an interesting step.

**Comment by github-k8n** [comment] 2015-07-23 16:25
@iNPUTmice , that's unfortunate, I think OpenPGP support is one of the main features that set Conversations apart from all the other Jabber clients that mostly support only OTR.

OTR is great if you have only a single device using jabber and you never want to send messages to an offline contact. OpenPGP shines for multi-device support (e.g.  desktop/mobile), I really like to be able to just continue an encrypted conversation on the desktop if the typing on the mobile gets to tedious and still have the whole conversation history on my mobile.

I hope someone can take over the PGP stuff, maybe I could also have a look if I have more spare time in a few months.

**Comment by iNPUTmice** [comment] 2015-12-11 17:17
If @dschuermann was right this was fixed by migrating to the new API.

**Closed by iNPUTmice** 2015-12-11 17:17 UTC
