### ISSUE TITLE
No way to reinitialize avatar

### ISSUE THREAD

**Issue by pmaziere** [siacs/Conversations#3435] opened 2019-04-15 08:38 UTC
After trying several pictures, I finally consider that these as avatars are more annoying than useful. 
I would like to reinitialize my avatar with the capital letter Conversations generated when I registered my account, but it seems there is no way to do so.

If I'm wrong, please advise on how to proceed.
Otherwise, is this a feature that could be implemented ?

thanks

**Comment by iNPUTmice** [comment] 2019-06-26 21:59
duplicate of #3080

**Comment by iNPUTmice** [comment] 2019-06-26 22:05
duplicate of #2235

**Closed by iNPUTmice** 2019-06-26 22:05 UTC
