### ISSUE TITLE
[Feature Request] If contact don't share a GPG public key, find one in OpenKeychain

### ISSUE THREAD

**Issue by Postroutine** [siacs/Conversations#2677] opened 2017-11-02 23:06 UTC
All is on the title:
If a contact don't share it's GPG public key, find one in OpenKeychain's keychain.

**Comment by licaon-kter** [comment] 2017-11-02 23:38
Maybe they want to use OMEMO, hence there is no need to share anything.

Why presume you/they should/want to use GPG?

**Comment by Postroutine** [comment] 2017-11-02 23:41
> Maybe they want to use OMEMO

Why?

> Why presume you/they should/want to use GPG?

Because they have shared their public keys with OpenPGP public keys server.

**Comment by licaon-kter** [comment] 2017-11-03 06:36
> Why?

Why not use OMEMO?

> Because they have shared their public keys with OpenPGP public keys server.

Again, that does not mean anything, maybe it's for e-mail only, maybe it's for Keybase Teams, maybe it's for git, you don't really know.

**Comment by Postroutine** [comment] 2017-11-03 15:25
> Why not use OMEMO?

 Why use OMEMO?

> Again, that does not mean anything, maybe it's for e-mail only, maybe it's for Keybase Teams, maybe it's for git, you don't really know.

If they publish a GPG public keys and use it for mail, files, etc, why suddenly using something else for XMPP?

**Comment by iNPUTmice** [comment] 2017-11-03 16:07
duplicate of #1490

**Closed by iNPUTmice** 2017-11-03 16:07 UTC

**Comment by d9h20f** [comment] 2017-11-03 17:04
Because OMEMO Just Works™, and you don't need a separate PGP client on every device in addition to the stuff you're using it for.

**Comment by Myppomeu** [comment] 2017-11-03 17:20
@d9h20f 
As I remember, with OMEMO you cannot store history on server with XEP-0313

**Comment by Postroutine** [comment] 2017-11-03 17:25
@d9h20f 
Omemo is only for XMPP, GPG can be used for mail, files, SMS, etc.
And Omemo is device linked, when GPG is user linked.
