### ISSUE TITLE
 [Feature Request] Add tab or switch for more then one accounts

### ISSUE THREAD

**Issue by tigexplorer** [siacs/Conversations#3270] opened 2018-11-13 12:20 UTC
####  [Feature Request]
If someone using several Jabber-IDs (accounts) with Conversations, it can get very confusing to manage a lot of chats of these accounts.

Is it possible, to have one tab for each account? 
So that at one tab (Conversations of account 1) only the chats of account 1 are listet and so on.

An other Solution could be, to add an account switch in the options menu and take the account ID or the Avatar/img in the title of the Conversations tab.

Thanx for your great work!

**Comment by iNPUTmice** [comment] 2018-11-17 13:59
This is duplicate of other issue which i’m too lazy to look up now.

**Closed by iNPUTmice** 2018-11-17 13:59 UTC
