### ISSUE TITLE
Only avatars of contacts shown in muc

### ISSUE THREAD

**Issue by meaz** [siacs/Conversations#3289] opened 2018-11-25 10:03 UTC
#### General information

* **Version:** 2.3.7
* **Device:** Galaxy s4 mini
* **Android Version:** Lineageos 15.1
* **Server name:** self hosted
* **Server software:** prosody trunk
* **Installed server modules:** mod_vcard4 mod_vcard_legacy
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open Conversations
2. Enter a MUC
3. Check the participants list

#### Expected result

See all participants avatars (if they have set one)

#### Actual result

I see only my contacts' avatar

**Comment by iNPUTmice** [comment] 2018-11-25 10:05
Closing as invalid. Conversations does show participants’ avatars in MUCs if it is available and annouced properly. That depends on what server those people are using.

**Comment by meaz** [comment] 2018-11-25 11:30
I think it is a Conversations problem as it works on Gajim and Dino.
As soon as I disable mod_vcard4 and mod_vcard_legacy and got back to mod_profile, things got back to what I expected: I see anyone's avatars.

**Comment by Zash** [comment] 2018-11-25 11:39
Looking at logs, I see no configuration set for the Avatar nodes, only a publish without publish-options like:

``` xml
<iq from="user@example.com/Conversations.xIRp" id="1szdJN2EQScp" type="set">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<publish node="urn:xmpp:avatar:data">
<item id="f05ae2cf8ea7f04f1163ae29a80dbe3ee4bab4b9">
<data xmlns="urn:xmpp:avatar:data">
/9j/4AAQSkZJRgABAQA....
</data>
</item>
</publish>
</pubsub>
</iq>
```

**Comment by iNPUTmice** [comment] 2018-11-25 11:42
@horazont thanks.
@Zash yeah it doesn’t set that.

**Comment by meaz** [comment] 2018-11-25 12:38
Then I still don't get it: it seems to be a Conversations issue, no? Then is this ticket still closed?

**Comment by iNPUTmice** [comment] 2018-11-25 12:52
@meaz the issue is not about Conversations not displaying avatars in MUC. As you can see in the conversations muc this is working fine.
The 'problem' is that avatars uploaded are deliberately not accessible to people not in your contact list. Previously this 'privacy issue' has been ignored. Now it doesn’t get ignored. So in a way this currently working as indented until Conversations decides to make your avatar explicitly available to everyone.

**Closed by iNPUTmice** 2018-11-25 12:52 UTC

**Comment by meaz** [comment] 2018-11-25 13:54
thanks @iNPUTmice I understand better.
