### ISSUE TITLE
Issue: Avatar getting reset to default avatar(Initial's letter) after a day.

### ISSUE THREAD

**Issue by VedantaBabaria** [siacs/Conversations#1191] opened 2015-05-13 07:52 UTC
It is been noticed that Avatar of all my contacts including me are getting reset to default state ie, Initial's letter, after sometime (Assumed to be a day). What might be a possible issue?

Using Conversation ver: 1.4.0 alpha

**Comment by iNPUTmice** [comment] 2015-05-13 09:31
please provide steps to reproduce

**Comment by VedantaBabaria** [comment] 2015-05-13 11:01
Steps to reproduce:

    > Open Manage Accounts.
    > Select  an account.
    > Click on Avatar.
    > Choose an Avatar to upload.
    > Click on Publish button.
   
Toast appears: "Avatar has been Published".
*The Published Avatar is successfully received by the subscribers (ie: friend's)

Expectation: Received Avatar should always persist on subscriber's side(ie: friend's application).

Reality: Although my Avatar gets reflected immediately on subscriber's side, but does not persist after a day (Assumed to be a day) and sets back to default avatar.

Additional information:

    Device: Sony Xperia s(lt26i), Moto-g, Moto-E
    OS: CyanogenMod 12 (for Xperia), Official Android 5.0.2 (for rest of the devices)
    XMPP Server: OpenFire(3.10.0)

**Comment by andersruneson** [comment] 2015-05-13 11:10
This is most likely the problem:
XMPP Server: OpenFire(3.10.0)

**Comment by iNPUTmice** [comment] 2015-05-13 11:10
>  Although my Avatar gets reflected immediately on subscriber's side, but does not persist after a day (Assumed to be a day) and sets back to default avatar.

does this correlate with an app restart?

**Comment by VedantaBabaria** [comment] 2015-05-13 11:30
No, it has no relation with app restart.

**Comment by iNPUTmice** [comment] 2015-05-13 13:35
Are you properly closing the app (by swiping it away for example) or are you killing it by flashing?
Try closing it once this should make your avatars persistent

**Comment by iNPUTmice** [comment] 2015-05-21 14:26
no reaction by op after over a week. closing

**Closed by iNPUTmice** 2015-05-21 14:26 UTC

**Comment by dm-m** [comment] 2019-12-30 13:43
#### General information

* **Version:** 2.6.1+fcr
* **Device:** OnePlus 5T
* **Android Version:**  Android 9, OsygenOS 9.0.9
* **Server name:** self hosted
* **Server software:** prosody 0.11.3
* **Installed server modules:** roster,  saslauth, tls, disco, carbons, pep, private, blocklist, vcard4, vcard_legacy, version, uptime, time, ping, register, mam, csi_simple, admin_adhoc, http_files, http, groups, smacks, smacks_noerror, cloud_notify, csi, http_upload, omemo_all_access, pep_simple.
* **Conversations source:** F-Droid


#### Steps to reproduce

1. Upload new avatar
2. Go to  Manage Accounts
3. Turn the account off and on
4. Avatar is reset to the one uploaded the very first time


#### Expected result

New avatar must be kept after an account is turned off.


#### Actual result

Old avatar keeps reappearing each time.


Tried to close the app by swiping it away but to no avail.

Please re-open the issue.

**Comment by licaon-kter** [comment] 2019-12-30 14:00
You pressed publish and in account details avatar appeared?

**Comment by dm-m** [comment] 2019-12-30 14:04
Hi, yes, corrected my post.

**Comment by iNPUTmice** [comment] 2019-12-30 14:15
As this is working for 10s of thousands users without any issue I’m going to suspect this is a server issue. (On re-login your server notifies the client of a newly published avatar which is really just your old avatar. (Maybe because it never actually got saved.)

**Comment by dm-m** [comment] 2019-12-30 17:45
Managed to find out the reason. My user was specified as admin in Prosody config. I removed it from admins and new avatar got saved. For those who might face the same issue here is the reference to Prosody issue tracker:
https://issues.prosody.im/1483

**Comment by Zash** [comment] 2019-12-31 01:43
As written in the Prosody issue:

> **Installed server modules:** *(snip)* pep, *(snip)* omemo_all_access, pep_simple.

You have two separate PEP implementations enabled. This is more likely to be the cause of your problems. Pick one (pep or pep_simple) and remove the other.
