### ISSUE TITLE
If I send a picture via URL with text the picture is not shown

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1527] opened 2015-10-28 06:28 UTC
If I send the URL of some picture without any text, the URL become a picture, there's no problem there. But if I do it with text the URL is not transformed into the picture.

**Comment by andersruneson** [comment] 2015-10-28 07:26
That is not a bug, it's the intended behavior.

**Comment by moshpirit** [comment] 2015-10-28 07:35
Well, I think that it should show always the pictures :\

**Comment by singpolyma** [comment] 2015-11-12 22:07
I also would like this feature.

**Comment by iNPUTmice** [comment] 2015-12-08 00:42
duplicate of #1421

**Closed by iNPUTmice** 2015-12-08 00:42 UTC
