### ISSUE TITLE
Password field - remove visibility option in account

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2730] opened 2017-12-19 01:41 UTC
#### General information

* **Version:** 1.23.3
* **Conversations source:** self build (latest HEAD)

It's nice on account creation, but in account view it makes the current security workflow of changing a password (prove you know the CURRENT password before changing it) useless.

Also, do add such a visibility icon to the NEW password field in the change password view though.

**Comment by harshitbansal05** [comment] 2018-01-21 14:07
@iNPUTmice @licaon-kter I think the password should not be visible in account view activity due to security reasons. So, the password edit text must be removed. Can I work on this?

**Comment by iNPUTmice** [comment] 2018-01-21 14:25
I haven't made up my mind on this yet. Not sure it's a good idea.

**Comment by licaon-kter** [comment] 2018-01-21 14:43
Why?

What's the use case exactly for this?

**Comment by harshitbansal05** [comment] 2018-01-21 17:22
as you said, @licaon-kter,  **it makes the current security workflow of changing a password (prove you know the CURRENT password before changing it) useless.**

**Comment by harshitbansal05** [comment] 2018-02-15 16:21
@licaon-kter, should I work on this issue?

**Comment by licaon-kter** [comment] 2018-02-15 17:34
@harshitbansal05 You don't need permission to start working on stuff, specially on old issues.

I wanted to do this myself, but only if it's wanted, hence this open issue.

Go!

**Comment by harshitbansal05** [comment] 2018-02-15 17:56
sure @licaon-kter, but I also wanted to ask if the issue is wanted. @iNPUTmice your reviews...

**Comment by allo-** [comment] 2018-03-28 20:05
There could be a clear-and-show option. The ability to input a password without hiding it is useful and I think modern security standards suggest to have this option. But you should of course not be able to read the old one. So first clearing and then unhiding the new text would be useful.

**Comment by iNPUTmice** [comment] 2018-03-29 05:53
Fixed in 2.0

**Closed by iNPUTmice** 2018-03-29 05:53 UTC
