### ISSUE TITLE
Feature request: Possibility to delete an avatar

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#1900] opened 2016-06-07 17:29 UTC
#### General information
- **Version:** eg 1.12.9
- **Conversations source:** PlayStore
#### Issue

If am no longer satisfied with my avatar, I need to choose a different one on my cellphone.
In case I don't have another suitable image, I would like to simply annul my avatar.
This is currently not possible.

--Alex

**Comment by blevant** [comment] 2016-10-25 15:53
+1

**Comment by x-jokay** [comment] 2017-02-20 16:17
+1

**Comment by iNPUTmice** [comment] 2019-06-26 22:09
duplicate of #2235

**Closed by iNPUTmice** 2019-06-26 22:09 UTC
