### ISSUE TITLE
Design: change how to join to an existing MUC

### ISSUE THREAD

**Issue by meaz** [siacs/Conversations#3148] opened 2018-08-18 06:51 UTC
#### General information

* **Version:** 1.28
* **Conversations source:** F-Droid

#### Steps to reproduce

If someone wants to connect to an existing MUC, the person has to click on ![02](https://user-images.githubusercontent.com/13604424/44296627-e2f71980-a2c2-11e8-8d73-98053360bbed.png) from the nav bar "Group conversations".
If someone want to create a MUC, the person has to click on ![01](https://user-images.githubusercontent.com/13604424/44296639-0b7f1380-a2c3-11e8-8a66-d05a049eff8d.png) from the bottom of "Group conversations".

#### Actual result

I find that confusing to click on ![02](https://user-images.githubusercontent.com/13604424/44296627-e2f71980-a2c2-11e8-8d73-98053360bbed.png) to join a room.

#### Expected result

What could make things easier, especially for new users, would be to have new menu that popsup when someone clicks on ![01](https://user-images.githubusercontent.com/13604424/44296639-0b7f1380-a2c3-11e8-8a66-d05a049eff8d.png), asking if the person want to create a room or to join an existing room.

**Comment by licaon-kter** [comment] 2018-08-18 08:43
/close as duplicate of #2950

IMHO, it's like that because one would rarely **type** the room ID, given that Conversations uses a random ID when a room is created, you'll likely click on a link to join and that doesn't need any user interaction.

**Closed** 2018-08-18 10:54 UTC
