### ISSUE TITLE
Group chat repeating message "...has set subject to..."

### ISSUE THREAD

**Issue by nikolanik** [siacs/Conversations#1386] opened 2015-09-04 12:49 UTC
When user change topic/subject of the group and he lose the net connection [or server has been restarted] all users in group have new message in that group: USERxxx has set the subject to: SUBJECT. From ejabberd debug log there are messages:  

2015-09-04 14:35:10.422 [debug] <0.497.0>@ejabberd_c2s:send_text:1894 Send XML on stream = <<"<message from='s82crcekp6hisf1@conference.chat.mtel.me' to='user1@chat.me/android' type='groupchat'><subject>Manijaci</subject><body>user2 has set the subject to: Manijaci</body></message>">>

that means the server send these messages, but question is why and how to stop it?

**Comment by iNPUTmice** [comment] 2015-09-04 15:49
duplicate of #1269 (see last comment on how to stop this if you do not control the server the MUC is hosted on)

**Closed by iNPUTmice** 2015-09-04 15:49 UTC
