### ISSUE TITLE
Suggestion: Add 'send-contact' feature

### ISSUE THREAD

**Issue by MaRies25** [siacs/Conversations#1313] opened 2015-08-04 11:25 UTC
Add an option to send a contact from your adressbook (choosable what data fields to include).

**Comment by iNPUTmice** [comment] 2015-08-04 22:29
Not exactly what you are asking for but from the android address book you can select 'share with' and pick Conversations.

**Comment by jruere** [comment] 2015-09-16 02:16
The functionality to choose fields could be implemented as a separate app that would then share the pruned contact data.

**Comment by knoy** [comment] 2015-09-17 01:57
I think what he may be suggesting is a method to transfer contacts using a UI similar to the file and image transfer.

I think this could be an interesting feature if people could instantly send each other contacts and have them be automatically be imported into the recipient's roster (after accepting the xfer), or have their OTR/OMEMO/PGP keys for that contact be transferred as well.

**Comment by iNPUTmice** [comment] 2016-06-17 13:02
duplicate of #1917

**Closed by iNPUTmice** 2016-06-17 13:02 UTC
