### ISSUE TITLE
Serverless p2p et al [question]

### ISSUE THREAD

**Issue by monokhrome** [siacs/Conversations#2505] opened 2017-06-04 15:02 UTC
Hello there.
First things first - thanks for what you do, Conversations is my XMPP client of choice for years now.

Given the recent events in the world, where some governments and officials try to monitor and regulate our communications, I would like to share some ideas on what could probably be done to enhance Conversations with server-less features, making communications decentralized and hard to monitor. I'm no Android coder by myself, so I'm not able to start working on the things listed below right now, but since I live in such a country, I may have to become one, if the conditions will become pressing.

1. Server-less protocol
We have XEP-0174, that is solid and is widely used to serverlessly chat in LANs using Zeroconf, or via Tor, exporting it's port as a hidden service, though no presence status is available since it's exchanged using DNS-SD. Presence information may be exchanged in-band, though, at the moment a chat is started.

Sorry, I've accidentally ctrl-entered, will update this message.

**Comment by iNPUTmice** [comment] 2017-06-04 15:08
duplicate of #1415

**Closed by iNPUTmice** 2017-06-04 15:08 UTC
