### ISSUE TITLE
High Battery Usage

### ISSUE THREAD

**Issue by IzzySoft** [siacs/Conversations#2576] opened 2017-08-06 17:34 UTC
As [recommended](https://github.com/siacs/Conversations/issues/1865#issuecomment-319357816), here's the specific issue:

#### General information

* **Version:** 1.19.5
* **Device:** Wileyfox Swift
* **Android Version:** Stock or Android 5.1 (CyanogenOS 12.1)
* **Server name:** jabber.de
* **Server software:** (unknown)
* **Installed server modules:** (unknown)
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Fully charge device
2. Start Conversations
3. Use the device as you always do

#### Expected result

Of course, a slight impact on battery is to be expected. Without Conversations *running* (e.g. when greenified), my Wileyfox Swift runs 5..6 days with one charge – so I would expect maybe 1 day less (20%). Having Conversations active (even only running in background without looking at it much) reduces runtime to 3 days or less, that is it "halves" duration – which I consider too much.

In the past, just stopping and restarting Conversations or, at worst, rebooting the device solved the issue – but Conversations then was usually responsible for 30% of battery use or less. Recently it amounted to over 70% and reduced runtime to less than 2 days (see screenshot from 2017-07-19), so I "greenified" the app (and only occasionally brought it up for manual checks). Battery duration was back to 6+ days.

Now, as recommended, I left it running the battery down from 100% to ~20% (sorry, but 5% would have been in the middle of the night – and also not healthy for LiIo batteries). Results are attached: Conversations responsible for about 50% of battery use, runtime ~3d. As requested, a (sanitized) dump of BBS is included.

Of course, the easiest solution for me would be switching to a version with GCM support, as then I could simply greenify it and still be updated via GCM (hence my post on the other issue) – though I wonder if the XMPP server would send such a notification via GCM? Maybe I'm mistaken in that respect and didn't understand what Conversation uses GCM for.

#### Debug output

* [adb.log.gz](https://github.com/siacs/Conversations/files/1203383/adb.log.gz)
* [log_conv_20170810_1.txt.gz](https://github.com/siacs/Conversations/files/1216434/log_conv_20170810_1.txt.gz)
* [BetterBatteryStats-2017-08-06_183836992.txt.gz](https://github.com/siacs/Conversations/files/1203261/BetterBatteryStats-2017-08-06_183836992.txt.gz)

[![screenshot_2017-07-19-15-46-28](https://user-images.githubusercontent.com/6781438/29005501-e74e071e-7adc-11e7-8d6b-1857f8c8b2f5.png)](https://user-images.githubusercontent.com/6781438/29005484-ac379014-7adc-11e7-9d37-874d0990da45.png) [![screenshot_2017-08-06-18-36-45](https://user-images.githubusercontent.com/6781438/29005510-074dc450-7add-11e7-827b-02d5f876c86e.png)](https://user-images.githubusercontent.com/6781438/29005379-a4dbf6f4-7ada-11e7-9624-4556811353cd.png)

**Comment by licaon-kter** [comment] 2017-08-06 18:05
Server software and more info in the [report](https://github.com/iNPUTmice/ComplianceTester/blob/master/reports/jabber.de.txt)

**Comment by iNPUTmice** [comment] 2017-08-06 19:25
Please include the output of adb logcat. Otherwise we won't be able to tell
if Conversations is doing something unusual.

**Comment by IzzySoft** [comment] 2017-08-06 19:56
@iNPUTmice Sorry for missing that. Didn't look like much helpful, only reaching back less than 2 hours. Included with initial post.

**Comment by licaon-kter** [comment] 2017-08-06 20:26
@IzzySoft See https://gultsch.de/compliance_ranked.html -> there's a `?` you can click for XEP-0384
More info here: https://github.com/iNPUTmice/ComplianceTester/issues/112

**Comment by licaon-kter** [comment] 2017-08-07 00:20
> Of course, the easiest solution for me would be switching to a version with GCM support

As the report says `running XEP-0357: Push Notifications… PASSED`, so push is available on your server, but you'd need the Google Play version (bought and) installed (also maybe all the Google services installed; albeit microG claims support for push so that might do it).

See FAQ: [How do XEP-0357: Push Notifications work?](https://github.com/siacs/Conversations#how-do-xep-0357-push-notifications-work)

**Comment by IzzySoft** [comment] 2017-08-10 09:27
@licaon-kter thanks! That sounds like a working approach (yes, microG handles GCM fine – and buying the version at Playstore is not an issue, though I'd prefer not to add the playstore dependency for updates (which is why I asked for the APK in the other issue)). Unless I should stay a little with my current configuration to help solving the underlying issue here. I'd hate having risen it and then not being around to help solving it or confirming a fix you come up with, feeling that a little unfair.

As to the issue: I already pointed out the only active "channel" I use is a MUC hosted on Trashserver. I just asked the round of participants who's using Conversations with that MUC in a constellation similar to mine, to maybe rule out some possible culprits.

* several are using the very same MUC with Conversations, not having my problems
* at least one of them is using a jabber.de account
* at least one of them shares the same mobile provider
* at least one explicitly stated using the F-Droid version
* all who answered with OS details are running Android 6 or higher

Of course, it could be a combination of factors. Nobody answered using the exact same combination I run.

With all required logs/dumps attached 4 days ago, may I ask if you already spotted something suspicious? I'm not pressing, but if you have a suspicion maybe I could help harden or reject it.

**Comment by iNPUTmice** [comment] 2017-08-10 09:32
The adb logcat looked totally normal to me. Maybe provide adb logcat for a longer duration or multiple 'snapshots' during the day.

**Comment by IzzySoft** [comment] 2017-08-10 10:03
I'd've loved to provide a longer interval, but that was all it gave (maybe due to the fact the device was charging for a while already – though that shouldn't purge logcat; I'll try again as soon as I come home. Currently Conversions is at 35% with the device off the charger for 24h and the battery down to ~50% – i.e. "full cycle" being one third of what I get without Conv running). Multiple daily snapshots are a bit trickier as I don't run around with a laptop :wink: Maybe I could find a logcat recorder with filtering function that works.

What about those BBS dumps? Don't they give a clue?

**Comment by iNPUTmice** [comment] 2017-08-10 10:12
> What about those BBS dumps? Don't they give a clue?

I have no idea what this is.


I suspect that you have too high of a expectation regarding battery life. A phone that is receiving ~200 messages a day will of course use up more battery than a phone doing nothing at all. Hypothetically - if your phone wouldn't do anything else but run Conversations - it is only logical that Conversations uses up 100% of the battery. I suspect using GCM will not necessarily change and only split the battery consumption between Conversations and Google Play Services. But the overall consumption will remain the same.

If you don't have access to adb keep an eye on the session age in account details. It should have reasonably high values (session ages of hours - under some conditions even days - are normal). Full reconnects are expensive.

**Comment by licaon-kter** [comment] 2017-08-10 10:33
> I have no idea what this is.

See the attached BetterBatteryStats-2017-08-06_183836992.txt.gz

From that log, what stands out for me:
* 1,1%/h - that's amazing, really, if I can get it <2.5%/h it would be a miracle :)
* `Awake (Screen Off) (): 4 h 59 m 46 s  6,7%` - this is rather strange, why would this be like this? Some app is keeping it awake or the system can't suspend the process. Either way there is a problem with the ROM, imho.

> Multiple daily snapshots are a bit trickier as I don't run around with a laptop :wink: Maybe I could find a logcat recorder with filtering function that works.

**Termux** (or NeoTerm or whatever) -> `su` -> `logcat -v threadtime | grep -i conversations >/sdcard/log1.txt`
do be aware those file can get big so maybe ^C every now and then: compress log1.txt as ZIP, rerun the command for `log2.txt`, rinse and repeat.

> I suspect that you have too high of a expectation regarding battery life. 

Exactly. You can't just go _"hey. it runs 5..6 days with one charge, but I want the same with a continuously active internet connection while having an app talking with 2-3-4 servers every 5 minutes"_ :-|

**Comment by IzzySoft** [comment] 2017-08-10 11:34
> 1,1%/h - that's amazing, really, if I can get it <2.5%/h it would be a miracle :)

I know this looks like a "first-world-problem". And yes, I love my Wileyfox Swift – as I wrote initially, without Conversations running one charge lasts about 6 days. Calc that, must be somewhere around 0.3%/h.

> `Awake (Screen Off) (): 4 h 59 m 46 s 6,7%` - this is rather strange, why would this be like this? Some app is keeping it awake or the system can't suspend the process.

That must be Conversations then. Of course, I could only tell for sure with a full run-down without Conversations running. Which would keep me "partly incommunicado" for about a week :wink:

> Either way there is a problem with the ROM, imho.

You're not the only one having that idea. But then tell me, why did this issue start suddenly a few months ago – and not straight away when I first installed Conversations about a year ago? So it must be something a later update triggered. I cannot tell for sure anymore, but it started about 2 or 3 updates back.

> Termux (or NeoTerm or whatever) -> `su` -> `logcat -v threadtime | grep -i conversations >/sdcard/log1.txt`
> do be aware those file can get big so maybe

Would be a way. I just tried with [MatLog](https://play.google.com/store/apps/details?id=com.pluscubed.matlog), but despite of root within the last hour it shows no single activity from Conversations or any other user apps, only from system processes (which I think is wrong). Now running `logcat` in Termux. Doubt the file won't get very big: 5 lines within 15min. Looks pretty normal.

> You can't just go "hey. it runs 5..6 days with one charge, but I want the same with a continuously active internet connection while having an app talking with 2-3-4 servers every 5 minutes" :-|

Sure not, that's what I meant. But there are other apps using the Internet as well, and GCM pings going out every 60s. Sure I expected a minor drop – but not that much. And what's more, it wasn't always that high battery values for Conversations.

> why is the battery graph missing data?

That confused me as well. I don't remember having seen that before. Having one gap again today already. But funnily, there's no battery drop immediately after the gap – so it looks like "very deep deep-sleep", not that there is something like that I'd know of.

Well, let me collect some more logcat and provide it to you. If you find something you can fix, I gladly watch things with an update to verify. If you really have no idea, I'd try switching to the Playstore version – and greenify Conversions, letting GCM take care for new messages.

**Comment by licaon-kter** [comment] 2017-08-10 12:07
Did you try an older version?

**Comment by IzzySoft** [comment] 2017-08-10 13:18
I didn't yet, no. Being on 1.19.5 currently and (AFAIR) the issue having started around 1.19.2/3, something like 1.19.0/1 could be a good guess to cross-check. If Android permits me do downgrade that is. Any issues with installing 1.19.1 over 1.19.5? If not, I of course could give that a try before switching to the GCM version.

Logcat still running. Wasn't aware Conversation merges contacts?

    21316 D conversations: start merging phone contacts with rooster
    21316 D conversations: finished merging phone contacts

I assume that means "rooster" versus "Conversations' contact list" – not the "global address book"? Must be, as I've no idea how it could merge with the latter (especially how to match contacts ;)

Apart from that: Still looks pretty normal to me. Couple of pings (Jabber.De), some "Receive PEP device list update" (followed by above contacts merger). Didn't do a line count, but not more than one line every 3..5 minutes. Afraid if you cannot find anything in the BBS dump, we won't identify the culprit by logcat anyhow – so instead of trying an older version, I'd better go straight for the GCM one which I can safely "hibernate". After the weekend that is – just in case this issue needs some additional details.

**Comment by IzzySoft** [comment] 2017-08-10 21:28
@licaon-kter I've attached a longer logcat to the initial post (`log_conv_20170810_1.txt.gz`).

**Comment by IzzySoft** [comment] 2017-08-29 15:43
Meanwhile, with another affected user, I was able to find a "common denominator". I had the feeling the issue was not as heavy when on WiFi, so I asked that other user to verify (he had switched WiFi off over night). So he left WiFi on – et voila, his battery consumption was back to normal: instead of a mid-range 2-digit value, Conversations leveled at about 5% again.

I cannot fully cross-check as I have no 24/7 WiFi coverage.

Side-note: Both of us are with the same mobile provider, though in different regions of our country. So if anyone else here is with O2 Germany, a verification would be nice. If that turns out to be the culprit, I'm not sure what can be done about it (unless we can tell the provider how to fix his network).

I've just checked other apps on the device which use mobile data automatically, and indeed DAVDroid turns up in the battery stats rather high compared to what I remember from earlier times (accounting for almost 10% where it usually was below 3%), which seems to confirm this. On the other hand, the other user reported that Threema (which he had meanwhile switched to) was *not* affected – so there might be something that can be done from the apps' ends.

Does this ring any bell? Is there hope for a solution?

**Comment by iNPUTmice** [comment] 2017-08-29 16:25
You seem to be very invested into this. However I don't think there is much we can do about this. You can start experimenting with lower and higher ping values. see Config.java
Higher ping values will of course make the radio wake up less frequently on the other if the provider kills the NAT in between the ping intervals due to inactivity Conversations will have to reconnect. And a reconnect might be more expensive battery wise.
The logcat doesn't show anything out of the ordinary. I think Conversations is working as intended. (Usually users don't expect their phone to run several days though and their displays use much more power in comparison (giving Conversations lower percentages in the battery stats.)

**Comment by IzzySoft** [comment] 2017-08-29 16:50
> You seem to be very invested into this.

Do I have a choice (except for living with a 50%+ decrease of battery)? :stuck_out_tongue_winking_eye:

> You can start experimenting with lower and higher ping values. see Config.java

Unfortunately, I cannot play with the sources – and I could find no corresponding item in settings. Currently I help myself with Greenify and Tasker (having the app greenified and Tasker waking it up twice an hour for 5 minutes), which is some compromise. Still, when bringing the app to foreground, every second time it needs to load and refresh all "channels", which is not "that nice".

And yes, I'm also one who, if possible, tries to find solutions which help others as well. Heard about 3 people quitting Conversations because of that battery problem within the past few weeks – as in their case, the battery didn't last the day anymore. Not all of them are with the same provider.

Besides: Looks you were right with "Playstore or F-Droid version does not matter as both should behave the same". To me it even looks as if the cross-installed Playstore version doesn't use GCM (I'd disabled signature check to keep my settings while switching over) – as I didn't receive a "ping" for two days, until I manually called up the app again (which is why I now let Tasker do that in intervals).

> Usually users don't expect their phone to run several days though

No, you're correct with that. But then, their phones don't do that without Conversations either. And if Conversations then causes their batteries "go dry" in the middle of the day, they are frustrated and rather switch to an alternative instead of tackling the culprit – which is what I try doing here.

**Comment by iNPUTmice** [comment] 2017-08-29 17:06
> Unfortunately, I cannot play with the sources

OK. I'm closing here then. If someone else wants to toy around with Conversations' ping setting they should have all required information in this thread.

**Closed by iNPUTmice** 2017-08-29 17:06 UTC

**Comment by IzzySoft** [comment] 2017-08-29 20:30
Umm. I was rather hoping for some debug settings to see if anything could be done application-side. Now I must hope for someone playing with the sources and finding something, which I'm afraid won't happen that easily.
