### ISSUE TITLE
Conversations crash after add a new account

### ISSUE THREAD

**Issue by colegota** [siacs/Conversations#1151] opened 2015-04-24 09:24 UTC
Hi!
I'm using Conversations since log time with a jabber.org account and recently I added an openmailbox.org account with no problems at all.
Using v1.20 from Fdroid in CyanogenMod 11.

Today I've created a new account at suchat.org and also added it to Conversations.
Then when I tried to go to Manage accounts option it crashed time by time.

I tried to uninstall it and install it again in order to clean some possible garbage...
Then configured only suchat.org account but then crashed immediately and no possible to open again because it crashed just when opening.

Uninstalled one more time and installed again configuring only jabber.org account. It works without any problem.
Added suchat.org as second account then when I try to go to Manage accounts again it crashed every time.

Before reinstall first time I received notifications request and sent several reports to bugs account as colegota (not sure if @jabber.org or @suchat.org) you maybe receive it.

So it's very strange behaviour because I have contacts with suchat.org accounts that use Conversations as client too, but my problems are only with this account.

Can you help me?

Thanks!
Colegota

**Comment by iNPUTmice** [comment] 2015-04-25 16:47
can you get your hands on the crash report and paste it here?

**Comment by colegota** [comment] 2015-04-26 12:33
Don't know how to do it.
After reinstall Conversations I can't see the crash report, jut the app finishes and show me a short message telling me that has been stopped.

Can you give me some directions to obtain the crash report?

**Comment by iNPUTmice** [comment] 2015-04-26 12:39
Does the app crash on startup if you put your phone into airplane mode?

Otherwise you will have to use adb logcat (The android debug bridge) on your computer.

**Comment by colegota** [comment] 2015-04-26 17:58
Now I can't reproduce crash at startup. I think it happened while I have no contacts at this account.
Now it chash when trying to access to Manage Accounts. 
It's the same with or without airplane mode, just the difference it's that in airplane mode I have no "app stopped" message.

Did dumped a logcat, but as it's too long and not sure what you need (but references to conversations) I've uploaded here:
tar.gz: http://www.fotolibre.org/albums/colegota/borrar/conv3.txt.tar.gz
zip: http://www.fotolibre.org/albums/colegota/borrar/conv3.txt.zip

Hope it helps.

**Comment by iNPUTmice** [comment] 2015-04-26 18:28
Thank you

should be fixed in c283fec0d1af6d4dc8c6b794a065fa1029b6d178 even though I couldn't reproduce how exactly this is happening.

**Closed by iNPUTmice** 2015-04-26 18:28 UTC

**Comment by colegota** [comment] 2015-04-29 16:10
Hi!
Admin from suchat.org has contacted me because he upgraded the server and now Conversations works fine again with suchat.org account and no problem at all.

Thanks for your support anyway.
