### ISSUE TITLE
File transfer reaches 99% and report "The file has been deleted"

### ISSUE THREAD

**Issue by milosb** [siacs/Conversations#1182] opened 2015-05-08 23:30 UTC
Hello everyone, 

We're experiencing an issue with Conversations v1.3.1 'paired' with Ejabberd v15.03. 

Namely, one of the users attempts sending a file (image) to me, and once the file transfer reaches 99% and is about to complete, 
I get "The file has been deleted" message. We've tried numerous times 5+ today and it failed every time with this same message. 
If I send him an image >3x larger (750KB), they receive it no problems whatsoever.

I've enabled the debug logging level, and you can find the log excerpt (just prior the file transfer ends, and after it ended) here: https://gist.github.com/milosb/2fd555b3c439ac6a8010

Hope it's not too modest excerpt - but with the debugging level I could attach several megs.

On both ends, Conversations client is configured with OTR encryption, and max file size to accept is set to 10MB.
Ejabberd has stanza size set to 131Kb, and traffic shaper rule is now 'fast' for everyone, even though it used to be 'normal'. There are <10 users on the server, 
and far from it there's a lot of traffic running through the server.
The OS Ejabberd is running on is CentOS 6.6 64bit.

Any ideas would be greatly appreciated. 

Thanks,
Milos.

**Comment by iNPUTmice** [comment] 2015-05-09 02:36
duplicate of #1172

**Closed by iNPUTmice** 2015-05-09 02:36 UTC

**Comment by Natureshadow** [comment] 2015-05-09 07:46
File transfer does not work when OTR is enabled. This is reproducible,
independent of the server.

**Comment by milosb** [comment] 2015-05-09 17:33
Thanks for the clarification. 

I have searched Github via Google but came up empty handed - possibly the page wasn't indexed yet...
