### ISSUE TITLE
MAM handling

### ISSUE THREAD

**Issue by mase76** [siacs/Conversations#1460] opened 2015-10-04 09:46 UTC
When you have a very long encrypted history, it takes much time when setting up
a new device with conversations. I think showing the last view messages (all from
current day, or about 10, or even configurable) would be better.
The rest of the history could either be in a calendar view, like in gajim, or something like
"pull to load more messages". I think, the last one would be less effort to implement.
What do you think?

**Comment by jkufner** [comment] 2015-10-04 09:55
Calendar approach in Gajim is very practical. Conversations allow only to scroll and croll and scroll... which is fin when browsing last 20 messages, but not so great when looking for last month message with some important data. What I miss in Gajim is button to previous day with messages, for case when there is no chat history for few days.

**Comment by iNPUTmice** [comment] 2015-10-05 15:05
I take it your issue @mase76 here is not the general amount of messages in your history but that time it takes to decrypt them with pgp?

**Comment by mase76** [comment] 2015-10-05 16:26
No, the decryption time is not the problem. A lesser amount if messages would make the chat more clear. I noticed, that you already implemented loading more messages. But once loaded, they stay visible, until you restart the app.
I am interested in, what the other users (and you) think.

**Comment by iNPUTmice** [comment] 2015-10-06 14:22
I don't understand how more messages make the chat 'unclear'. Nobody forces you to scroll up.

**Comment by alexara** [comment] 2015-10-06 15:11
I have to agree with @mase76: After a while the chat history grows quite large. Now try to find a certain message/image/file by scrolling up and down. This will take time.

Meanwhile when you send a receive a message the history jumps to the very latest message and your scrolling session starts again from the very beginning.
(Maby a "Message received: Jump down? overlay button would be good here.)

I would really appeciate to have something like calender to keep the message history short and clear.

**Comment by iNPUTmice** [comment] 2015-10-06 15:38
@alexara those issues you are mentioning are completely unrelated to the length of the history

Finding a certain message could be addressed by:  #1315 for example.

the scrolling issue is also something that could be address individually. However this limiting the size of the history would maybe ease the symptoms of the scrolling issue a bit but not make it disappear.

**Closed** 2015-10-06 15:48 UTC

**Comment by alexara** [comment] 2015-10-06 16:24
> However this limiting the size of the history would maybe ease the symptoms of the scrolling issue a bit but not make it disappear.

Of course not. For making it disappear you would have to address the cause: Prevent users from writing messages. ```</irony>```

Isn't it better to relieve an issue as much as possible than to leave it as it is?

**Comment by strb** [comment] 2015-10-06 16:37
> Isn't it better to relieve an issue as much as possible than to leave it as it is?

Well, you're presenting a false dichotomy here. It actually seems preferable to fix the original issue (i.e. in this case address these specific problems themselves, separately) rather than applying somewhat arbitrary changes to unrelated features (decreasing their utility in the process) in an effort to mitigate the effects of those original issues. Introducing this proposed limitation would amount to a half-assed band-aid fix at best.

**Comment by alexara** [comment] 2015-10-06 19:24
> Well, you're presenting a false dichotomy here.

I thought I got the point of the original issue but it seems I was wrong. In this case, I'm sorry. Please ignore my posts and focus on the OT. ;-)
