### ISSUE TITLE
Visible encrypted OTR messages

### ISSUE THREAD

**Issue by MiskyWhixer** [siacs/Conversations#1370] opened 2015-08-28 07:43 UTC
Since 1.6.x version I got a lot of visible encrypted OTR messages in my OTR chats.
There are even encrypted messages when no one writes a message. (Handshake?)
No chat message is missing. Just the encrypted ones on top.
It seems like Conversations turn off the encryption at this time.
Is there a way to filter messages with '?OTR:' and '?OTRv' in the beginning as workaround?
Conversations 1.6.6
OpenFire Server 3.10.2
Android 5.1.1r13

![tmp_18087-screenshot_2015-08-28-09-18-45-112414419](https://cloud.githubusercontent.com/assets/8101397/9541397/07493b46-4d68-11e5-8f42-5200126dc149.png)

**Comment by mhde** [comment] 2015-08-28 10:22
I can confirm this bug on Conversations 1.6.6 & ejabberd 15.07.

**Comment by iNPUTmice** [comment] 2015-08-28 10:26
both of you are using MAM I assume?

**Comment by mhde** [comment] 2015-08-28 10:28
Yes, MAM is used.

**Comment by iNPUTmice** [comment] 2015-08-28 11:28
thats your server ignoring our *no-permanent-store* message hints and storing OTR messages in MAM. (I think if you upgrade your server and use mod_mam_mnesia this should be fixed)

**Comment by mhde** [comment] 2015-08-28 11:39
I've upgraded to mod_mam_mnesia  from mod_mam. I will report back in case the issue returns.

**Comment by MiskyWhixer** [comment] 2015-08-30 20:10
Yes, my Server uses MAM too.
On OpenFire there is a plugin for MAM (Monitoring Plugin with message archiving support)
http://www.igniterealtime.org/projects/openfire/plugins/monitoring/changelog.html
I have installed the current plugin (1.4.6 wich added support for XEP-0313).
For now I have disabled the plugin for testing.

**Comment by Tokodomo** [comment] 2015-09-01 18:22
In my case, only the file transfer announcements via OTR seemed to be stored on the server (in MAM), normal OTR and all OMEMO messages are not stored in MAM (the server is jabber.at). Please take a look at my screenshots, the first one is before and the second one after reloading the chat history via MAM. Maybe Conversations doesn't give those "no-permanent-store message hints" on file transfer announcements via OTR?

![screenshot_2015-09-01-17-47-44](https://cloud.githubusercontent.com/assets/13941754/9610705/7e686780-50db-11e5-9605-98cb11a1ee24.png)
![screenshot_2015-09-01-17-50-00](https://cloud.githubusercontent.com/assets/13941754/9610712/8a2c7930-50db-11e5-9bf4-9be50e131e26.png)

**Comment by iNPUTmice** [comment] 2015-09-01 20:37
@Tokodomo good catch. Fixed in: 91b0605bc29cbba55abbb32293c4b632608a00bf

**Comment by Tokodomo** [comment] 2015-09-01 21:00
@iNPUTmice 
Wow, that was fast! Thanks a lot.

**Comment by chaoscommander** [comment] 2015-10-23 17:20
I would like to attach to this the following observation: Whenever Conversations receives unexpected OTR messages (for example after switching from a desktop client without first ending the session), they are displayed as plain text. No OTR ERROR is sent, the session doesn't get renegotiated, the chat partner has no opportunity to re-send unreadable messages because they are never notified of the failure (unless I do it manually). I'd expect Conversations to reply to EVERY unexpected or unreadable OTR message with an OTR error code so the remote client can renegotiate and resend stuff. Running the latest version from F-Droid.

**Comment by SamWhited** [comment] 2015-10-23 17:27
> I'd expect Conversations to reply to EVERY unexpected or unreadable OTR message with an OTR error code

How do you know if a message is an unreadable OTR message? If I send you the message:
```
?OTR: <- what does this thing mean at the begining of those random messages you keep sending me?
```

should that send back an error message too? As far as Conversations is concerned, that would proably also look like an "unreadable" OTR message.

This is one of the big problems with OTR; it's not really designed for XMPP. It's designed to be a "one size fits all" solution (which, as usual with anything that's one-size-fits-all, fits almost no one).

**Comment by chaoscommander** [comment] 2015-10-23 17:32
I guess there's something else, because Pidgin doesn't understand a typed-out "?OTR" as an OTR message and replys to all others with an error. But I haven't read the source code for OTR implementations, so what do I know.

**Comment by arkenoi** [comment] 2016-01-16 09:36
I agree. If there is an OTR message which is out of the line and cannot be decrypted, it should NOT be displayed to user unless he explicitly says so in advanced settings. Otherwise you just get a lot of meaningless garbage if there is more than one client device and/or server is misbehaving. Please remember that situation where server is not under a users' control is quite common.

**Comment by iNPUTmice** [comment] 2016-01-16 10:48
> I'd expect Conversations to reply to EVERY unexpected or unreadable OTR message with an OTR error code

Conversations DOES in fact reply to every unreadable OTR messages with an error. But of course only for messages that were directed to us.

What you are seeing are either Carbon copies of OTR messages which should be suppressed by the sending client or messages that were loaded from MAM.

In neither of those cases Carbon nor MAM should Conversations respond with an error messages because this could break an established OTR connection between two other resources.

> This is one of the big problems with OTR; it's not really designed for XMPP. It's designed to be a "one size fits all" solution (which, as usual with anything that's one-size-fits-all, fits almost no one).

This is the actual issue here.

Just use OMEMO.

**Comment by arkenoi** [comment] 2016-01-16 11:14
Ok, then why not hide that MAM messages from user?

**Comment by sedrubal** [comment] 2016-09-14 10:53
The most real otr messages don't have whitespace and have valid base64 strings behind the `?OTR:` :wink:

**Comment by varac** [comment] 2018-03-27 14:43
Still happening also with conversations 2.0. Please reduce the noice to some oneline-message indicating that a OTR messages was recieved which cannot get decrypted because OTR was removed or sth like this.

**Comment by iNPUTmice** [comment] 2018-03-27 15:00
Other clients should not send that garbage to use. OTR support has been removed

**Closed by iNPUTmice** 2018-03-27 15:00 UTC

**Comment by varac** [comment] 2018-03-27 15:34
see myupdate on https://github.com/siacs/Conversations/issues/1998#issuecomment-376570208
