### ISSUE TITLE
[BUG]Multiple instances of same account on same installation possible

### ISSUE THREAD

**Issue by vijai1996** [siacs/Conversations#1175] opened 2015-05-07 10:04 UTC
Hello, 
       Currently Conversation allow you to add a account which is already signed in in the same app which at times lead to confusion. It would be better to check if the account exists already before adding a new account.
Way to reproduce:
1. Add account abc@xyz.com
2. Add another account with user same as abc@xyz.com

**Comment by strb** [comment] 2015-05-14 14:05
Thank you for reporting. I was unable to reproduce this with the steps you gave. Conversations correctly detects existing accounts. 

I did, however, identify a related issue, which should be fixed in b69ee7125d49493bea86c6e3095f1236ad895980. Does this fix your problem?

**Comment by iNPUTmice** [comment] 2015-05-21 14:16
no reaction in a week. assuming that means yes

**Closed by iNPUTmice** 2015-05-21 14:16 UTC
