### ISSUE TITLE
Notification on failed message delivery

### ISSUE THREAD

**Issue by RalfJung** [siacs/Conversations#1754] opened 2016-03-09 21:41 UTC
Earlier today, I sent a message to a friend and then quickly put the phone away to enter a bus. Only 30min later, I noticed that the message actually had not been sent (I guess WiFi dropped when I got into the bus, and LTE wasn't established quickly enough, or whatever) -- which was rather unfortunate in this situation.

It would be great if Conversations could issue a notification (and trigger vibration or a tone) when message delivery fails so that users do not incorrectly rely on the message having been sent successfully.

**Comment by iNPUTmice** [comment] 2016-03-10 13:48
duplicate of #1704 and #229 and there is a FAQ section of 'delivery failed'

**Closed by iNPUTmice** 2016-03-10 13:48 UTC

**Comment by RalfJung** [comment] 2016-03-10 14:05
I have read over #229 before posting this, could not find a reference to "how to inform the user when delivery fails". #1704 does not mention this either. And neither does the FAQ. Note that "smacks_offline" *is* enabled on my server.

These issues essentially propose various things for making these delivery errors not happen, or making them more informative, or whatever. I am talking about what to do if they *do* happen; namely, not just adding a tiny red text to the message but also letting the phone vibrate so that the user notices that something went wrong. Could you please reopen, or else explain how the FAQ entry and the other issues are helping here?

**Comment by RalfJung** [comment] 2016-03-17 08:07
@iNPUTmice could you please read the issue I reported again? The duplicates you mention are actually different issues, as far as I can tell; same goes for the FAQ entry.
