### ISSUE TITLE
Implement XEP-0224

### ISSUE THREAD

**Issue by lorenz** [siacs/Conversations#2638] opened 2017-09-22 09:54 UTC
I would like to implement XEP-0224 in Conversations, mainly because I want to have paging support in Conversations. There are a few open questions though:

1. How do we want to implement the actual attention-grabbing behaviour? For my specific use-case I'd like my phone to constantly ring until either another client sends a read acknowledgement or I read the message in Conversations. This is rather extreme and optimized for paging, we probably also want something a bit less aggressive like a notification tone that disregards Android notification settings.

2. How to deal with delayed messages and multiple clients? I prefer to have the above behavior of using read receipts to coordinate between clients and not just have all clients ring indefinitely and not ignoring delayed messages if they aren't marked as read anywhere. This is a deviation from the XEP though (at least in behavior, not in network spec), so I'm not sure if that's accepted here.

3. How do we deal with who is allowed to actually send these? I do not want everybody to be able to send such messages so we probably have to have some kind of whitelist.

I'm open for suggestions on this proposal.

**Comment by iNPUTmice** [comment] 2017-09-22 10:07
duplicate of #979

**Closed by iNPUTmice** 2017-09-22 10:07 UTC
