### ISSUE TITLE
Sharing (GBoard) Stickers converts animated/transparent gifs in a wrong way

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#3058] opened 2018-06-03 18:16 UTC
#### General information

* **Version:** 2.2.2
* **Android Version:** Android 6.0, CyanogenMod
* **Conversations source:** eg PlayStore

#### Steps to reproduce

1. Use GBoard
2. Download some silly sticker sets
3. Open a conversation
4. Send a sticker

#### Expected result

The sticker is sent "as is". Independent from how it is displayed, it should not be converted in a way which damaged its properties

#### Actual result

The sticker is sent as a ``.jpg`` file which transparent pixels replaced by black. This isn't nice for animated stickers and a real problem for stickers with black text on transparent background. 
This wouldn't be a too big problem, if the file itself would be available unchanged and opening in gallery or one of the gif-viewer apps would display it correctly.

**Comment by iNPUTmice** [comment] 2018-06-05 06:58
I’m unable to reproduce this. Please provide adb logcat output.

**Comment by allo-** [comment] 2018-06-06 16:49
```
06-06 18:46:08.225 31258 14933 D conversations: copy image (content://com.google.android.inputmethod.latin.inputcontent/inputContent?fileName=%2Fdata%2Fuser%2F0%2Fcom.google.android.inputmethod.latin%2Ffiles%2Fsticker728765590&packageName=eu.siacs.conversations&mimeType=image%2Fpng) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/979c112c-6516-4b60-9cdd-2c3cbde7165b.jpg
06-06 18:46:08.265 31258 31258 D conversations: received uri permission for content://com.google.android.inputmethod.latin.inputcontent/inputContent?fileName=%2Fdata%2Fuser%2F0%2Fcom.google.android.inputmethod.latin%2Ffiles%2Fsticker728765590&packageName=eu.siacs.conversations&mimeType=image%2Fpng
06-06 18:46:08.294 31258 14933 D conversations: reading bitmap with sample size 1
06-06 18:46:08.308 31258 14933 I CameraExif: Orientation not found
06-06 18:46:08.349 31258 14933 D conversations: send file message
06-06 18:46:08.399 31258 15126 D conversations: uploading to https://myserver:5281/upload/AQt7FIjOl20ufies/l5wRLGUWS2Cc3Sw8vecWWw.jpg w/ read timeout of 24s
06-06 18:46:08.590 31258 15126 D conversations: finished uploading file
06-06 18:46:08.609 31258 15126 D conversations: AxolotlService (my@jabberid): Cache miss: 979c112c-6516-4b60-9cdd-2c3cbde7165b
06-06 18:46:08.735 31258 14947 D conversations: AxolotlService (my@jabberid): Generated message, caching: 979c112c-6516-4b60-9cdd-2c3cbde7165b
06-06 18:46:08.736 31258 14947 D conversations: AxolotlService (my@jabberid): Cache hit: 979c112c-6516-4b60-9cdd-2c3cbde7165b

```

The image had a transparent background and has a block one afterwards and is stored as JPG. When I read the log correctly, the gboard app sends a png (and for animations probably a gif) to conversations, which is then converted before being sent for some reason.

**Comment by iNPUTmice** [comment] 2018-06-06 17:22
Have you actually tried with gifs? Because I can’t reproduce this with gifs. I might be able to reproduce witht png if i manage to find one.

**Comment by allo-** [comment] 2018-06-06 19:17
The problem is the "compress images" option, which converts PNG files to JPG.

**Comment by JuniorJPDJ** [comment] 2018-06-07 09:12
I think that there should be quick switch for compression
I also send some smaller images and some bigger photos, and i dont want conversations to do anything with my images, but it could compress photos.
There should be configurable sizes or quick switch/separate options in send menu

**Comment by iNPUTmice** [comment] 2018-06-07 10:18
@JuniorJPDJ use 'send file' instead of 'send picture' if you want to send files untouched

**Comment by allo-** [comment] 2018-06-07 15:32
For things like stickers and other stuff which may be sent from other apps, it is impracticle to switch the mode before sending (and back again after sending) and there is no reason against scaling the image.
It should just be scaled as PNG and not converted to JPG.

**Comment by iNPUTmice** [comment] 2018-06-16 06:27
This has been fixed in 2.2.3

**Closed by iNPUTmice** 2018-06-16 06:27 UTC

**Comment by kuba86** [comment] 2018-08-29 10:02
I am  facing this issue now with beta version. When sharing stickers on WhatsApp or Signal I get black background. But when I share to Gmail it attaches stickers as PNG files with white background.

**Comment by Alendwarf** [comment] 2018-10-06 01:32
This is actually happening to me while using Gboard and WhatsApp, all background goes black

**Comment by radkoa** [comment] 2019-04-01 20:12
Same for me with Viber

**Comment by DarioChan** [comment] 2019-09-26 15:19
Was this ever solved? I am also getting this issue. I have Transparent PNG's loaded into my Android Sticker Moji app (I have also tried a transparent GIF - also doesn't work). When I go to send one using the app, it sends a JPG instead, with a black background. It looks horrendous. When I save that image, it has a new numbered name, so it seems it is being converted before sending it through Messages or FB messenger or whatever.

What is the fix?

**Comment by licaon-kter** [comment] 2019-09-26 16:03
@DarioChan did you put Image Compression to Never in Settings?

**Comment by DarioChan** [comment] 2019-09-26 16:06
> @DarioChan did you put Image Compression to Never in Settings?

Thanks for responding. Sorry, you'll have to explain this like I am a newb. Is this in Android settings on a particular phone or within the coding of the app? @licaon-kter

**Comment by licaon-kter** [comment] 2019-09-26 16:45
@DarioChan the app you posted this issue to...

**Comment by DarioChan** [comment] 2019-09-26 16:49
@licaon-kter So I've looked through the Gboard settings, there is no option for image compression. I also have my Messages android app set to Send Original picture.
The app that actually has the stickers is my app that I had coded. I'm trying to find out what code was done that is causing it to convert my transparent PNGs to jpgs with black backgrounds. Online I am finding things called "Intent", and I am wondering if my share intent is automatically converting my PNGs to JPGs, but I am hoping someone here would know the answer.

**Comment by allo-** [comment] 2019-09-26 16:51
Is there a reason, why scaling needs to change the format? You could just resize transparent GIF/PNG images and keep them in the same format. I do not know which image libary you're using, but it probably already supports these formats as output.

**Comment by licaon-kter** [comment] 2019-09-26 18:22
@DarioChan in Conversations settings....look dn Conversations!!!!

**Comment by DarioChan** [comment] 2019-09-26 19:02
@licaon-kter 
Again, the Android native app for texting is called Messages. I have looked in their settings and set the image quality to original. This does not affect the Sticker/Moji app I am programming which has the issues. There is no app called Conversations. I am running Android 9.0 with OnePlus Oxygen.

I am realizing now that this entire thread is under an app called Saics and there is a thing called Conversations there 🤦‍♂️. I am not working with siacs so this might have been the wrong place to ask this question.

It was the only thread I could google that was similiar to my issue - namely that I am programming a Moji app in Android studio, and when the user is prompted to share my transparent PNG image, it instead converts it into a jpg with a black background, which happens in Gboard too. I am not scaling the image in the code, unless you are saying that it happens automatically in the background. @allo- Were you ever able to fix this?

**Comment by licaon-kter** [comment] 2019-09-26 19:42
@DarioChan Siacs is the group of devs name, the app name is "Conversations"


Do report this error to the app developers instead...aka to the Oneplus Forums (I guess)

**Comment by sban2009** [comment] 2021-08-16 09:16
Amazing it's 2021 and still no fix

**Comment by licaon-kter** [comment] 2021-08-16 09:36
@sban2009 same keyboard? Which device/os?

**Comment by sban2009** [comment] 2021-08-16 09:38
Moto G8 Plus - Android 10

GBoard on WhatsApp

**Comment by sban2009** [comment] 2021-08-16 10:00
> @sban2009 same keyboard? Which device/os?

Sorry. Wrong thread.
