### ISSUE TITLE
MUC secure

### ISSUE THREAD

**Issue by XmppVictory** [siacs/Conversations#502] opened 2014-09-27 08:50 UTC
Further along consider mpOTR (otr for muc).  Jappix dropped the ball on this.  Crypto.cat is less than ideal.

**Comment by d9h02f** [comment] 2015-08-15 18:44
I think this can be closed now that OMEMO is available.

**Comment by andersruneson** [comment] 2015-08-15 18:45
Does OMEMO work for MUC?

**Comment by strb** [comment] 2015-08-15 18:52
Nope. OMEMO is only for (multi-ended) one-on-one conversations. 

While there are some very tentative ideas floating around on how to extend this to MUC, there are still a number of unsolved challenges. It's not likely that OMEMO extension for MUC will happen before MUC2 is standardized/implemented.

**Comment by d9h02f** [comment] 2015-08-15 18:54
Ah, seems I misunderstood. Thanks.

**Comment by knoy** [comment] 2015-09-01 01:06
This is a duplicate of an issue I started recently (and didn't see until now), some of you may be interested in the discussion in that thread:  https://github.com/siacs/Conversations/issues/1372

**Comment by iNPUTmice** [comment] 2015-09-01 08:10
I'm actually closing this because @knoy's issue #1372 describes/tracks the issue in a more accurate way

**Closed by iNPUTmice** 2015-09-01 08:10 UTC
