### ISSUE TITLE
[FR or Bug] Constant lock screen bubble with no useful info

### ISSUE THREAD

**Issue by bahur142** [siacs/Conversations#3109] opened 2018-07-10 20:00 UTC
#### General information

* **Version:** eg 2.2.5
* **Device:** Xiaomi Mi6
* **Android Version:** Android 8.0, MIUI10
* **Launcher:** Default
* **Server software:** prosody 0.10
* **Conversations source:** PlayStore

I have attached a screenshot of my lock screen. There is constantly a bubble from Conversations in general - useless for me with no actual information. It is not only on lock screen, it is also on notification panel when unlocked. I can not find a way to remove it unless disable all notifications from Conversations.

I am not sure is it feature of the current ROM or feature of Conversations, but I will be very happy to find a way to turn it off.
![screenshot](https://user-images.githubusercontent.com/30805725/42534254-ef170f8c-8494-11e8-9ed6-6dc793e9571c.jpg)

**Comment by licaon-kter** [comment] 2018-07-10 20:19
Xiaomi? 

If you disable settings-expert-foreground service it will disappear, it's not a bubble, it's a notification, Android it self forces it upon us

But, without it MIUI will kill the app sooner rather than later and you won't get the messages. 

Choose wisely

/close this as not a bug per se
 
/PS: #2831 or #2921 might fix this somewhat

**Closed** 2018-07-11 08:00 UTC
