### ISSUE TITLE
Limit frequency of notifaction sounds

### ISSUE THREAD

**Issue by steffanson** [siacs/Conversations#1746] opened 2016-03-04 12:57 UTC
Currently a notification sound is played for each message which result in a lot of "beep" when a contacts send a lot of single messages and the speakers are turned on.
The issue is that if I receive a message and hear the notification I'm already informed and thus do not need further notification for each single message. 

Wouldn't it more convenient to add an option to only play notification sound once in 1/2/3 minute(s)?

I think it'd also make sense to add an option for not playing a sound when the app is in the foreground since I already see on the screen that I received message and don't need to be bothered by the noise.

In the end it's not about disabling the notification sound completely but to limit its use to situations where it's actually useful.

**Comment by iNPUTmice** [comment] 2016-03-04 20:44
duplicate of #762

**Closed by iNPUTmice** 2016-03-04 20:44 UTC
