### ISSUE TITLE
The behavior of enabling OMEMO as standard automatically is causing message loss for unsupported clients

### ISSUE THREAD

**Issue by Testertime** [siacs/Conversations#1908] opened 2016-06-12 12:02 UTC
The current Conversations version is 1.13.0 (F-Droid) and I have tested this with the computer Jabber clients called Jitsi and Miranda NG.

Steps to reproduce

1. You and your partner are starting a conversation while both of you are using the Conversations app. The app selects OMEMO automatically without asking the user.
2. Now your partner quits the chat and is using a different client which isn't Conversations and has no OMEMO support (for example Miranda NG or Jitsi in this case). _Yes, it's still reality, okay?._
3. On your device OMEMO is still selected as the default encryption method. Now you are going to write a message. With message receipts enabled, it even shows that the message has even reached the client. But your partner isn't able to see the message at all! It's like that the message ended in a black hole, as the client was unable to understand it.

Expected result

Either Conversations should automatically restore the previous user-selection, as Conversations has changed it _without_ userconsent. Or it should automatically choose a compatible encryption method, like OTR, or in the worst case even clear text. But message loss due to this OMEMO enforcement is not okay.

Conclusion

This has caused serious frustration until I have found out what was going on. Novice users are not assuming that something went wrong, and this really needs a fix. Either this OMEMO selection behavior shouldn't be so pushy, the automatic selection needs a major improvement, like selecting OTR for clients where it's supported, or we need an expert setting to disable the automatic selection. I can't tell my novice contacts that they have to pay attention to the pad lock icon every time, this is causing frustration and sometimes comments how complicated it is... No, I won't use Conversations all the time, and yes, sadly it's taking time until an OMEMO plugin for Miranda NG is released. So a fix is really necessary.

Thanks a lot!

**Comment by d9h02f** [comment] 2016-06-12 12:32
The message isn't lost, you'll get it next time you open up Conversations.

**Comment by iNPUTmice** [comment] 2016-06-12 12:51
Turns out our fallback message wasn't working properly. Fixed in f4e3cd509874009e2baa024337973e958c586863 and soon in 1.13.1

Gajim works great and has OMEMO support.

**Comment by iNPUTmice** [comment] 2016-06-12 13:14
> or we need an expert setting to disable the automatic selection

an expert setting on your end won't influence the automatic selection on your contacts end

>  I can't tell my novice contacts that they have to pay attention to the pad lock icon every time

You don't have to do this every time. Just once. If it's turned off once it will stay off

> selecting OTR for clients where it's supported,

OTR has always been a horrible hack for XMPP. There is no way to discover if your contact supports it.

> Either Conversations should automatically restore the previous user-selection

That's called downgrading and is usually not desirable because it can be used to attack you.

>  changed it *without* userconsent.

Some things don't need user consent. Like we also don't ask the user if it's ok to turn on TLS


Look I'm sorry you had a bad experience that was caused by the fall back message not working. (That's fixed now)

The question whether or not to enable e2e by default is not an easy one to answer.
We simply can not wait for your weird unmaintained multi-protocol client to eventually support OMEMO. Spoiler alert this is not going to happen.
My reasoning is that it is always easier to turn off e2e (Just tell your contacts once) than it is to turn it on.

**Closed by iNPUTmice** 2016-06-12 13:14 UTC
