### ISSUE TITLE
Message delete

### ISSUE THREAD

**Issue by nikolanik** [siacs/Conversations#1407] opened 2015-09-13 17:36 UTC
Will be nice to have posibillity for deleting one or multiple messages from conversation, not whole chat...

**Comment by SamWhited** [comment] 2015-09-13 17:43
Duplicate of #1100, #1037, #627, and probably others that a cursory search didn't reveal.

**Comment by iNPUTmice** [comment] 2015-09-13 17:49
Adding something to the discussion I haven't mentioned before but is one of my primary concerns with this feature: I have the feeling that the most common reason this feature gets requested is to delete garbage messages (OTR and duplicate messages) however those messages should be prevented from happening at all instead of providing the user with a way to delete them.

**Closed by iNPUTmice** 2015-09-13 17:49 UTC

**Comment by alexara** [comment] 2015-09-18 13:17
I think there is a reason where message deletion may be a useful feature:

* An image which should not be send and where the file transmission has been intentionally canceled takes a huge space in the local chat history, blowing it up and reducing the overview.

It's a pity, that it's not possible to hide or delete it. It would be greate to delete intentionally cancelled transmissions.

**Comment by knoy** [comment] 2015-09-18 15:28
I think there are legitimate use cases for this. Most notably, you have a private conversation with someone discussing a third-party, you then need to show this third-party some of these messages without revealing some other things you said. If you can delete the confidential messages and then show them the rest, this is easy to do

**Comment by knoy** [comment] 2015-09-18 15:29
It could be done in a context menu next to "Copy message" after long-pressing
