### ISSUE TITLE
crashing after upgrading to android N

### ISSUE THREAD

**Issue by canary5** [siacs/Conversations#2029] opened 2016-09-20 04:04 UTC
http://pastebin.com/8BFsQAcP

**Comment by canary5** [comment] 2016-09-20 14:56
I have checked changelogs, fix rare statup crashes. Is it supposed to fix this issue?

**Comment by iNPUTmice** [comment] 2016-09-20 15:03
> I have checked changelogs, fix rare statup crashes. Is it supposed to fix this issue?

Nope. I can't make anything out of your stack trace. Looks a bit like a weird ROM problem. You might want to supply more information what ROM/phone do you use.

**Comment by canary5** [comment] 2016-09-20 16:12
Its CopperheadOs, nexus 6P. I have opened ticked there too

**Comment by lagosazules** [comment] 2016-10-21 08:08
Still no ETA for this fix? It is very annoying thi  bug, Conversations is in my opinion one of the most important application to use with CopperheadOS, hope for a quick solucion.

**Comment by lagosazules** [comment] 2016-10-21 08:13
Comments from thestinger on Copperhead bugtracker:

ETA == when one of you feels like contributing a fix for it.

It's probably caused by exec spawning. Step one: make a build without exec spawning. Revert 514fe7f117db62704d8759d83c27ad8fc3ccbf8b and eb00f8dff5dfb4ac080540a9179dca30b48cca28 (in that order).

If that doesn't work, revert b8d123b8554f34cfea46148b248c84e9ecd190e5 and then fa54c344d37380414e1cab5d037fe10301e6d38b in that order too. If that works, revert the eb00f8dff5dfb4ac080540a9179dca30b48cca28 revert then the 514fe7f117db62704d8759d83c27ad8fc3ccbf8b revert to determine if enabling preloading while still using exec spawning fixes it.

That's the easy part. Assuming one of those things is the cause, figure out why it happens. Doing that kind of thing will often take days of work or more. Can use a debugger, strace, perf trace, etc. It seems to be a race, so setting affinity to pin to a single core might help with debugging. Maybe it's something that TSan could figure out but I doubt it.

Not planning on working on it though. It seems like an AOSP or app bug uncovered by exec spawning. So I need evidence it's a CopperheadOS bug to devote my limited time to working on it. That's how this works.

**Comment by lagosazules** [comment] 2016-10-21 08:41
https://github.com/copperhead/bugtracker/issues/443

**Comment by iNPUTmice** [comment] 2016-10-26 18:29
Can somebody with Copperhead OS try this branch? https://github.com/siacs/Conversations/tree/possible_copperhead_fixes

**Comment by iNPUTmice** [comment] 2016-10-29 09:49
Copperhead believes this to be an upstream bug. No one in here cares enough about this bug to try the branch I linked so I'm closing here.

**Closed by iNPUTmice** 2016-10-29 09:49 UTC

**Comment by canary5** [comment] 2016-10-29 17:41
Hello. Thanks but it still crashing

**Comment by licaon-kter** [comment] 2016-10-29 18:59
New log?
