### ISSUE TITLE
Don't search archived messages when it is off in account

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2241] opened 2017-01-19 01:42 UTC
Have some accounts with Archive: Never, every time I open a chat (not a new chat), I get toasts with "Downloading archived..." and imediately "No archived messages"

**Comment by iNPUTmice** [comment] 2017-01-20 09:40
The problem here is that we don't know if the archive is enabled or not. (We only know if it is available.)
I can talk to the MAM author and the server implementers to add a way to discover this during disco but don't hold your breath.

**Comment by licaon-kter** [comment] 2017-01-20 12:26
I don't follow, so that setting for each account, does not matter here?

**Comment by iNPUTmice** [comment] 2017-01-20 12:32
The problem is that we can't discover that setting automatically. We would have to make even more requests to the server just to figure that out.

**Comment by licaon-kter** [comment] 2017-01-20 12:47
Ok, nice.

Now, some issues:
* the user chose no archiving but
* the app checks that setting every time you connect to that server
* the app informs the user that it checks
* the app informs the user that it found none

Now, some ideas:
* check once on adding the account
* if the server has it, maybe pop-up a dialogue with `hey, you like them archived or not`
* if the server does not, don't
* but the server might add that, ok, maybe check from time to time, even on every connect, but don't say anything unless it will be detected as available
* then maybe pop-up a dialogue with `hey, look like the server now has this, you like them archived or not`
* also, check when the user opens the `archive` in account options

**Comment by iNPUTmice** [comment] 2019-01-13 20:01
I’m closing here because we can’t tell beforehand if messages are stored in the archive. Even if the archive is disabled *now* it might still have old messages in it.

**Closed by iNPUTmice** 2019-01-13 20:01 UTC
