### ISSUE TITLE
User presence loss in conference after reconnection

### ISSUE THREAD

**Issue by Mishiranu** [siacs/Conversations#1971] opened 2016-07-27 12:22 UTC
#### General information

* **Version:** 1.13.6
* **Device:** Android Emulator
* **Android Version:** Android 6.0
* **Server name:** jabber.ru
* **Server software:** ejabberd
* **Conversations source:** self build (at 1.13.6 release commit)

#### Steps to reproduce

1. Join a conference
2. Simulate connection loss (e.g. enable and disable flight mode)
3. Wain until account reconnected
4. You are the only user in conference

#### Debug output

```
07-27 11:56:56.296: D/conversations(3762): ...: online with resource phone
07-27 11:56:56.296: D/conversations(3762): ...: fetching roster
07-27 11:56:56.301: D/conversations(3762): ...: running mam query with=..., start=2016-07-26T23:56:55.993Z, end=2016-07-27T11:56:55.993Z
07-27 11:56:56.315: D/conversations(3762): ...: successfully enabled carbons
07-27 11:56:57.339: D/conversations(3762): ...: joining conversation ...
07-27 11:56:57.339: D/conversations(3762): ...: fetched muc configuration for ... - [vcard-temp, http://jabber.org/protocol/muc, muc_hidden, muc_persistent, muc_open, muc_semianonymous, muc_moderated, muc_passwordprotected]
07-27 11:56:57.396: D/conversations(3762): ...: finished mam after 0 messages. messages left=true
```

Every time I joined conference I received a presence from all users. But after reconnection it seems that I receive only 1 presence packet — it's a presence of mine.

Is there a way to fix it?

**Comment by iNPUTmice** [comment] 2016-07-27 12:34
This sounds like a server bug to me. Some old prosody servers are known for this behavior for example. (The server which hosts the conference is relevant for this. Not your own server.)

**Comment by Mishiranu** [comment] 2016-07-27 12:41
The conference server is jabber.ru too (conference.jabber.ru). I'll try to reproduce this bug on another server.

**Comment by Mishiranu** [comment] 2016-07-27 13:43
I've created a conference on conversations.im server and I still receive only my presence using my jabber.ru account (in case of conversations.im account I receive a "resumed" packet).

So I've tested on I third server and I still received only my presence when I've reconnected. But there was these lines in logcat output:

```
07-27 13:36:09.818: D/conversations(3825): ...: fetching members for ...
...
07-27 13:36:12.062: D/conversations(3825): ...: retrieved members for ...: [...]
```

and this bug didn't appear in this conference. Now I know, that this is a result of request in `fetchConferenceMembers` method — a direct request of users in conference.

And it seems that this method doesn't called for the first conference because id doesn't have a `muc_membersonly` feature (`if (mucOptions.membersOnly() && mucOptions.nonanonymous())`).

**Comment by iNPUTmice** [comment] 2016-07-27 14:15
If you resume a session you won't receive any presences anyway.

The member fetching is independent of the presences. You should still receive the presences even if Conversations doesn't explicitly request the members.

**Comment by Mishiranu** [comment] 2016-07-27 14:23
But I tested it on 2 servers (jabber.ru and bakka.su (a random server I found for testing)) and they both sent me only my presence after reconnection. Maybe it's a normal behavior?

**Comment by Mishiranu** [comment] 2016-07-27 15:24
When I completely commented the line `this.streamId = enabled.getAttribute("id");`, I began to receive a presence from all online users in conference.

When this line it not commented, I receive `<failed xmlns="urn:xmpp:sm:3">` from server after sending `<resume h="23" xmlns="urn:xmpp:sm:3" previd="..."/>` and later I receive only my presence in conference.

**Comment by iNPUTmice** [comment] 2016-07-27 15:42
@Mishiranu this is perfectly fine behavior. But removing that line you are essentially disabling Stream Management which leads to:
> If you resume a session you won't receive any presences anyway.

Sorry i'm closing here. Your original problem might be caused by a malfunctioning server and your subsequent questions are all based on wrong assumptions and wrong test cases.

**Closed by iNPUTmice** 2016-07-27 15:42 UTC

**Comment by Mishiranu** [comment] 2016-07-27 16:47
Sorry for disturbing, I've contacted with server's maintainers and they confirmed this bug on their side.
