### ISSUE TITLE
Add possibility to verify the last x messages if they were delivered and fetch them if not

### ISSUE THREAD

**Issue by Killerjoe** [siacs/Conversations#2192] opened 2016-12-18 12:59 UTC
#### General information

* **Version:** 1.15.0
* **Device:** eg Galaxy Note Edge, Huawei P9 lite
* **Android Version:** Android 6.0 Stock
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore

I don´t know how to reproduce this problem.
In the last days some people from our conversations group have recognized that some messages are not displayed in our muc on theirs handys.
I can see these messages in conversations but some can not and getting angry about using conversations.
I tried to give some hints what they should configure in their phones to prevent message lost.
But of course I can not really do that on every phone and can only try to provide help but can not bring back the lost messages
Even if this problem was solved by some kind of setting (battery optimization for example) the previous lost messages can not be recovered.
There is currently no way to bring missing messages back in conversations and I don´t really know why it happens but thougt about that such situations can happen because of different things but there is no way to recover.

#### Expected result

It should be possible to add a functionality which will compare/check the last x (maybe 50-100) messages in conversations and on the xmpp server and verify only the numbers and sizes of the messages and if they are differ then fetch them from the server again to conversations and display them.
This would help to recover messages and also would help to reduce the data usage because only numbers and sizes are compared and only missing messages are getting resend/fetched.
This should happen everytime conversations is connectiong to a xmpp server.

I hope you can implement some functionality like this to recover lost messages. I think it would be helpful for everyone.

#### Debug output

I can not provide you with a adb logcat output because it is unclear when these situations happen and it seems it doesn´t happen on my phone.
I have the debug logfile from prosody but don´t know if it helps and don´t know for what I should search for.

**Comment by iNPUTmice** [comment] 2016-12-20 08:05
Prosody is currently missing a certain features that causes MUC OMEMO not to work in one particular situation: When the recipient is catching up with the backlog (after being offline for a while) and if at this point the original sender isn't available. Due to the missing feature in Prosody we also can't just re fetch the messages.

**Comment by Killerjoe** [comment] 2016-12-20 12:01
Thank you for clarification @iNPUTmice. This is a big issue for me to think about a change to another xmpp server like ejabberd. Is ejabberd working better with OMEMO MUCs?
Is it possible to refetch messages in ejabberd with the same scenario?
Do you know if there is a issue open for prosody? Is the problem in the mam_muc module?
But isn´t it possible for conversations to fetch the missing messages if both the original sender and the recipient (one of the muc members which was previously offline) are back online some time later?

**Comment by thededem** [comment] 2016-12-21 21:49
@iNPUTmice do you know why this is not an issue with the gajim omemo implementation? After reading your explanation I reproduced the bug using conversations. With gajim, however, I was able to receive encrypted messages, even if the sender (using conversations (1.15.0 from playstore)) was offline at the time.
Server specs are similar to those of Killerjoe.

**Comment by devurandom** [comment] 2018-02-09 07:06
Did someone report this bug against Prosody? Maybe they can do something about it.

**Comment by iNPUTmice** [comment] 2018-04-02 06:50
Crude hack for reliability problems. Closing here.

**Closed by iNPUTmice** 2018-04-02 06:50 UTC

**Comment by devurandom** [comment] 2018-04-02 08:24
@iNPUTmice Could you please point us to the bug report against Prosody, so we can contribute in fixing this issue properly?

**Comment by iNPUTmice** [comment] 2018-04-02 08:28
@devurandom i believe this has been fixed in prosody.
