### ISSUE TITLE
Swipe Conversations from recent apps kicks me from conferences

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1975] opened 2016-07-30 21:18 UTC
#### General information

* **Version:** 1.13.7
* **Device:** Samsung Galaxy S3
* **Android Version:** Android 6.0 Cyanogenmod
* **Server name:** self hosted
* **Server software:** prosody trunk
* **Installed server modules:** all needed for Conversations
* **Conversations source:** PlayStore, PlayStore Beta Channel

#### Steps to reproduce

1. start Conversations and join some MUCs
2. close Conversations and swipe it away from recent apps
3. this kicks me from all conferences, but I'm still online

#### Expected result

I shound stay in the conferences during a recents app purge. I've the foreground service enabled, but did not resolve the issue.

#### Debug output

````
07-30 23:07:41.535 eu.siacs.conversations D/Conversations: app switched into background
````
Here I swiped Conversations from recent apps
````
07-30 23:07:47.165 eu.siacs.conversations D/Conversations: user@domain.de: leaving muc chat1@conference.domain.de/user
07-30 23:07:47.165 eu.siacs.conversations D/Conversations: user@domain.de: leaving muc rqb0iu6t8pf8l6u@conference.domain.de/user
07-30 23:07:47.170 eu.siacs.conversations D/Conversations: user@domain.de: leaving muc chat2@conference.domain.de/user
07-30 23:07:47.170 eu.siacs.conversations D/Conversations: user@domain.de: leaving muc chat3@conference.domain.de/user
07-30 23:07:47.170 eu.siacs.conversations D/Conversations: user@domain.de: leaving muc chat4@conference.domain.de/user
07-30 23:07:47.170 eu.siacs.conversations D/Conversations: user@domain.de: leaving muc chat5@conference.domain.de/user
07-30 23:07:47.170 eu.siacs.conversations D/Conversations: user@domain.de: leaving muc chat6@conference.domain.de/user
07-30 23:07:47.175 eu.siacs.conversations D/Conversations: user@domain.de: disconnecting force=false
07-30 23:07:47.175 eu.siacs.conversations D/Conversations: user@domain.de: waiting for tag writer to finish
07-30 23:07:47.180 eu.siacs.conversations D/Conversations: interrupted
````

**Comment by iNPUTmice** [comment] 2016-07-31 06:54
This is expected behavior. Duplicate of #1803 (and maybe others)

**Closed by iNPUTmice** 2016-07-31 06:54 UTC

**Comment by licaon-kter** [comment] 2016-07-31 07:23
It's not #1803 directly since the user here has foreground service enabled.

**Comment by kriztan** [comment] 2016-07-31 07:44
If leaving all conferences would be the expected behaviour, please tell me why there is a foreground service available? Shouldn't exactly this service prevent closing connections?

**Comment by kriztan** [comment] 2016-07-31 08:01
@licaon-kter right, I've battery options disabled and tested it with an other device running lollipop stock. It behaves exactly same. I've not played around with background app settings.
