### ISSUE TITLE
Need the ability to block messages from unauthorized contacts

### ISSUE THREAD

**Issue by eugeneseppel** [siacs/Conversations#2494] opened 2017-05-24 11:49 UTC
Currently I experience a lot of spam messages regarding espionage offers on the server. It's impossible to disallow messages from unknown unauthorized persons. Also it's impossible to block messages with certain phrases. Thus I had to stop using this application
#### General information

* **Version:** recent
* **Device:** Samsung
* **Android Version:** 4
* **Server name:** jabber.ru
* **Conversations source:** F-Droid

**Comment by licaon-kter** [comment] 2017-05-24 12:11
/close as duplicate of #2345 

In the mean time disable "notifications from strangers"

**Closed** 2017-05-24 12:28 UTC
