### ISSUE TITLE
"Trrustworts" instead of hex-fingerprints

### ISSUE THREAD

**Issue by htgoebel** [siacs/Conversations#1999] opened 2016-08-23 09:32 UTC
pEp (pretty Easy privacy) introduces a concept of "trustwords" to overcome the fingerprints, which are hard to read and verify. The idea is as simple as effective: Each set of 4-hex-digit numbers corresponds to a word and instead displaying hex-digits a few words are displayed (see screenshots). The UI could have an option (e.g. a tab) to switch to hex-digits to be exchanged with other programs. And of course, this could be used for all types of fingerprints.

![screenshot_2016-08-23-09-48-21](https://cloud.githubusercontent.com/assets/784161/17886564/b08fae98-6922-11e6-8bce-613e02ce33d8.png)

https://cacert.pep.foundation/trac/browser/db contains word lists for ca, de, es, en, fr and tr. These lists are already cleaned from swearwords.

For more information see https://cacert.pep.foundation/trac/wiki/Trustwords (which may be a bit outdated) and get in contact with pEp.

**Comment by iNPUTmice** [comment] 2016-08-27 09:45
duplicate of #1390

**Closed by iNPUTmice** 2016-08-27 09:45 UTC
