### ISSUE TITLE
WISH: auto-reconnect on failed connections

### ISSUE THREAD

**Issue by andreas-h** [siacs/Conversations#1633] opened 2016-01-04 08:41 UTC
I have one account where the server is somewhat unstable, leading to frequent disconnects. Currently, I then always get a notification prompting me to reconnect or disable the account. This is quite annoying.

It would be great if each account had a boolean setting "auto-reconnect on server failure" to prevent these notifications from appearing.

**Comment by iNPUTmice** [comment] 2016-01-04 13:49
Conversations in fact keeps trying to connect. Just after the second unsuccessful attempt that information is shown. If the users ignores that notification the error can disappear on its own. Also duplicate of #1589

**Closed by iNPUTmice** 2016-01-04 13:49 UTC
