### ISSUE TITLE
[Feature request] Support for MUC Subscription and XEP-0369: Mediated Information eXchange (MIX)

### ISSUE THREAD

**Issue by MurzNN** [siacs/Conversations#2037] opened 2016-09-24 06:28 UTC
Ejabberd introduced greate imrove of group chats: https://blog.process-one.net/xmpp-mobile-groupchat-introducing-muc-subscription/ - XEP-0369: Mediated Information eXchange (MIX) that solve problem with group chats on unstable connections.  

Woll be good to see support of this feature in your app.

**Comment by lovetox** [comment] 2016-09-25 07:32
you are confusing something,

ejabbered has a own developed improvement for MUC, but it is not XEP-0369.

and thats probably what conversations is waiting for, for implementation of XEP-0369

**Comment by dequis** [comment] 2016-12-30 19:31
Duplicate of #1951 (closed) for ejabberd's muc sub, #1764 (reopened after this one was created) for MIX

**Closed** 2016-12-30 19:43 UTC
