### ISSUE TITLE
Add contacts with Conversations installed from their phone number like Kontalk or whatsapp

### ISSUE THREAD

**Issue by logos88** [siacs/Conversations#940] opened 2015-01-27 10:00 UTC
I suposse is complicated to do, if possible. But the only way I could convince my friends to use xmpp would be if they could install the app and instantly speak with others without any registration. I'd love Conversations to do that with others who have installed the Conversations app or kontalk (making it compatible with this app too).

I really think xmpp needs a specification to use mobile phone numbers as identification if doesn't have any. It's the only way the way we comunicate nowadays (whatsapp, telegram, etc) could really change.

**Comment by jkufner** [comment] 2015-01-27 10:15
I'm affraid this is not how XMPP works. XMPP needs a server. That's why
there is a domain part in JID. So XMPP alone cannot do that.

But I like the idea behind.

There is XEP-0174 (Serverless Messaging) [1], however, it requires some
DNS magic to make peer-to-peer connections and I'm pretty sure it will
have many drawbacks.

The real problem is in providers. If every e-mail provider provided XMPP
account with same address, life would be much simpler.

Registration itself should not be a problem. For example Skype requires
it and it is widely used. But Jabber requires a server to choose. That
is difficult task for ordinary mortals.

[1]: http://xmpp.org/extensions/xep-0174.html

**Comment by iNPUTmice** [comment] 2015-01-27 10:16
duplicate of #906

**Closed by iNPUTmice** 2015-01-27 10:16 UTC

**Comment by iNPUTmice** [comment] 2018-11-15 10:59
I have now introduced [Quicksy](https://quicksy.im) which is my attempt at providing phone number lookup for in the Jabber world.
Here are are [the slides](https://github.com/iNPUTmice/talks/blob/master/2018_11_14_-_the_making_of_a_new_feature.md) for me introducing this new spin of. And here are [recordings of the German talk](https://media.ccc.de/v/dg-94) I gave.
