### ISSUE TITLE
Feature request: dark theme, optional day/night mode?

### ISSUE THREAD

**Issue by rejhgadellaa** [siacs/Conversations#1573] opened 2015-11-18 09:57 UTC
Would be nice for amoled screen users to have a dark theme. Maybe also include an option to automatically switch for day/night (easier on the eyes).

I'd be happy to have a go at building the theme (layouts with modified colors) if the devs are willing to incorporate it?

/Sorry if this is a duplicate, mobile github site doesn't support search?

**Comment by andersruneson** [comment] 2015-11-18 09:58
It's a duplicate yes.

**Comment by iNPUTmice** [comment] 2015-11-26 05:28
duplicate of #529

**Closed by iNPUTmice** 2015-11-26 05:28 UTC
