### ISSUE TITLE
Can not find HTTP_Upload service

### ISSUE THREAD

**Issue by ChristianPauly** [siacs/Conversations#2822] opened 2018-02-21 09:49 UTC
#### General information

* **Version:** eg 1.23.6
* **Device:** eg Google Nexus 5
* **Android Version:** LineageOS 14
* **Server name:** self hosted
* **Server software:** Ejabberd 16.09-4 armhf (Raspberry Pi with Raspbian (Debian Stretch))
* **Installed server modules:** HTTP_UPLOAD, MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Go to Account settings
2. Select "Server-Info"
3. Since a few weeks the HTTP File Upload is not found anymore. I can not upload any files. It does work in older versions for example Kandru Messenger. The domain of the upload service is just: upload.mydomain.de
I have done all upgrades from the f-Droid-Store instantly. Http upload worked for over two years without problems.

**Comment by licaon-kter** [comment] 2018-02-21 09:55
Update server version.

**Comment by kriztan** [comment] 2018-02-21 09:56
duplicate of duplicate of #2807 #2792 #2788 an #2818

**Comment by licaon-kter** [comment] 2018-02-21 09:57
And #2796

**Closed** 2018-02-21 22:46 UTC
