### ISSUE TITLE
Design: Simple conference creating UI

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#1701] opened 2016-02-16 14:37 UTC
Right now, to create a conference I can either invite a user to an existing 1:1 or go to the join dialog an enter a whole JID for a conference that does not exist yet.

Sometimes I want to start a group up to discuss something, but I'm not already 1:1 with anyone, so I really want to pick a short name, some users to invite, and go.

The current flow requires the user to know technical details about conferences (when you join one that doesn't exist, it gets created) and just not that user friendly.

Would other people use such a feature? Where would the button go? What flow would match your needs best?

**Comment by iNPUTmice** [comment] 2016-02-19 12:46
duplicate of #722

**Closed by iNPUTmice** 2016-02-19 12:46 UTC
