### ISSUE TITLE
HTTP Upload doesn't work on a server; works with Gajim

### ISSUE THREAD

**Issue by abbradar** [siacs/Conversations#2909] opened 2018-03-28 07:49 UTC
#### General information

* **Version:** 2.0.0
* **Device:** Xiaomi Mi5s
* **Android Version:** Android 8.1 LineageOS
* **Server name:** jabber.ru
* **Server software:** ejabberd 3.2.x
* **Installed server modules:** HTTP File Upload, etc.
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Try to upload a file using HTTP Upload

#### Expected result

File can be uploaded -- this works in Gajim.

#### Actual result

File is sent using Jingle.

#### Debug output

https://gist.github.com/abbradar/b1a6db59e1ae4a41024f906e6b8f0c58

**Comment by licaon-kter** [comment] 2018-03-28 07:56
Talk with admin to upgrade server software.

/Duplicate of many issues

**Comment by abbradar** [comment] 2018-03-28 07:56
I can register an account for debugging if needed (this is the most popular Russian server -- registration is open but there's a possible language issue).

**Comment by abbradar** [comment] 2018-03-28 07:57
@licaon-kter (posted simultaneously) I can try to create an issue with them; can you be more specific about what's needed on a server? Some new HTTP Upload namespace support?

**Comment by allo-** [comment] 2018-03-29 18:16
Maybe Conversations should display a notice about it? I was surprised on my own server, but when really big servers still have the problem it can affect a lot of users who do not understand the issue.

**Comment by licaon-kter** [comment] 2018-03-29 18:30
@abbradar Keep this open because users that don't search past issues would suddenly do what?

**Comment by abbradar** [comment] 2018-03-29 18:32
@licaon-kter I can speak at least for myself -- I've searched in opened issues but not closed ones because 1) several releases have passed since the problem appeared; 2) I didn't consider the problem is in server because Gajim worked. Also Github's default search adds `is:open` filter.

**Closed** 2018-06-05 07:04 UTC
