### ISSUE TITLE
Redesign 1-to-1 chat window to make it more screen-space efficient

### ISSUE THREAD

**Issue by av2k** [siacs/Conversations#3329] opened 2019-01-04 07:43 UTC
#### General information

* **Version:** 2.3.10
* **Conversations source:** latest HEAD

#### Steps to reproduce

1. Run a 1-to-1 conversation in Conversations.

#### Expected result

The chat screen should make maximum use of the available screen space to make reading and writing messages as appealing as possible.

#### Actual result

Considerable screen space is wasted by

- redundant display of the avatars of both users in each message
- the display of the username of each user in each message
- the timestamp of each message is displayed in a separate row above the message within the frame for each user's message

#### Possible solutions

- only show the avatar of the other and display it in the top bar of the conversation window next to the user's name
- don't display the username of the other user for each message
- display the timestamp of each message right next to it to prevent waste of vertical screen estate; the timestamp can then be shown in the same font size but still a different color than the text message, which would further increase the reading flow

**Comment by iNPUTmice** [comment] 2019-01-04 08:13
close as duplicate of #3330

**Closed by iNPUTmice** 2019-01-04 08:13 UTC
