### ISSUE TITLE
connection issues with Hangouts / Google Talk (SNI-related?)

### ISSUE THREAD

**Issue by jwise** [siacs/Conversations#3208] opened 2018-10-01 18:12 UTC
#### General information

* **Version:** 2.3.0+pcr (upd. Sep 27, 2018)
* **Device:** Google Pixel 2
* **Android Version:** Android 9 (PPR2.180905.005)
* **Server name:** Google Talk
* **Server software:** n/a
* **Installed server modules:** n/a
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

Recently, Conversations stopped being able to connect to Hangouts / Google Talk.  (I use Conversations to maintain a Talk instance other than the one that I am signed into on my phone.)  Pointing it directly at talk.google.com as the connect server, instead of gmail.com, works, but:

1. Set up a @gmail.com account with Hangouts / Talk.
2. Add it to Conversations.
3. Enable Advanced > Expert settings > Extended connection settings.
4. Set the hostname in 'Account details' to 'talk.google.com', port 5222.
5.  Press connect.

#### Expected result

Conversations, when it sees a @gmail.com, probably should just connect to a reasonable XMPP server automatically.  Note that:

```
joshua@bruges:~$ host -t SRV _xmpp-client._tcp.gmail.com
_xmpp-client._tcp.gmail.com has SRV record 20 0 5222 alt2.xmpp.l.google.com.
_xmpp-client._tcp.gmail.com has SRV record 20 0 5222 alt4.xmpp.l.google.com.
_xmpp-client._tcp.gmail.com has SRV record 20 0 5222 alt1.xmpp.l.google.com.
_xmpp-client._tcp.gmail.com has SRV record 5 0 5222 xmpp.l.google.com.
_xmpp-client._tcp.gmail.com has SRV record 20 0 5222 alt3.xmpp.l.google.com.
joshua@bruges:~$ host xmpp.l.google.com
xmpp.l.google.com has address 74.125.28.125
xmpp.l.google.com has IPv6 address 2607:f8b0:400e:c05::7d
joshua@bruges:~$ host talk.google.com
talk.google.com is an alias for talk.l.google.com.
talk.l.google.com has address 74.125.28.125
talk.l.google.com has IPv6 address 2607:f8b0:400e:c04::7d
```

However, when I hardcode talk.google.com, it should connect without warnings, also.

#### Actual result

Without hardcoding talk.google.com, I get 'TLS connection failed' (or an analogous message) in the connections window.  With hardcoding talk.google.com, I get the following popup:

![screenshot_20181001-110207](https://user-images.githubusercontent.com/87427/46306973-8c8c2480-c56a-11e8-97f6-e8a996514ac7.png)

Pressing 'once' allows Conversations to connect.

#### Debug output

I do not have a USB-C cable at work with me, but I can grab this later if needed.  Hopefully the above should be sufficient to repro.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment] 2018-10-01 18:13
Duplicate of #3203

**Closed by iNPUTmice** 2018-10-01 18:13 UTC

**Comment by jwise** [comment] 2018-10-01 18:14
D'oh -- I searched for 'SNI' but didn't find anything.  Sorry for the duplicate, and thank you for the fast response (and, thank you further for your hard work on maintainership)!
