### ISSUE TITLE
(re) force verification, challenge response

### ISSUE THREAD

**Issue by TameOfGroans** [siacs/Conversations#1053] opened 2015-03-22 04:34 UTC
both using 1.2.0-beta 

both clients identically configured, including: force end2end encryption,  do not save encrypted. 

conversations only initiated verification between Conversations and ChatSecure.

**Comment by iNPUTmice** [comment] 2015-03-22 18:44
please provide detailed steps to reproduce, result and expected result since I don't really know what you mean

**Comment by iNPUTmice** [comment] 2015-04-02 11:51
no reaction from op. closing

**Closed by iNPUTmice** 2015-04-02 11:51 UTC
