### ISSUE TITLE
[Feature] Android Smartwatch/Pebble Time support

### ISSUE THREAD

**Issue by Nekmo** [siacs/Conversations#1249] opened 2015-06-13 21:48 UTC
Other messaging applications have support for Android SmartWatch. For example Telegram. Thanks to this they can do many more things like reply messages.

Pebble supports Android SmartWatch. If Conversations implemented Android Watch, will also support Pebble.

**Comment by SamWhited** [comment] 2015-06-13 22:02
Conversations already supports Pebble. I have a mostly working branch for Android Wear support somewhere that I've abandoned if you wanted to pick it up.

**Comment by shtrom** [comment] 2015-07-06 07:46
The current Pebble support #649 is a pretty rough implementation doing the bare minimum and interacting directly with the Pebble API. There is probably a lot of value in using a more generic API. Not sure if the current Pebble App implements it, though.

**Comment by timosl** [comment] 2015-07-06 09:43
Is there any extra value in interacting with the Pebble API directly? By default, the Pebble shows the notifications from Conversation as expected and if Android Wear support was implemented, you could even reply to a message directly.

**Comment by shtrom** [comment] 2015-07-06 09:54
On Mon, Jul 06, 2015 at 02:43:20AM -0700, Timo Schlömer wrote:
> Is there any extra value in interacting with the Pebble API directly?
> By default, the Pebble shows the notifications from Conversation as
> expected and if Android Wear support was implemented, you could even
> reply to a message directly.

Maybe not anymore. It was useful with older versions of the app which
did not capture notification. This would require some testing.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by SamWhited** [comment] 2015-07-06 14:13
The [branch I mentioned](https://github.com/SamWhited/Conversations/tree/reply-from-wearable). Not tested with Pebble, and in serious need of a rebase.

**Comment by moneytoo** [comment] 2015-07-19 12:02
I only use Conversations to chat with single person but I checked receiving message from 2nd person to see it doesn't support [Stacking Notifications](https://developer.android.com/training/wearables/notifications/stacks.html) which I consider essential for proper Wear support. (I implemented it in one project so I may help with that if no one else is interested...)

My other issue is that the last received message from a person is appended to a message at the bottom which makes it hard reading several messages on Wear received during some period of time (without me dismissin notification or taking phone out and replying).

**Comment by baudtack** [comment] 2015-07-26 06:19
I have cherry-picked the commit in question, built it and tested it on a Pebble smart watch and it seems to be working perfectly. Will create a pull request.

**Comment by baudtack** [comment] 2015-09-15 17:56
Is there any chance this is going to get merged? Or is it going to wait until someone rebuilds it with stacking notifications?

**Comment by baudtack** [comment] 2015-09-15 18:00
I'm going to update my local repo, build a new apk with this functionality to test that it still works and create a new pull request.

**Comment by iNPUTmice** [comment] 2015-09-15 20:19
>  Or is it going to wait until someone rebuilds it with stacking notifications?

I would prefer that. Yes.

I think this is an important feature for Android Smartwatches

> on a Pebble smart watch

We actually have native Pebble support. Is this not working out for you?

**Comment by baudtack** [comment] 2015-09-15 20:34
@iNPUTmice the native pebble support is kind of terrible. It bypasses the pebble app that lets you control notifications and just shoots off notifications even if you don't want them. It also lacks the key ability to reply to messages from the pebble. The only way to add that as far as I can tell is through the android wear api.

**Comment by iNPUTmice** [comment] 2015-09-15 20:38
@baudtack ok thanks. good to know. Will remove the native Pebble support then in the near future. (I think even the original contributor dislikes the feature)

**Comment by baudtack** [comment] 2015-09-15 20:39
I'll still produce a build with the old code, hopefully someone will be able to build on it and add the stacking notifications. I'd do it but I don't have a way of testing it. The described behavior is just how my pebble works by default if i understand what i'm looking at.

**Comment by shtrom** [comment] 2015-09-15 20:50
On Tue, Sep 15, 2015 at 01:38:13PM -0700, Daniel Gultsch wrote:
> @baudtack ok thanks. good to know. Will remove the native Pebble support then in the near future. (I think even the original contributor dislikes the feature)

Well, it's better than nothing, but it would be better replace by
proper stacking notifications (:

That said, until it's relpaced by something better, I'm quite happy for
it to stay there!

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by jwise** [comment] 2015-09-18 06:36
I'll note that the native Pebble support, even as rudimentary as it is, actually is way better than having no support at all.  I just switched to Pebble Time, and the native Pebble support no longer works, and I really miss it.  So until we end up with summary notifications or native Wear support (which would also support Pebble), my vote is as well with @shtrom's, which is to say that native Pebble support should be left in.

**Comment by baudtack** [comment] 2015-09-25 06:04
I've created a new branch with the existing wear notification. I've preliminary tested it. Seems to work. I can pass on an APK to anyone who would like it. https://github.com/baudtack/Conversations YMMV, I just merged in the existing code.

**Comment by jumper047** [comment] 2016-06-07 11:07
Are some good news here? By the way, can you share this apk? Also OG Pebble owner, and now it support Android wear actions.

**Comment by jumper047** [comment] 2016-07-16 20:06
I did it! (big deal for non coder:)). Latest conversations with merged baudtrack's patch. Not shure, that i dit it all right, but it works for me. 

[Conversations-1.13.6-free-debug.apk.zip](https://github.com/siacs/Conversations/files/367502/Conversations-1.13.6-free-debug.apk.zip)

**Comment by iNPUTmice** [comment] 2016-08-31 08:27
The current HEAD supports stacking notifications as well as a reply action. According to the docs this should work an Android Wear. Can somebody confirm this?

**Comment by jumper047** [comment] 2016-08-31 09:02
If you share apk, I'll test it right now:)

**Comment by danielegobbetti** [comment] 2016-09-06 07:24
@iNPUTmice I just upgraded to 0.14 from F-droid and the reply action is not visible for me. I don't have android N on my phone (I saw it mentioned in the commits).
The functionality should however be technically possible also on M.

**Comment by iNPUTmice** [comment] 2016-09-06 10:16
@danielegobbetti please try the latest HEAD.
I don't have a wear device so I can't replicate this

**Comment by danielegobbetti** [comment] 2016-09-06 12:07
@iNPUTmice works fine with pebble on current HEAD!

**Comment by danielegobbetti** [comment] 2016-09-06 17:24
Sorry but I have to correct my statement: the notifications work as intended, but in case of multiple notifications from the same user, only the first message in the stack gets pushed repeatedly for me.

**Comment by iNPUTmice** [comment] 2016-09-06 20:40
Hi,

sorry you are on your own then. I don't have a smartwatch (neither a pebble nor an android wear device). I followed the API and google design guidelines to the best of my knowledge. I'm unsure about what I can do differently. Pull requests welcome.

**Comment by danielegobbetti** [comment] 2016-09-07 07:27
From what I can tell the technical part works well (the notifications go through *and* they are actionable) so you can probably close this issue, unless you want to wait for an android wear user to confirm.
I'll further debug the repeating message on the receiving side to be sure it's not the other end that interprets the data in the wrong way, and provide a pull request if something has to be done on your side.

Thanks a lot!

**Comment by danielegobbetti** [comment] 2016-09-09 10:32
With the following patch I get the most recent message notified to the pebble (instead of the first one), while the on-screen notification contains the correct text.
If you prefer I can do a pull request, but the changes are minimal as you can see.
```
diff --git a/src/main/java/eu/siacs/conversations/services/NotificationService.java b/src/main/java/eu/siacs/conversations/services/NotificationService.java
index fe9215d..2b27a61 100644
--- a/src/main/java/eu/siacs/conversations/services/NotificationService.java
+++ b/src/main/java/eu/siacs/conversations/services/NotificationService.java
@@ -376,7 +376,7 @@ public class NotificationService {
 			builder.setStyle(messagingStyle);
 		} else {
 			builder.setStyle(new NotificationCompat.BigTextStyle().bigText(getMergedBodies(messages)));
-			builder.setContentText(UIHelper.getMessagePreview(mXmppConnectionService, messages.get(0)).first);
+			builder.setContentText(UIHelper.getMessagePreview(mXmppConnectionService, messages.get((messages.size()-1))).first);
 		}
 	}
 
@@ -425,7 +425,7 @@ public class NotificationService {
 				text.append("\n");
 			}
 		}
-		return text.toString();
+		return text;
 	}
 
 	private PendingIntent createShowLocationIntent(final Message message) {
```

**Comment by iNPUTmice** [comment] 2016-09-16 17:00
The merged PR from @danielegobbetti seems to resolve this issue.

**Closed by iNPUTmice** 2016-09-16 17:00 UTC
