### ISSUE TITLE
Notification for arriving message is not played

### ISSUE THREAD

**Issue by karlkarpfen** [siacs/Conversations#765] opened 2014-12-09 06:35 UTC
The notification for an arriving message is sometimes not played.

To say that clear: I DO UNDERSTAND IT IS NOT PLAYED WHEN APP IS IN FOREGROUND.

But it happens too when it is in background, either because the home-button was pressed or because the display was turned off (in both cases onPause() is executed for the App so that from technical point of view it is in background).

So please do not close this bug again, there definitely is a problem. The strange thing: it happens only sometimes but for about 40% of the time it does not work as expected and specified.

**Comment by knoy** [comment] 2015-01-01 14:02
This looks identical to #758 for me

**Comment by knoy** [comment] 2015-01-03 22:10
What seems to happen is that the phone vibrates extremely briefly when the message is received but there is no notification or sound played

**Comment by iNPUTmice** [comment] 2015-01-03 22:42
duplicate of #758.
Please use #758 if this issue remains in 0.10 which has just been tagged.

**Closed by iNPUTmice** 2015-01-03 22:42 UTC
