### ISSUE TITLE
Feature request: Support for inline images with data: uri scheme

### ISSUE THREAD

**Issue by roobre** [siacs/Conversations#2757] opened 2018-01-13 00:05 UTC
Just like gajim does: https://dev.gajim.org/gajim/gajim-plugins/wikis/ImagePlugin ([XEP](https://xmpp.org/extensions/xep-0071.html))

Could be a nice start for an sticker-like system and reaction pics in general.

I can try and write a PR if you like the idea.

**Comment by licaon-kter** [comment] 2018-01-13 00:33
Duplicate of https://github.com/siacs/Conversations/issues/2114 ?

**Comment by roobre** [comment] 2018-01-13 01:00
Probably yes, but things have changed a bit since then, maybe we could discuss about it again?

Rich-texts messages are now a thing on Whatsapp and other commong messaging applications. In fact, Conversations does support markdown-like syntax for `*bold*` and `_italics_`, so implementing this would make this feature more accesible for other XMPP clients. What do you think about it?

**Comment by licaon-kter** [comment] 2018-01-13 01:04
I don't really care, but you know, _to each his own_.

Regarding stickers there's https://github.com/siacs/Conversations/issues/2122

**Comment by roobre** [comment] 2018-01-13 01:25
I see [XEP-231](http://xmpp.org/extensions/xep-0231.html) mentioned, but it seems to be a more recent standard with little support from clients.

This would be less efficient, but more cross-compatible. Anyway I think that's just a possibility, enabling rich text messages is pretty interesting by itself. Integrating with markdown also looks like a promising idea to me.

**Comment by iNPUTmice** [comment] 2018-01-17 08:30
If needed we might implement BOB at some point. But I don't see the upside of data uris over BOB.

**Closed by iNPUTmice** 2018-01-17 08:30 UTC
