### ISSUE TITLE
Photo are sometimes too big?

### ISSUE THREAD

**Issue by clayt0nk** [siacs/Conversations#2515] opened 2017-06-19 05:31 UTC
New conversations / XMPP user here, with what I think is probably a wish-list bug.

Sharing a 221K photo from the Nexus 5 works, sharing a 476K photo from the Nexus 6p fails repeatedly, using the same account and sending through the same server (darknet.nz). I am guessing what is going on here is I am hitting a file upload size limit on the server. However on the Conversations end I am seeing no configurability of the processing (shrinking?) done on a photo before upload. I think what is needed is at least the ability to set an upper limit to file size. This is also probably a very desirable feature for places where bandwidth or connectivity are issues. Logcat

06-19 13:24:20.472 D/conversations( 8108): send file message
06-19 13:24:20.913 D/conversations( 8108): uploading to https://darknet.nz:5443/upload/d26f47acd6b24a7babcfe1660f995fa54f56e068/8H6VKpwsT1iIAfZ6UinyAQjpelJHfC5x1Nx176SZ/UYlK5vmoS3qPXaWSef6k_A.jpg
06-19 13:24:38.937 D/conversations( 8108): http upload failed timeout

does not say much except it timed out.

#### General information
* **Version:**
1.18.5

* **Device:**
Nexus 5 running CyanogenMod 11
Nexus 6p running CopperHead Android 7.1.2

* **Server name:**
darknet.nz

* **Installed server modules:**
see https://gultsch.de/compliance_ranked.html

* **Conversations source:**
FDroid

**Comment by iNPUTmice** [comment] 2017-06-19 06:44
duplicate of #2318

**Closed by iNPUTmice** 2017-06-19 06:44 UTC
