### ISSUE TITLE
Requirement: How to get/ retreive list of all conference rooms created on server?

### ISSUE THREAD

**Issue by VedantaBabaria** [siacs/Conversations#1198] opened 2015-05-14 17:14 UTC
In conversations, when I swipe to conferences fragment on the main activity, and then click on an icon of add/join conference; A pop-up appears. Which asks to enter room name/ conference name manually on edit text.

Instead of the above given scenario, I was trying to develop a feature on same  activity where I can show all the hosted room's name in a spinner instead of asking user for input. For that I need to retrieve list of all the hosted rooms from the server. 

#Any_help_will_be_appreciated!

**Comment by andersruneson** [comment] 2015-05-14 17:50
I think this is a duplicate of
#279

**Comment by iNPUTmice** [comment] 2015-05-15 04:39
In fact duplicate

**Closed by iNPUTmice** 2015-05-15 04:39 UTC
