### ISSUE TITLE
Contact online/offline indicator everywhere

### ISSUE THREAD

**Issue by naught101** [siacs/Conversations#1277] opened 2015-07-08 00:42 UTC
It would be really nice to have a online/offline/away/etc indicator on any screen that includes a contact. For example, on the contact list, it would be good to have a coloured circle next to, or in the corner of the contact icons. In the chat screen, it would be good to have a similar indicator at the top of the page (in the header) or perhaps also on the icons - this would probably work better with multi-party chat.

At the moment, in 1.4.7, I don't seem to have any way to view the availability of contacts at all...

**Comment by naught101** [comment] 2015-07-08 01:21
Hrm.. it looks like maybe the colour of the send button is the indicator? It's a bit non-intuitive, and it doesn't match any other programs I've ever seen.  An indicator in the header would be a bit more obvious.

Indicators in the contacts list would still be really useful.

**Comment by SamWhited** [comment] 2015-07-08 04:30
Duplicate of #1254, #236, #61, #477, and #451 among others.

Also covered in [the FAQ](https://github.com/siacs/Conversations#where-can-i-see-the-status-of-my-contacts-how-can-i-set-a-status-or-priority).

**Comment by andersruneson** [comment] 2015-07-08 04:57
Settings - show dynamic tags, then you'll get a tag with the contact status.

**Comment by naught101** [comment] 2015-07-08 14:10
I already have that option on, and I've tried turning it off and on again, and it does nothing, as far as I can see... on the contact list, I just have the Icon, the name,  the last message, and the date of the last message. In the chat view, I just have the contact name in the header, and the Icon, messages, and dates in the view... what should I be seeing exactly?

ned

On 7 July 2015 9:57:32 pm MST, Anders Sandblad <notifications@github.com> wrote:
>Settings - show dynamic tags, then you'll get a tag with the contact
>status.
>On 8 Jul 2015 6:30 am, "Sam Whited" <notifications@github.com> wrote:
>
>> Duplicate of #1254
><https://github.com/siacs/Conversations/issues/1254>,
>> #236 <https://github.com/siacs/Conversations/issues/236>, #61
>> <https://github.com/siacs/Conversations/issues/61>, #477
>> <https://github.com/siacs/Conversations/issues/477>, and #451
>> <https://github.com/siacs/Conversations/issues/451> among others.
>>
>> Also covered in the FAQ
>>
><https://github.com/siacs/Conversations#where-can-i-see-the-status-of-my-contacts-how-can-i-set-a-status-or-priority>
>> .
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/siacs/Conversations/issues/1277#issuecomment-119426556>
>> .
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/1277#issuecomment-119433648

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andersruneson** [comment] 2015-07-08 14:30
Maybe we are talking about different views "contact list"? My contact list
is shown when I press +. The normal view is the conversation list with
recent conversations.

**Comment by naught101** [comment] 2015-07-08 14:45
Yeah, sorry, I was talking about the conversations list. This is more important to me, because this is where my most important contacts are.

However, in the contact list I only have the Icon, the nickname, the username, and a tag that says which group the contact is in (e.g. groups that I created in pidgin, or 'Facebook friends'). Nothing indicating whether a contact is online or not.



On 8 July 2015 7:30:17 am MST, Anders Sandblad <notifications@github.com> wrote:
>Maybe we are talking about different views "contact list"? My contact
>list
>is shown when I press +. The normal view is the conversation list with
>recent conversations.
>On 8 Jul 2015 4:10 pm, "naught101" <notifications@github.com> wrote:
>
>> I already have that option on, and I've tried turning it off and on
>again,
>> and it does nothing, as far as I can see... on the contact list, I
>just
>> have the Icon, the name, the last message, and the date of the last
>> message. In the chat view, I just have the contact name in the
>header, and
>> the Icon, messages, and dates in the view... what should I be seeing
>> exactly?
>>
>> ned
>>
>> On 7 July 2015 9:57:32 pm MST, Anders Sandblad
><notifications@github.com>
>> wrote:
>> >Settings - show dynamic tags, then you'll get a tag with the contact
>> >status.
>> >On 8 Jul 2015 6:30 am, "Sam Whited" <notifications@github.com>
>wrote:
>> >
>> >> Duplicate of #1254
>> ><https://github.com/siacs/Conversations/issues/1254>,
>> >> #236 <https://github.com/siacs/Conversations/issues/236>, #61
>> >> <https://github.com/siacs/Conversations/issues/61>, #477
>> >> <https://github.com/siacs/Conversations/issues/477>, and #451
>> >> <https://github.com/siacs/Conversations/issues/451> among others.
>> >>
>> >> Also covered in the FAQ
>> >>
>> ><
>>
>https://github.com/siacs/Conversations#where-can-i-see-the-status-of-my-contacts-how-can-i-set-a-status-or-priority
>> >
>> >> .
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub
>> >>
>> ><
>>
>https://github.com/siacs/Conversations/issues/1277#issuecomment-119426556>
>> >> .
>> >>
>> >
>> >
>> >---
>> >Reply to this email directly or view it on GitHub:
>>
>>https://github.com/siacs/Conversations/issues/1277#issuecomment-119433648
>>
>> --
>> Sent from my Android device with K-9 Mail. Please excuse my brevity.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/siacs/Conversations/issues/1277#issuecomment-119592329>
>> .
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/1277#issuecomment-119598537

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andersruneson** [comment] 2015-07-08 14:54
Please join the conversations muc to discuss further.
https://github.com/siacs/Conversations/blob/development/README.md#conversations-doesnt-work-for-me-where-can-i-get-help
Yeah, sorry, I was talking about the conversations list. This is more
important to me, because this is where my most important contacts are.

However, in the contact list I only have the Icon, the nickname, the
username, and a tag that says which group the contact is in (e.g. groups
that I created in pidgin, or 'Facebook friends'). Nothing indicating
whether a contact is online or not.



On 8 July 2015 7:30:17 am MST, Anders Sandblad <notifications@github.com>
wrote:
>Maybe we are talking about different views "contact list"? My contact
>list
>is shown when I press +. The normal view is the conversation list with
>recent conversations.
>On 8 Jul 2015 4:10 pm, "naught101" <notifications@github.com> wrote:
>
>> I already have that option on, and I've tried turning it off and on
>again,
>> and it does nothing, as far as I can see... on the contact list, I
>just
>> have the Icon, the name, the last message, and the date of the last
>> message. In the chat view, I just have the contact name in the
>header, and
>> the Icon, messages, and dates in the view... what should I be seeing
>> exactly?
>>
>> ned
>>
>> On 7 July 2015 9:57:32 pm MST, Anders Sandblad
><notifications@github.com>
>> wrote:
>> >Settings - show dynamic tags, then you'll get a tag with the contact
>> >status.
>> >On 8 Jul 2015 6:30 am, "Sam Whited" <notifications@github.com>
>wrote:
>> >
>> >> Duplicate of #1254
>> ><https://github.com/siacs/Conversations/issues/1254>,
>> >> #236 <https://github.com/siacs/Conversations/issues/236>, #61
>> >> <https://github.com/siacs/Conversations/issues/61>, #477
>> >> <https://github.com/siacs/Conversations/issues/477>, and #451
>> >> <https://github.com/siacs/Conversations/issues/451> among others.
>> >>
>> >> Also covered in the FAQ
>> >>
>> ><
>>
>
https://github.com/siacs/Conversations#where-can-i-see-the-status-of-my-contacts-how-can-i-set-a-status-or-priority
>> >
>> >> .
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub
>> >>
>> ><
>>
>https://github.com/siacs/Conversations/issues/1277#issuecomment-119426556>
>> >> .
>> >>
>> >
>> >
>> >---
>> >Reply to this email directly or view it on GitHub:
>>
>>https://github.com/siacs/Conversations/issues/1277#issuecomment-119433648
>>
>> --
>> Sent from my Android device with K-9 Mail. Please excuse my brevity.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/siacs/Conversations/issues/1277#issuecomment-119592329>
>> .
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/1277#issuecomment-119598537

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

—
Reply to this email directly or view it on GitHub
<https://github.com/siacs/Conversations/issues/1277#issuecomment-119608200>.

**Closed** 2015-07-09 12:22 UTC

**Comment by naught101** [comment] 2015-07-16 17:09
For what it's worth, I still don't think that the colour of the send button is enough of an indicator, so I don't think this is fixed. Sorry for not joining the chat, but I'm working and travelling at the moment, and it's difficult to find time.
