### ISSUE TITLE
Share to Conversations.

### ISSUE THREAD

**Issue by Bretos** [siacs/Conversations#1515] opened 2015-10-22 22:40 UTC
In a case that I use Android share option, and choose to share a file to Conversations (eg. from gallery), it uses xmpp in-band file transfer instead of httpupload, even if it's available. Shouldn't Conversations first try to share the file through httpupload, and if fail/not available fall back to "old" xmpp file transfer?

**Comment by SafwatHalaby** [comment] 2015-10-23 05:59
I can't reproduce this.

**Comment by Bretos** [comment] 2015-10-23 07:54
Forgot to mention few details:

the phone is LG Spirit 4G LTE with stock firmware, running Android Lolipop (with included LG crapware, not-rooted)

**Comment by moshpirit** [comment] 2015-10-27 11:04
Why should it try first HTTP upload instead of Jingle?

**Comment by d9h02f** [comment] 2015-10-27 15:55
(in every single possible case, HTTP upload works better)

**Comment by moshpirit** [comment] 2015-10-27 16:27
Oh, OK thanks!

**Comment by singpolyma** [comment] 2015-11-12 22:08
@d9h02f in *every possible case*? citation needed :P

**Comment by iNPUTmice** [comment] 2015-12-11 14:36
fixed with 5e151c7311bed98ce7eafa041735484c32bd7dda

**Closed by iNPUTmice** 2015-12-11 14:36 UTC
