### ISSUE TITLE
Feature Request: Add a Unread Messages Marker

### ISSUE THREAD

**Issue by ro0kie4** [siacs/Conversations#1719] opened 2016-02-24 12:43 UTC
From time to time I have a problem finding the last message I have read. So I thought about adding a Unread Messages Marker for example like the one from Telegram:

![screenshot](https://cloud.githubusercontent.com/assets/9086371/13285719/78a83d7e-dafc-11e5-868b-f74db0bd832d.png)

**Comment by kriztan** [comment] 2016-02-24 12:50
duplicate of #291

**Closed** 2016-02-24 12:54 UTC
