### ISSUE TITLE
Client signature - Send files to Conversations only

### ISSUE THREAD

**Issue by CarlVanHouten** [siacs/Conversations#270] opened 2014-07-12 17:00 UTC
Scenery :
1x JID
2x Clients = 1x Jitsi, 1x Conversations

When sending a file to one JID, if Conversations would have a client signature, another Conversations client could send the file automatically to Conversations. 

This would fit to the minimalistic and clean UI, instead of asking to which JID to send.

Often the other users are sending to the wrong JID or just trying or asking me or they just give up. 

If there's no Conversations client, it could tell the user "Sorry, there's no compatible client for file transfer." instead of sending, but it never reaches the other client. 
There are only two handful xmpp clients, that are used often, so the signature list would be easy to update. 

Xabber and jTalk / jTalkMod are sending their signature. I think Jitsi, too. 

I don't think that the file transfer problem, with other clients, will be solved soon.

**Comment by SamWhited** [comment] 2015-01-23 03:32
The answer here is not to send to Conversations only, but to do service discovery and check if any of the other resources advertise Jingle file transfer (and only show those in the list).

**Comment by iNPUTmice** [comment] 2015-04-11 12:50
duplicate of #1033

**Closed by iNPUTmice** 2015-04-11 12:50 UTC
