### ISSUE TITLE
Require OTR option?

### ISSUE THREAD

**Issue by tYGjQCsvVI** [siacs/Conversations#1422] opened 2015-09-20 20:21 UTC
There use to be a "default to off-the-record" option in the expert settings menu that would default to OTR for new conversations, however this feature seems to be missing as-of a recent update (F-Droid).

Can I ask why it was removed? It was very useful for someone like me who only speaks to people with OTR-enabled clients and only ever wishes to use OTR.

**Comment by iNPUTmice** [comment] 2015-09-21 15:32
duplicate of #1345

**Closed by iNPUTmice** 2015-09-21 15:32 UTC
