### ISSUE TITLE
Black AMOLED theme (real black!)

### ISSUE THREAD

**Issue by rugk** [siacs/Conversations#2111] opened 2016-11-09 19:06 UTC
I know a black theme is available, but it is still not suitable for AMOLED devices, because the background is usually just dark grey.

However on AMOLED devices it is most suitable when the background is black, real #00000 black. The "advanced settings" dialog serves a as good example (in case you're responsible for this) as it is really black.

As a dark theme is implemented, you may just need to add one with the same colors except of a black background color.
An example for how this can look can be seen in [LeafPic](https://github.com/HoraApps/LeafPic/).

**Comment by licaon-kter** [comment] 2016-11-09 20:06
/duplicate of [so many issues](https://github.com/siacs/Conversations/issues?q=is%3Aissue+theme+is%3Aclosed), do close

**Comment by rugk** [comment] 2016-11-09 20:22
Please read it again. I have not found anyone, who actually talks about the #00000 thing, which is a thing I find quite important for AMOLED screens.

To make it more clear I am just adjusting the title.

**Comment by SamWhited** [comment] 2016-11-09 20:25
> Please read it again. I have not found anyone, who actually talks about the #00000 thing

From #1993, first result on that search page that was linked:

> I'd like a third theme to be available in settings. The background should be 100% black.

**Comment by rugk** [comment] 2016-11-09 20:29
Okay https://github.com/siacs/Conversations/issues/1993 is old. Let'S look at more recent comments I just found:
* https://github.com/siacs/Conversations/issues/529#issuecomment-230359993 (5 Jul)
* https://github.com/siacs/Conversations/issues/529#issuecomment-255598449 (17 days ago)

So either reopen https://github.com/siacs/Conversations/issues/529 or let this issue open. There seem to be people, who are requesting this feature.

**Comment by licaon-kter** [comment] 2016-11-09 20:40
Or read https://github.com/siacs/Conversations/issues/1993#issuecomment-241098432 and close this?

**Comment by rugk** [comment] 2016-11-09 21:39
Maybe you can be convinced. :smile: 

Also [LeafPic](https://github.com/HoraApps/LeafPic/) is a great FLOSS app and they use material designs. Their AMOLED dark theme looks great and so could it look in Conversations.
Additionally it is of course only an option for the user. By default users might still see the "pure material design". :wink:

**Closed** 2016-11-10 01:16 UTC

**Comment by Sonickyle27** [comment] 2019-05-24 15:36
This is something that can please be reconsidered for the future? Google have been adding black themes to their apps lately, and other messaging apps like Revolution IRC and Riot also come with a black theme.
