### ISSUE TITLE
Handling of new additional devices with OMEMO encryption

### ISSUE THREAD

**Issue by slizzered** [siacs/Conversations#2117] opened 2016-11-13 14:09 UTC
The issue is about acceptance of new OMEMO keys after a user adds additional devices.

In our case, one member of a MUC added a new device. We all had to blindly accept the new key, since there is no real built-in way to do that (see #2097, #1632). What is the expected workflow to handle such a scenario? As keys can not easily be verified, why not accept them automatically (trust on first contact)? I know the about implications security-wise, but for the majority of users this might be a better default. Through an option, advanced or more paranoid users could keep the old behavior.

In a large-ish MUC where users regularly add new devides, this key verification process becomes a problem. Especially with inexperienced users that are reluctant to accept new keys or do not know how to verify keys reliably.

**Comment by iNPUTmice** [comment] 2016-11-13 18:32
Yes verification of fingerprints can be made more easy. There are also considerations of introducing a 'verified' state on top of the trusted/untrusted. However blindly trusting all keys makes no sense whatsoever. Also this issue (which reads more like a general rant instead of a feature suggestion or a bug report) is either invalid or duplicate of the issues you linked yourself.

**Closed by iNPUTmice** 2016-11-13 18:32 UTC
