### ISSUE TITLE
Automatically Resend Failed Messages

### ISSUE THREAD

**Issue by chrisvella** [siacs/Conversations#970] opened 2015-02-06 06:28 UTC
Could you please introduce an option to auto-resend a failed message? Sometimes issues occur on the network, and messages silently fail. Adding a 30 second delay before a message is automatically resent would fix this problem.

Thank you for the fantastic client. The material design looks beautiful.

**Comment by knoy** [comment] 2015-02-06 07:05
This would definitely be a huge help in cases of network instability

**Comment by viric** [comment] 2015-02-06 10:28
Yes, we often fall into the situation where messages simply don't arrive, and we don't know why. Sending extra messages sometimes triggers the resend.

**Comment by JannisHeinen** [comment] 2015-02-06 17:24
I know this issue ... I often have to ask my partner if he got my message and he diddn't because
- driving car and no contact to a mobile-provider
- shut-off the smartphone when I send a meesage

**Comment by chrisvella** [comment] 2015-02-07 03:31
@JannisHeinen have you got "Request message receipts" enabled in the options under "Other"? I can tell that the message has been sent properly with that enabled for both clients. Really you should be able to see how far the other person has read.

**Comment by iNPUTmice** [comment] 2015-02-07 18:38
duplicate of #229

**Closed by iNPUTmice** 2015-02-07 18:38 UTC
