### ISSUE TITLE
Jump to the position of searched messages

### ISSUE THREAD

**Issue by BaumGuard** [siacs/Conversations#3242] opened 2018-10-18 18:57 UTC
When you search for words in messages and some messages are displayed, you can't go to the position in the conversation-protocol where the displayed message is.
Sometimes you don't know in which context the messages are, so it would be great, if you can jump to the position of the message when you click on it.

**Comment by iNPUTmice** [comment] 2018-10-18 19:09
duplicate of #3101

**Closed by iNPUTmice** 2018-10-18 19:09 UTC
