### ISSUE TITLE
Conversation ignores the resource-name

### ISSUE THREAD

**Issue by vasisualiy** [siacs/Conversations#1613] opened 2015-12-24 02:19 UTC
If I chat in Psi on my dfesktop, then conversation mirrors messages.

**Comment by SafwatHalaby** [comment] 2015-12-24 04:30
That's because Conversations uses [XEP-0280: Message Carbons](http://xmpp.org/extensions/xep-0280.html). This is a *feature*. If Psi had used it two, you'd get synced messages on both clients.

**Comment by vasisualiy** [comment] 2015-12-25 10:04
Is there a possibility to disable this feature? Its a bit annoing, especially if I chatting with an OTR, then the mirrored messages can not be decprypted and shown like a garbage.

**Comment by andersruneson** [comment] 2015-12-25 10:28
You should probably fix psi instead of doing work around in other software.

**Comment by vasisualiy** [comment] 2015-12-25 11:45
it's true. But it's not possible o implement all of the XEP cause of lack of human ressources. And the fact is, that AKAIK there are only  a few number of clients, that supports XEP-0280. mcabber is one of those. And the support of this in libpurple is far from clear, I think. 

More - the problem of OTR seems to be a hard one. And the problem of becoming encrypted messages, that can not be decrypted will exists a long time, I think. So it would be smart, to implement the option, to disable the carbon copies.

**Comment by strb** [comment] 2015-12-25 12:50
The problem here is that Psi doesn't seem to set the <private/> and/or <no-copy/> hints on OTR messages. These hints tell the server(s) involved in the communication not to copy these messages to other clients than the target resource. They are designed for exactly this kind of situation.

That should be a really easy fix for the Psi developers, you should report it with them. You can point them at [XEP-0334: Message Processing Hints, Section 4.3](http://xmpp.org/extensions/xep-0334.html#no-copy) and [XEP-0280: Message Carbons, Section 9](http://xmpp.org/extensions/xep-0280.html#avoiding) for further information.

I'm closing here, as this is not a bug with Conversations.

**Closed by strb** 2015-12-25 12:50 UTC
