### ISSUE TITLE
Picture transfer to Gajim 1.0.3 hangs at 0%

### ISSUE THREAD

**Issue by sledz** [siacs/Conversations#3445] opened 2019-04-28 08:21 UTC
#### General information

* **Version:** 2.4.3+fcr
* **Device:** Fairphone FP2
* **Android Version:** Android 7.1.2 Fairphone Open
* **Server name:** jabber.in-berlin.de
* **Server software:** ejabberd
* **Installed server modules:** ?
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Send picture to Gajim-user
2. Gajim-user gets a popup: "foo@bar want's to send you a file" and confirms with OK
3. Gajim-user gets a file selection dialog and chooses directory and filename and confirms with Save
4. Gajim-user get a file transfer process popup which hangs at 0%
5. Conversations user sees "Sending (0% done)"

#### Expected result

Picture is transfered.

#### Actual result

Freeze at 0%.

**Comment by licaon-kter** [comment] 2019-04-28 08:24
Logs from Gajim? From Conversations?

**Comment by iNPUTmice** [comment] 2019-04-28 08:41
Information about the receiving server would also be useful. + Please do provide Conversations logs (see README.md on how to debug Conversations)

I have a suspicion that this is due to Gajim not sending proxy-activated when using the proxy65 of the receiver because the sender doesn’t have one. I know that this bug existed some years ago; but it is super rare to run into this because it only occurs when the sending client does not have a proxy but the receiving one has.
At least this would explain the symptoms. But it could be something else obviously.

**Comment by sledz** [comment] 2019-04-28 13:16
Conversations log:

> 04-28 15:00:14.000 D/conversations( 5912): send file message
> 04-28 15:00:14.139 D/conversations( 5912): no primary candidate of our own was found
> 04-28 15:00:15.028 D/conversations( 5912): sledz@zone42.org: other party received offer
> 04-28 15:00:27.699 D/conversations( 5912): connection failed with 2001:bf0:c080:401::1:28011
> 04-28 15:00:27.827 D/conversations( 5912): received candidate error
> 04-28 15:00:42.719 D/conversations( 5912): connection failed with 172.16.100.130:28011
> 04-28 15:00:43.478 D/conversations( 5912): connection failed with 217.197.84.186:28011
> 04-28 15:00:43.478 D/conversations( 5912): could not find suitable candidate
> 04-28 15:00:43.478 D/conversations( 5912): sledz@zone42.org: sending fallback to ibb
> 04-28 15:00:44.025 D/conversations( 5912): connection failed with 2001:bf0:c080:401::1:28011
> 04-28 15:00:59.036 D/conversations( 5912): connection failed with 172.16.100.130:28011
> 04-28 15:01:00.133 D/conversations( 5912): connection failed with 217.197.84.186:28011
> 04-28 15:01:00.133 D/conversations( 5912): could not find suitable candidate
> 04-28 15:01:00.133 D/conversations( 5912): sledz@zone42.org: sending fallback to ibb
> 04-28 15:01:00.691 D/conversations( 5912): connection failed with 2001:bf0:c080:401::1:28011
> 04-28 15:01:15.707 D/conversations( 5912): connection failed with 172.16.100.130:28011
> 04-28 15:01:16.551 D/conversations( 5912): connection failed with 217.197.84.186:28011
> 04-28 15:01:16.551 D/conversations( 5912): could not find suitable candidate
> 04-28 15:01:16.551 D/conversations( 5912): sledz@zone42.org: sending fallback to ibb
> 04-28 15:01:17.061 D/conversations( 5912): connection failed with 2001:bf0:c080:401::1:28011

Gajim log:

> 
> 28.04.2019 15:00:15 (I) gajim.c.jingle_ft: transport value: <gajim.common.jingle_transport.JingleTransportSocks5 object at 0x7f182d297828>
> 28.04.2019 15:00:15 (I) gajim.c.jingle_ft: FT request: None
> 28.04.2019 15:00:15 (I) gajim.c.jingle_ft: ourjid: zone42@jabber.de/gajim.XRGIU6XH
> 28.04.2019 15:00:27 (I) gajim.c.p.bytestream: send_file_approval: jingle session accept
> 28.04.2019 15:00:27 (I) gajim.c.jingle_transport: candidate dict, {'host': '2001:bf0:c080:401::1', 'candidate_id': 'a4d859ed-f08b-47bc-9a1e-f95eaca2c013', 'port': 28011, 'type': 'direct', 'jid': 'zone42@jabber.de/gajim.XRGIU6XH', 'priority': 8257536}
> 28.04.2019 15:00:27 (I) gajim.c.jingle_transport: candidate dict, {'host': '172.16.100.130', 'candidate_id': '044445ed-8dab-4cea-bec8-81e7b11a1af1', 'port': 28011, 'type': 'direct', 'jid': 'zone42@jabber.de/gajim.XRGIU6XH', 'priority': 8257536, 'initiator': 'sledz@zone42.org/Conversations.X5GP', 'target': 'zone42@jabber.de/gajim.XRGIU6XH'}
> 28.04.2019 15:00:27 (I) gajim.c.jingle_transport: candidate dict, {'host': '217.197.84.186', 'candidate_id': 'f68e052d-1822-4d40-abfb-942ce3545ba5', 'port': 28011, 'type': 'direct', 'jid': 'zone42@jabber.de/gajim.XRGIU6XH', 'priority': 8257536, 'initiator': 'sledz@zone42.org/Conversations.X5GP', 'target': 'zone42@jabber.de/gajim.XRGIU6XH'}
> 28.04.2019 15:00:28 (I) gajim.c.jingle_ft: __on_iq_result
> 28.04.2019 15:00:28 (I) gajim.c.jingle_ft: connect error, sid=71vf51o68g
> 28.04.2019 15:00:28 (I) gajim.c.jingle_ft: __on_iq_result
> 28.04.2019 15:00:44 (I) gajim.c.jingle_transport: candidate dict, {'host': '2001:bf0:c080:401::1', 'candidate_id': 'a4d859ed-f08b-47bc-9a1e-f95eaca2c013', 'port': 28011, 'type': 'direct', 'jid': 'zone42@jabber.de/gajim.XRGIU6XH', 'priority': 8257536}
> 28.04.2019 15:00:44 (I) gajim.c.jingle_transport: candidate dict, {'host': '172.16.100.130', 'candidate_id': '044445ed-8dab-4cea-bec8-81e7b11a1af1', 'port': 28011, 'type': 'direct', 'jid': 'zone42@jabber.de/gajim.XRGIU6XH', 'priority': 8257536, 'initiator': 'sledz@zone42.org/Conversations.X5GP', 'target': 'zone42@jabber.de/gajim.XRGIU6XH'}
> 28.04.2019 15:00:44 (I) gajim.c.jingle_transport: candidate dict, {'host': '217.197.84.186', 'candidate_id': 'f68e052d-1822-4d40-abfb-942ce3545ba5', 'port': 28011, 'type': 'direct', 'jid': 'zone42@jabber.de/gajim.XRGIU6XH', 'priority': 8257536, 'initiator': 'sledz@zone42.org/Conversations.X5GP', 'target': 'zone42@jabber.de/gajim.XRGIU6XH'}
> 28.04.2019 15:00:44 (I) gajim.c.jingle_transport: candidate dict, {'host': '2001:bf0:c080:401::1', 'candidate_id': '5c6c02ff-585e-43ee-a99c-7b58241667ea', 'port': 28011, 'type': 'direct', 'jid': 'zone42@jabber.de/gajim.XRGIU6XH', 'priority': 8257536}
> 28.04.2019 15:00:44 (I) gajim.c.jingle_transport: candidate dict, {'host': '172.16.100.130', 'candidate_id': '65c6fd2a-1f6c-4e22-a8ee-d65e87e5801c', 'port': 28011, 'type': 'direct', 'jid': 'zone42@jabber.de/gajim.XRGIU6XH', 'priority': 8257536, 'initiator': 'sledz@zone42.org/Conversations.X5GP', 'target': 'zone42@jabber.de/gajim.XRGIU6XH'}
> 28.04.2019 15:00:44 (I) gajim.c.jingle_transport: candidate dict, {'host': '217.197.84.186', 'candidate_id': '4a865b94-2e49-4580-aff3-1fb768732b35', 'port': 28011, 'type': 'direct', 'jid': 'zone42@jabber.de/gajim.XRGIU6XH', 'priority': 8257536, 'initiator': 'sledz@zone42.org/Conversations.X5GP', 'target': 'zone42@jabber.de/gajim.XRGIU6XH'}
> 28.04.2019 15:00:44 (I) gajim.c.jingle_ft: __on_transport_replace
> 28.04.2019 15:00:44 (I) gajim.c.jingle_ft: __on_transport_info
> 28.04.2019 15:00:45 (I) gajim.c.jingle_ft: __on_iq_result
> 28.04.2019 15:00:54 (I) gajim.chatstates: inactive   - sledz@zone42.org
> 28.04.2019 15:01:01 (I) gajim.c.jingle_ft: __on_transport_replace
> 28.04.2019 15:01:01 (I) gajim.c.jingle_ft: __on_transport_info
> 28.04.2019 15:01:01 (I) gajim.c.jingle_ft: __on_iq_result
> 28.04.2019 15:01:17 (I) gajim.c.jingle_ft: __on_transport_replace
> 28.04.2019 15:01:17 (I) gajim.c.jingle_ft: __on_transport_info
> 28.04.2019 15:01:18 (I) gajim.c.jingle_ft: __on_iq_result

**Comment by iNPUTmice** [comment] 2019-04-28 14:50
Thanks for the logs. I have successfully reproduced the issue. Gajim doesn’t handle the fallback to ibb well and sends a session-accept instead of a transport-accept.
In any case you usually don’t want to fall back to ibb anyway as this is way too slow in practice. So I would advise you to enable proxy65 on your server. (or even better http upload)

So this is a bug; it will eventually be fixed when lovetox and i sit down for an interop session; but probably not any time soon.

**Comment by iNPUTmice** [comment] 2019-04-28 15:00
Tracked here: https://dev.gajim.org/gajim/gajim/issues/9692

**Comment by iNPUTmice** [comment] 2019-10-11 16:21
Fixed in Gajim.

**Closed by iNPUTmice** 2019-10-11 16:21 UTC
Labels: Techniker ist informiert
