### ISSUE TITLE
Use phone-number as JID

### ISSUE THREAD

**Issue by simonsample** [siacs/Conversations#906] opened 2015-01-20 00:12 UTC
Hi,

I think conversations is really awesome and getting close to an app that is usable for "everyone". A feature which I personally consider very useful and which would make conversations even much easier to configure would be the following:
In the setup step, a default account (on a certain server?) with the phone number as username is created (like in whatsapp or kontalk, which is also xmpp-based). In this way, users can avoid the registration process and conversations is able to find their friends from the phone numbers in the contact list. An "advanced" setup should of course still be there as well!

This is only an idea I got while thinking about how to spread the app among my friends (who have difficulties to choose a server, register an account, configure conversations and add the friends). 

I am happy for any pro and contra argument!

**Comment by schwindp** [comment] 2015-01-20 06:38
How would you choose such a server to register an account on? Would you require the developers to additionally run this default server?

**Comment by jkufner** [comment] 2015-01-20 06:52
So you are missing a directory service which maps phone numbers to
jabber IDs?

**Comment by simonsample** [comment] 2015-01-20 09:30
> How would you choose such a server to register an account on? Would you require the developers to additionally run this default server?

This is indeed a good and difficult question. By now I can think of two possible answers:
* As you said, the developers run this default server. I have no idea how that would scale, but maybe the additional costs for running the server could be covered by the additional users who are attracted by this feature und purchase the app via google play (or eventually people would donate for this?)
* We ask the admins of existing servers if they would cooperate.

> So you are missing a directory service which maps phone numbers to jabber IDs?

Well, initially I thought of a (jabber) server where the users are automatically registered with their phone numbers as jabber IDs (if they want to), so the number *is* the jabber ID and you need no mapping. Although I also like your idea of a directory service. If the problem with the default server cannot be solved, this could be a second solution, that users would have to register their own account, but they can create a mapping from phone number to JID that they can be easily found by others.

**Comment by cultixate** [comment] 2015-01-21 09:18
There are already XEP to accomplish such.  This of course needs make mention of the Privacy Lists xep-0016.

Or you need not reinvent the wheel:  [open]LDAP

I, myself, would not be amused to have my (private) mobile number associated in a public directory.  You can of course simply add whatever information amuses you to your respective profile.  Such jiggery pokery is available via jappix and can be toyed with via webchat.chatme.im -- after account registration opt to create a public profile. Alternatively: PEP.

How do your "find" friend's communication options now?  Does not this typically involve asking?  I find this works best.  Because the average technology [ab]user cannot be trusted to not-mash the fwd button in email, or submit a friend's private numbers to save thisOrThat site, or share upon request one may opt to have public numbers to share with low trust persons.  The same can be applied to JID as phone numbers [sip capable or otherwise].


Create a second JID with your MDN as username.  Look for others doing likewise?


Xmpp Texting affords one liberty /from/ single device bondage of sms texting.  Why return to needless cost or slavery?


..
http://xmpp.org/extensions/xep-0055.html
http://xmpp.org/extensions/xep-0016.html
http://xmpp.org/extensions/xep-0163.html
http://xmpp.org/extensions/xep-0292.html

**Comment by DrAzraelTod** [comment] 2015-01-23 07:37
phone-numbers are no good way of identifying people

a) a phone-number does not map to a single person (phone numbers are dropped, reasigned)
b) a person does not map to a single phone number (the lesser problem of these)
c) there are different ways of representing phone numbers, numbers might even be non-unique in different countries/nets/area-codes (no, some numbers are not dialable worldwide, your phone might not know about that)

what do you propose should happen if i switch my phone-number and it gets reassigned to a different person? How should that be detected?

How other services handle this currently: they don't, the just break

**Comment by simonsample** [comment] 2015-01-23 10:32
> There are already XEP to accomplish such.

That would also be fine with me, as long as they are working...


> How do your "find" friend's communication options now? Does not this typically involve asking? I find this works best. Because the average technology [ab]user cannot be trusted to not-mash the fwd button in email, or submit a friend's private numbers to save thisOrThat site, or share upon request one may opt to have public numbers to share with low trust persons. The same can be applied to JID as phone numbers [sip capable or otherwise].

I'm not sure if I got you right here. What exactly is the connection between phone number as JID and low trust persons? What would they be able to do that concerns the privacy?


> phone-numbers are no good way of identifying people [...] How other services handle this currently: they don't, the just break

* Maybe it's not the *best* way of identifying people, but at least it's *a* way (the only way I can think of) and users like it (why else would whatsapp be so successfull?)
* In contrast to other services (I'm not sure about this), a jabber account also needs a password, so if the number is reassigned, the other person woudn't be able to use the account. We can also think of some way to revoke/delete the old account and create a new one, in case your number changes. I think conversations can read your phone number, so it should be able to detect if the number changes. Then the user can be asked what to do.

Maybe we could split this whole issue in two discussions:

1. Is it useful to have an identifier like this?
2. Is the phone number the best way to do so or is there another solution?
I think that, although phone numbers might not be the best way of identifying people, it would still be better than nothing.


> I, myself, would not be amused to have my (private) mobile number associated in a public directory.
> Xmpp Texting affords one liberty /from/ single device bondage of sms texting. Why return to needless cost or slavery?

That's why I said this should be optional and if you don't like it, you can just use conversations as before.

I am very surprised in general that this idea is not really supported by you guys. There are so many apps like xabber with which you can use jabber in the traditional way, I thought conversations should provide a very easy and nice interface to enable regular smartphone users to find their way to jabber? I am so sure that many people would love this feature and it would absolutely help to spread jabber.

**Comment by plsng** [comment] 2015-01-23 11:16
"(why else would whatsapp be so successfull?)"

Peer pressure?

**Comment by DrAzraelTod** [comment] 2015-01-23 11:24
> In contrast to other services (I'm not sure about this), a jabber account also needs a password, so if the number is reassigned, the other person woudn't be able to use the account. We can also think of some way to revoke/delete the old account and create a new one, in case your number changes. I think conversations can read your phone number, so it should be able to detect if the number changes. Then the user can be asked what to do.

You don't try to login via your phone number, but to find people with all numbers you know. So login isn't the problem here (you are right, we have a password for that).
The problem is that when you find 100 people for your 200 known phone-numbers, how do you know whose number is still current and whose was reassigned last year?

So in the worst case you will gett littered with dead accounts of people you really don't know because they once had the phone number your friend now uses or you find new accounts of people with phone numbers you couldn't even call, because they are from a local restricted phone-net somewhere.

A better way to do this is already available. It's called E-Mail-Adresses combined with Domain-Names. That's why jabber-adresses were designed like these.

So that would imho be the better idea: search for people who set up their mail-adress as identifying value. You could even try to reach all jabber-accounts with the same name as your mail-adresses in your contacts. That was a good idea until google broke it's service 1-2 years ago.
Now even that keeps you left with mostly non-working gmail-contacts. :-/

**Comment by iNPUTmice** [comment] 2015-01-23 11:41
Using phone numbers as JIDs will break federation which is one of the main advantages of XMPP.
I personally have not interest in doing this. However Conversations is free software. If you think you can be successful with vendor locking a fork of Conversations to a specific server that uses phone numbers as JIDs. Feel free to do so.

**Closed by iNPUTmice** 2015-01-23 11:41 UTC

**Comment by jkufner** [comment] 2015-01-23 15:07
Jabber also have a vcard directory service, so it is possible to search
for people by phone number, however, not many people fill in their
public vcard. And this service is also federated, so you need to know at
least on which server given user is.

Anyway, this feature request can be implemented as a standalone service
and used by many clients. Maybe as a dedicated contact search app...

**Comment by amenk** [comment] 2016-03-17 20:05
(Mobile) Phone numbers  don't have to change that often... At least in Germany you can keep them in most cases when switching providers. No clue how the situation is in other countries.

**Comment by iNPUTmice** [comment] 2018-11-15 10:59
I have now introduced [Quicksy](https://quicksy.im) which is my attempt at providing phone number lookup for in the Jabber world.
Here are are [the slides](https://github.com/iNPUTmice/talks/blob/master/2018_11_14_-_the_making_of_a_new_feature.md) for me introducing this new spin of. And here are [recordings of the German talk](https://media.ccc.de/v/dg-94) I gave.
