### ISSUE TITLE
Conversations crashes and become inoperable when sending long (10,000+ char) messages

### ISSUE THREAD

**Issue by solariiknight** [siacs/Conversations#1717] opened 2016-02-24 04:08 UTC
I recommended (or rather forced :P ) conversations 1.9.4 to a friend of mine. He sent me a very long forward message that has 10,670 cahrs After he sent, the conversations client in his phone crashed. It became inoperable as every-time he opens it, it crashes. His phone is Asus Zenphone 5 . Meanwhile conversations 1.9.4 in my phone becomes very slow when I open the 10,000 char message message he sent me. My phone is HTC Desire X

Kindly look into this issue.

**Comment by iNPUTmice** [comment] 2016-02-24 08:14
duplicate of #1338

**Closed by iNPUTmice** 2016-02-24 08:14 UTC
