### ISSUE TITLE
Unable to recover some MUC messages from Conversation

### ISSUE THREAD

**Issue by martinmix** [siacs/Conversations#3167] opened 2018-09-04 09:13 UTC
Some messages are getting lost in MUC when recovering.

For example I sent a message to one of my friend in a personal group but it is not their now when i changed my device

**Comment by iNPUTmice** [comment] 2018-09-04 15:03
Is this about private messages (whispers) in a group chat? In that case it is duplicate of #2964

**Comment by martinmix** [comment] 2018-09-04 16:09
I have not clear any history or uninstall. I just install the app in a different phone.
Some MUC messages are missing and none of the whisper messages are there. @iNPUTmice

**Comment by golangbu** [comment] 2018-09-22 12:04
I think its the same issue like  #2964 ..
Private message(Whisper) for muc is not storing in conversations.im server.
So you will never get it back again.

**Comment by martinmix** [comment] 2018-09-22 16:38
@iNPUTmice     Is this true..I will never get the messages back.I thought that was an issue

**Comment by iNPUTmice** [comment] 2018-09-22 16:40
Conversations does not request private muc messages from MAM.

**Comment by martinmix** [comment] 2018-09-22 16:45
@iNPUTmice  i have so many message which was private message..I will never get that back?

**Comment by iNPUTmice** [comment] 2018-09-22 16:55
This probably depends on your server they might still be stored and could maybe be retrieved with gajim. but conversations doesn’t request muc pms

**Comment by golangbu** [comment] 2018-09-28 12:19
@martinmix   I am able to restore whisper messages which I have sent in groups by Gajim but received messages are not able to  restore..
May be if you want  to restore only sent whisper messsages you can try with gajim but you will not get received whisper messages

**Comment by yokozu** [comment] 2019-01-16 10:38
@golangbu  I am not able to find Gajim application in play store. Can you provide me the link how to install it

**Comment by licaon-kter** [comment] 2019-01-16 10:42
> @golangbu I am not able to find Gajim application in play store. Can you provide me the link how to install it

Gajim is for PC (Windows/Mac/Linux)

**Comment by yokozu** [comment] 2019-01-16 11:41
@golangbu  Thank you for the clarification.

**Comment by niaomi** [comment] 2019-03-15 09:43
@martinmix  I am also facing  same problem.  @iNPUTmice  i want to work on this problem ?

**Comment by iNPUTmice** [comment] 2019-03-15 10:08
To avoid confusing I’m closing this in favor of the better named #2964

**Closed by iNPUTmice** 2019-03-15 10:08 UTC
