### ISSUE TITLE
QR scanning: Make feature more visible

### ISSUE THREAD

**Issue by ThomasLeister** [siacs/Conversations#3438] opened 2019-04-19 10:31 UTC
# Description of the issue

It's not hard to find the QR code *scanner* button in the top right corner of the "select conversation" screen of Conversations - but it truly is hard to find the *QR code to scan*. I'm a software engineer and consider myself an "experienced user" - still it took me like 5 minutes to find my own QR code (so my sister could scan it with her mobile).

Currently there are two ways of getting the QR code:

* Open any conversation, long-press on your own profile picture, select "show barcode"
* Open "manage accounts" screen, select your account, press "share" button, then "show barcode"

Both are not intuitive. I've heard of many people facing the same problems. 

# The solution

As the "scan QR code" button can easily be found in the "select conversation" screen, the "show QR code" button should also go there. Maybe it it possible to put both (scan and show) into a submenu. Threema is a good example in my opinion:

![Screenshot_20190419-122455](https://user-images.githubusercontent.com/4207956/56420537-9c691d00-629e-11e9-96ce-456fb9af191c.jpg)

@ community please let me know, what you think about it (and if you have experienced the same problem in the past) - upvote if you like the idea.

@ developers please consider making QR code scan more intuitive

**Comment by licaon-kter** [comment] 2019-04-19 10:36
How does Threema handle multiple accounts when you push scan?

**Comment by ThomasLeister** [comment] 2019-04-19 10:38
@licaon-kter Threema is only capable of handling a one single account, therefore no account selection is needed here. 

For conversations there could be multiple QR codes to swipe through - just as you would swipe through a image gallery. :-)

**Comment by iNPUTmice** [comment] 2019-04-19 13:03
duplicate of #2896

**Closed by iNPUTmice** 2019-04-19 13:03 UTC
