### ISSUE TITLE
Recurring subject notifications in MUC

### ISSUE THREAD

**Issue by jastice** [siacs/Conversations#1282] opened 2015-07-15 10:58 UTC
In my group chats, it seems whenever there is a disconnect and reconnect, I will get a notification that the subject has been set, even though it hasn't actually changed. This also spams the chat view quite a bit with multiple "has set the subject to ... " lines.

Version: Conversations 1.4.7

**Comment by SamWhited** [comment] 2015-07-15 14:06
Duplicate of #1269

**Closed** 2015-07-15 15:24 UTC
