### ISSUE TITLE
Cannot send/receive files using Conversations

### ISSUE THREAD

**Issue by falcofox** [siacs/Conversations#2934] opened 2018-04-02 15:03 UTC
#### General information

* **Version:** 1.23.8 (recent version in F-Droid store)
* **Device:** Fairphone 2
* **Android Version:** Android 6.0.1
* **Server name:** self hosted 
* **Server software:** prosody 0.10.0
* **Installed server modules:** defaults plus muc and proxy65
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Start conversation with account user1@my-host.net on my phone.
2. Start Pidgin or Empathy with account user2@my-host.net on my computer.
3. Try to send/receive a file from/to conversion (small text file or image < 500 KB).

#### Expected result

The file (e. g. text file or image) should be transferred.

#### Actual result

In Conversations (when sending): Transfer failed
In Pidgin/Empathy (when sending): I cannot choose any file because the function is greyed out.

But when I use the same accounts with Pidgin and Empathy, the file transfer works. Thus, I it's probably a bug in the Conversations client. Can anyone reproduce this behaviour?

**Comment by licaon-kter** [comment] 2018-04-02 16:36
Update http_module_*

/Close as duplicate of many issues

**Comment by iNPUTmice** [comment] 2018-04-03 07:13
Pidgin and Empathy are not compatible with Conversations when it comes to file transfer. I recommend you check out Gajim.

**Closed by iNPUTmice** 2018-04-03 07:13 UTC
