### ISSUE TITLE
Avatar's not displaying

### ISSUE THREAD

**Issue by TurkeyMan** [siacs/Conversations#1072] opened 2015-03-25 13:51 UTC
I logged into gtalk, and I can see and chat with my contacts, but the avatar's are all just letters.
The avatar's are correctly sourced in the android contacts app, and all other chat programs properly associate my gtalk contacts with those from my android contacts and display the avatars properly.

Have I missed something?

**Comment by iNPUTmice** [comment] 2015-03-27 12:27
Conversations only supports PEP avatars. gtalk doesn't
There is an open issue asking for vcard avatars which is basically duplicate of this.
If your contacts are in your phone book you can also add the JID to your phone book and Conversations will start using the contact names and photos from there.

**Closed by iNPUTmice** 2015-03-27 12:27 UTC

**Comment by TurkeyMan** [comment] 2015-03-27 13:14
Right. But there is plan to automate this connection? It might seem trivial, but I think it's a pretty big barrier to adoption.
