### ISSUE TITLE
"Private message hint" incorrect when having file attached

### ISSUE THREAD

**Issue by alexara** [siacs/Conversations#3442] opened 2019-04-26 11:36 UTC
#### General information

* **Version:** 2.25.0-beta
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Join a MUC
2. Attach a file to your message
3. Long press on an avatar of a participant and choose "private message"
4. Sent message

#### Expected result

There's a hint now, that the message is sent privately, thus the message should be sent privately to the participant.

#### Actual result

Message with file is sent to the public audience.

#### Notes

This issue is related to that one: https://github.com/siacs/Conversations/issues/3372

**Comment by licaon-kter** [comment] 2019-04-26 12:55
The file was attached BEFORE entering private mode? So its expected...I guess?

**Comment by alexara** [comment] 2019-04-26 13:15
> The file was attached BEFORE entering private mode? So its expected...I guess?

The message input field should either be cleared at step 3 or even better stashed for later messages to the public.

**Comment by iNPUTmice** [comment] 2019-04-26 14:06
duplicate of #3372

**Closed by iNPUTmice** 2019-04-26 14:06 UTC

**Comment by alexara** [comment] 2019-04-26 14:45
> duplicate of #3372

Not quiet, because now situation is different: 

1. Long press to send a private message: The blue hint (Send a private message to XY) appears
2. Insert an image: The blue hint vanishes, which thus indicates, that the message won't be private anymore.
