### ISSUE TITLE
Constantly spamming a friend with connects and disconnects that dont display on my screen

### ISSUE THREAD

**Issue by Chaosxlife67** [siacs/Conversations#1956] opened 2016-07-15 20:24 UTC
#### General information

* **Version:** eg 1.12.2
* **Device:** eg Google Nexus 5
* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod
* **Server name:** eg conversations.im, jabber.at or self hosted
* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

#### Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by Chaosxlife67** [comment] 2016-07-15 20:24
Friend has been copy and pasting all my connects and disconnects, it's spamming his chat, please help.

**Comment by SamWhited** [comment] 2016-07-15 20:26
Please actually fill out the template above. I suspect the answer is to use a server with Stream Management, but we can't tell if you don't provide any information.

**Comment by ItchyBugReporter** [comment] 2016-07-15 20:38
I am the guy Chaosxlife67 is having trouble with. We're both on dukgo.com, though I know not what server software they use. I do know that when Chaosxlife67 was using Xabber, reconnects for him were rare enough to not be a problem.

**Comment by jkufner** [comment] 2016-07-15 21:27
Open account details in Conversations, then click the menu button and show server info. You should see list of (un)supported XEPs and between them there should be XE-0198 (Stream Management). If your server does not support it, you will loose your messages every time a connection is lost and message is sent before server notices. If this is the case, fix your server (or ask admin to fix it).

**Comment by jkufner** [comment] 2016-07-15 21:28
Btw, Xabber does not support XEP-0198, so it looses messages on disconnects.

**Comment by ItchyBugReporter** [comment] 2016-07-15 21:31
Except all those disconnects did not seem to be an issue when Chaos was using Xabber. It didn't start happening (that I could see) until *after* he said he switched to Conversations. All of a sudden, I find myself having to litterally search my chat window for messages he sent me when I was AFK. It's extremely annoying, and I'm to the point of begging him to switch back to Xabber.

**Comment by d9h02f** [comment] 2016-07-16 00:01
DuckDuckGo's XMPP service is terrible, use a better one and see if that stops the constant connect/disconnects. If it doesn't, at least you'll be on a much better service overall.

**Comment by d9h02f** [comment] 2016-07-16 00:02
Also, just hide connect/disconnect messages in whatever IM client you're using.

**Comment by ItchyBugReporter** [comment] 2016-07-16 00:41
Using a different service won't fix the issue with Conversations. As mentioned previously, I didn't see so much "reconnect" spam when Chaos was using Xabber, so clearly the issue is with Conversations itself. To further back this up, I tested this with my jabber.org account - the only time my computer saw Xabber reconnect was when I switched back and forth between wifi and mobile data, while my desktop would see repeated reconnections when I was using Conversations.

Also, telling me to change my settings will have no effect on the issue with Conversation, nor am I going to change my settings just because someone else doesn't want to fix a bug.

The best thing here is to accept that there's something weird going on in the way Conversations is handling the connection. It is possible Conversations is terminating the connection too quickly when it sees a bit of connection lag, which is undoubtedly something that would be common in some mobile environments.

**Comment by lovetox** [comment] 2016-07-16 06:57
its not about someone not accepting that there might be somewhere a way to handle this situation better in conversations.

the problem is this takes time and work.
and all this work is for a user who uses an absolutely **bad** xmpp server.

look at this table and search for dukgo.com
https://gultsch.de/compliance.html

nearly everything is red ! you shouldnt use this server for anything. this is not a server you should use with conversations. seriously with this server you can barely send chat messages, every good xmpp feature that is available is not supportet bei dukgo.com

switching server will probably not only solve this problem, it will give you a much better experience overall.

**Comment by iNPUTmice** [comment] 2016-07-16 09:31
Hi,

two ways to handle this. Either you provide a lot more information like what version, what device. How frequent is frequent? Once an hour? Once a minute? Does this happen on wifi as well?
Also you should provide the output of adb logcat (See how do I debug Conversations.)

Or you just install xabber again.

**Comment by ItchyBugReporter** [comment] 2016-07-16 10:52
@lovetox I have to contest what you say about dukgo.com being bad. I use it through tor (!) without any issues whatsoever. I barely see any lag, messages go through without any issues, and it supports every thing I need (i.e. "chat"). **Also. as mentioned previously, this did not happen with Xabber.** Installing Xabber would fix this issue and provide for a much better experience overall. Unfortunately, I can't control what some else uses. If you can't offer useful advice, if all you want to do is repeat some "solution" that has already been discounted, **please don't say anything.** Bug reports aren't for that, **they're for resolving bugs**.

@lovetox It's completely random when it happens, and how frequently it does happen when it does. It can happen two or three times in a row, sometimes it can happen very frequently over several hours. One thing that is consisten is that it happens every single day. As for any other information, I'm trying to nudge Chaos back to this thread.


As for me, I'm unsubscribing from this bug before it turns into a flame war just because people can't accept that a bug is a bug. If more information is needed from me (I doubt it will be since I don't use broken XMPP clients), I'll pass it through Chaos assuming he still uses Conversations long enough to respond to this thread.

**Comment by benediktg** [comment] 2016-07-16 11:52
@ItchyBugReporter: The dukgo XMPP server really misses support for *all* XEPs which are necessary to have a good "mobile XMPP experience" ( @iNPUTmice has described them very well in his essay: https://gultsch.de/xmpp_2016.html). Hence I think @lovetox is right. In addition to that I have to note that on an own server with full compliance I cannot notice any "spam" like you reported.

**Comment by ItchyBugReporter** [comment] 2016-07-16 12:51
I don't know how I got re-subscribed to this bug. If someone other than me somehow managed to do that, **don't**. I unsubscribed for a reason.

For the last time, I repeat myself: **This did not happen when Chaos was using Xabber.** If it doesn't happen in Xabber but it does happen in Conversations, that tells me there's a bug in Conversations.

What people think of one particular server, and what happens on another unrelated server, does not change whether or not there's a bug. Okay, so maybe using a service that supports Stream Management might improve things a bit, but so would making Conversations more resiliant in the face of connection lag. If my mobile device can connect to dukgo.com through tor on a 3G connection using the same phone service as Chaos (i.e. Cricket before it was bought by AT&T) without experiencing this issue on Xabber, then Conversations should not have this issue on a 4G-LTE connection (i.e. Cricket after it was bought by AT&T) without tor.

There seems to be three general attitudes towards bugs in open source:

- Bug fixing is hard, therefor I won't admit there's a bug if I don't have to.*
- Bug fixing is hard, therefor I'll leave it for someone else to fix.
- Bug fixing is hard, but I'm willing to do it.

We seem to be stuck on that first point. We should at least be on point number two, at the very least if the Conversations developers won't look at it, admitting there's a bug might get someone else to look at it.

**Please do not resubscribe me to this bug. I don't know how that was possible, unless Github's unsubscribe button is broke (yes, I did click the button, and it did change after I clicked it).**

**Comment by licaon-kter** [comment] 2016-07-16 13:00
You are not subscribed, you were mentioned, by name. ;)

**Comment by iNPUTmice** [comment] 2016-07-16 14:27
There are two things that can go wrong here. Either the ping timeout is too low. Meaning the network needs too long to respond to our pings. (Given that the timeout is 15 seconds and your are talking about a LTE network here I'm saying this is rather unlikely.) The other thing that could go wrong is your network terminating the NAT pretty aggressively. Conversations only pings every 5 minutes. Xabber afaik pings every 30 seconds. If your networks terminates the connection after <5 minutes of inactivity this could lead to the frequent reconnects you are seeing.

If you @Chaosxlife67 are interested in that I could send you a debug build that pings a lot more frequent to test this theory.

**Comment by Chaosxlife67** [comment] 2016-07-16 17:25
General information

Version:1.12.9
Device: Cricket HTC
Android Version: 4.4.2
Server name: dukgo.com
Server software: Don't know
Installed server modules: Don't know
Conversations source: F-Droid
​

**Comment by iNPUTmice** [comment] 2016-07-16 17:47
@Chaosxlife67 this build [Conversations-1.13.6-aggressive-pings.apk](https://gultsch.de/files/Conversations-1.13.6-aggressive-pings.apk) brings down the ping interval to 60s. See if this helps

**Comment by iNPUTmice** [comment] 2016-07-20 11:18
@Chaosxlife67 did you try that build? Are you still interested in that? Otherwise I'm gonna close here.

**Comment by mimi89999** [comment] 2016-07-23 21:46
I also experience that issue on the "being spammed" end. I am using Gajim from Debian testing and Conversations 1.13.5 from F-Droid. I am running my own server using Prosody trunk. The "spamming" contact is also using Conversations 1.13.5 from F-Droid, but is not able to capture a logcat :-(.

Please ping me if I can help in any way.

**Comment by mimi89999** [comment] 2016-07-23 21:50
I have one contact at jabber.at doing that ~every minute (sic) and another one on my server doing that every ~2min or ~30min or ~1h. It varies and I have no clue what the time depends of.

**Comment by andersruneson** [comment] 2016-07-24 06:57
Just disable the connect/disconnect messages. You don't need that
information.

**Comment by mimi89999** [comment] 2016-07-24 08:29
That is not the point. The point is that IMHO smacks should handle that.

**Comment by iNPUTmice** [comment] 2016-07-24 08:41
@mimi89999 Make sure there are using the latest version. If you suspect that the NAT timeout of their provider is too low feel free to distribute the APK I linked above that pings more aggressively and as always if possible try to get logcats. Otherwise we can't help you.

**Comment by mimi89999** [comment] 2016-07-24 08:50
> Make sure there are using the latest version.

They are, but if they don't, I will remind them to update.

As for the logcat, they are stock, non-rooted and don't even know what is adb or logcat or a custom ROM. The best would be to try to reproduce that issue... I will work on that.

**Comment by mimi89999** [comment] 2016-07-24 11:54
But regardless of what is the reason of the disconnect, shouldn't the session be resumed on a reconnect thanks to smacks?

**Comment by iNPUTmice** [comment] 2016-07-26 14:49
Ok. I'm closing here. This is not a bug report but a vague rant. Without more information we can't help you. If you are still interested in this our channel has a lot of nice people that are willing to help you.

By the way: Are you sure you are not swiping the App away from recent apps. That would kill the app and force a reconnect. In that case you could either stop swiping it away or enable the 'Foreground Service' from the expert settings.

**Closed by iNPUTmice** 2016-07-26 14:49 UTC
