### ISSUE TITLE
Bug: silent hours do not work in winter time (work only during daylight saving time)

### ISSUE THREAD

**Issue by magoralczyk** [siacs/Conversations#2679] opened 2017-11-03 15:19 UTC
#### General information

* **Version:** 1.20.1
* **Device:** Honor 7
* **Android Version:** Android 5.0
* **Server name:**  self hosted
* **Server software:** ejabberd 16.04 
* **Installed server modules:**
* **Conversations source:** F-Droid

#### Steps to reproduce

1. set silent hours to current hour (13-14 if it is 13:30)
2. get a message

#### Expected result

The notification sound should get supressed.

#### Actual result

The notification sound gets played.

This could of course be a problem with the locale. I live in germany and I recognized the problem when we changed form summer to winter time last sunday. The setting needs now an one hour offset to work like intended. A restart of the phone did not help. The phone shows the real (winter) time, so it is not a general clock problem.

**Comment by iNPUTmice** [comment] 2017-11-03 16:05
duplicate of #2565

**Closed by iNPUTmice** 2017-11-03 16:05 UTC
