### ISSUE TITLE
jingle voice calling support

### ISSUE THREAD

**Issue by willstdueswissen** [siacs/Conversations#1427] opened 2015-09-21 21:24 UTC
My question is what the title say.
I would an voice support in conversation.
How do you think?
conversation ist the best xmpp client for android, but if you need calling,you need a other client.

**Comment by andersruneson** [comment] 2015-09-22 05:30
Duplicate?

**Comment by willstdueswissen** [comment] 2015-09-22 06:40
sorry, but where?
I did not find this request!
And sorry for my Bad english.

**Comment by iNPUTmice** [comment] 2015-09-22 06:54
duplicate of #1234

**Closed by iNPUTmice** 2015-09-22 06:54 UTC

**Comment by whitetornado** [comment] 2017-09-05 11:27
is this still actual? i also wants a voip option for conversations

**Comment by licaon-kter** [comment] 2017-09-05 11:52
@whitetornado As the post above says, see #1234
