### ISSUE TITLE
Feature-Requests

### ISSUE THREAD

**Issue by MarkSmz** [siacs/Conversations#3622] opened 2020-01-20 15:38 UTC
#### General information
* **Version:** 2.6.2+fcr
* **Device:** Motorola one Vision
* **Android Version:**  Android 9 (stock)
* **Server name:** jabber.de
* **Server software:** prosody 0.10.2
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

I have been using Conversations as an XMPP client on my smartphone for almost a year now and I am very satisfied with it.
But I also have a few suggestions for improvement that I would like to share with you.
#### Feature Requests
* Rather than adding a "has read up to.." message which takes considerable space and adds visual clutter and dosn't work all the time, it would be wonderful if you could get either a message as before, or a read check mark (next to the sent check mark). So a possibility to decide for one or the other.
* Also, it would be great if the "Select Media" button was at the bottom of the message bar was just to the left of the "Send" button so you can select other media more quickly. For example, my screen is very high, which makes sending a picture or other media quite cumbersome. Again, I think it would be great if the user could choose where they want the button to go.
* Instead of the Media button at the top of the bar, you could provide easier access to the Media Browser, which is currently somewhat hidden in the contact/chat details.
* The online status is currently shown by a green send/quick dial button. A message, i.e. a text, under the name of the chat partner I personally would find a little nicer and more visible. I have forgotten once that the green send button shows the online status and then the online status was unfortunately not immediately visible to me.
An additional status/online message in the contact overview would also be useful, especially if calls will be possible in the future.
* The function to search messages I find useful again and again, but a quick access, using a separate button would be very helpful.
So far you can only search all chats at once, can you add this function to the individual chats so that you can also search only one chat?
* Faster access to contact details by tapping the contact name at the top of the chat window would also be nice.
* I sometimes send a lot of weblinks to my contacts and it would be great if you could see a weblink preview under the link. (This is already planned if I remember correctly?)
* Would it be possible to add a pause button for voice messages. (That has been suggested before as well, I see.)
* Some other messenger have a function called live location, where the position is transmitted continuously over a fixed period of time, so that my contacts see my location even when I move. This would be a useful function for spontaneous meetings.

#### Questions
* You can confirm your identity by means of a QR code, if I have understood correctly. Is there a way to invite other contacts directly with the QR Code? If not, can this be added?
* I noticed on the internet that the addition of VoIP (audio and video calls) was announced for version 3.0. I just wonder if this is true and if it will be this year or later?

**Comment by licaon-kter** [comment] 2020-01-20 15:46
> Rather than adding a "has read up to.." message which takes considerable space and adds visual clutter and dosn't work all the time, it would be wonderful if you could get either a message as before, or a read check mark (next to the sent check mark). So a possibility to decide for one or the other.

https://github.com/siacs/Conversations/pull/3620


> Also, it would be great if the "Select Media" button was at the bottom


    Instead of the Media button at the top of the bar, you could provide easier access to the Media Browser, which is currently somewhat hidden in the contact/chat details.
    The online status is currently shown by a green send/quick dial button. A message, i.e. a text, under the name of the chat partner I personally would find a little nicer and more visible. I have forgotten once that the green send button shows the online status and then the online status was unfortunately not immediately visible to me.
    An additional status/online message in the contact overview would also be useful, especially if calls will be possible in the future.
    The function to search messages I find useful again and again, but a quick access, using a separate button would be very helpful.
    So far you can only search all chats at once, can you add this function to the individual chats so that you can also search only one chat?
    Faster access to contact details by tapping the contact name at the top of the chat window would also be nice.
    I sometimes send a lot of weblinks to my contacts and it would be great if you could see a weblink preview under the link. (This is already planned if I remember correctly?)
    Would it be possible to add a pause button for voice messages. (That has been suggested before as well, I see.)
    Some other messenger have a function called live location, where the position is transmitted continuously over a fixed period of time, so that my contacts see my location even when I move. This would be a useful function for spontaneous meetings.

Questions

    You can confirm your identity by means of a QR code, if I have understood correctly. Is there a way to invite other contacts directly with the QR Code? If not, can this be added?
    I noticed on the internet that the addition of VoIP (audio and video calls) was announced for version 3.0. I just wonder if this is true and if it will be this year or later?

**Comment by licaon-kter** [comment] 2020-01-20 15:52
> Rather than adding a "has read up to.." message which takes considerable space and adds visual clutter and dosn't work all the time, 

https://github.com/siacs/Conversations/pull/3620

> Also, it would be great if the "Select Media" button was at the bottom

https://github.com/siacs/Conversations/issues/2598

> Instead of the Media button at the top of the bar

Like Pix-Art, yes that would be nice, an icon on titlebar near lock/attach

> A message, i.e. a text, under the name of the chat partner I personally would find a little nicer and more visible

Under the name where exactly? each bubble? Titlebar?

> An additional status/online message in the contact overview would also be useful

Enable Dynamic Tags is Settings

>  The function to search messages I find useful again and again, but a quick access, using a separate button would be very helpful.

An loupe in Chats view title bar yes, nice.

> So far you can only search all chats at once, can you add this function to the individual chats so that you can also search only one chat?

/duplicate of https://github.com/siacs/Conversations/issues/3243 and others

> Faster access to contact details by tapping the contact name at the top of the chat window would also be nice.

Tap on avatar in 1:1 or longpress in MUC


> I sometimes send a lot of weblinks to my contacts and it would be great if you could see a weblink preview under the link. (This is already planned if I remember correctly?)

Who is generating the preview? In Pix-Art is the developer server that does this...and sees all your links...

> Would it be possible to add a pause button for voice messages. (That has been suggested before as well, I see.)

https://github.com/siacs/Conversations/pull/3610

> Some other messenger have a function called live location, where the position is transmitted continuously over a fixed period of time

/duplicate of https://github.com/siacs/Conversations/issues/3163

> You can confirm your identity by means of a QR code, if I have understood correctly. Is there a way to invite other contacts directly with the QR Code? If not, can this be added?

Share your QR code, they'll add you as contact too

> I noticed on the internet that the addition of VoIP (audio and video calls) was announced for version 3.0. I just wonder if this is true and if it will be this year or later?

Soon :)

**Comment by iNPUTmice** [comment] 2020-01-20 16:06
Your feedback has been read and acknowledged. @licaon-kter responded to a few of your questions.

**Closed by iNPUTmice** 2020-01-20 16:06 UTC

**Comment by MarkSmz** [comment] 2020-01-21 12:18
> Under the name where exactly? each bubble? Titlebar?

A Message: "Online" / "x minutes ago" under the name in the Titelbar (I know, this only makes sense in 1:1).

> Enable Dynamic Tags is Settings

I had already activated it, but I can't see a difference with or without it.

> Tap on avatar in 1:1 or longpress in MUC

Ohh, I didn't realized it.

> Who is generating the preview? In Pix-Art is the developer server that does this...and sees all your links...

I don't know, I have no idea about that.

> Share your QR code, they'll add you as contact too

Nice, that can make things a lot easier.

Thanks for the help, and I look forward to new features in Conversations.
