### ISSUE TITLE
Issue with OTR - HTML tags are shown on received messages

### ISSUE THREAD

**Issue by alexandru** [siacs/Conversations#1116] opened 2015-04-09 13:18 UTC
See attached screenshot ...

![screenshot_2015-04-09-16-13-13](https://cloud.githubusercontent.com/assets/11753/7067448/fd387afc-ded3-11e4-82a9-03784dcbc849.png)

**Comment by iNPUTmice** [comment] 2015-04-09 13:22
duplicate of #23

**Closed by iNPUTmice** 2015-04-09 13:22 UTC
