### ISSUE TITLE
Adding personal info to vCard user profile

### ISSUE THREAD

**Issue by Marsupio** [siacs/Conversations#1979] opened 2016-08-01 16:56 UTC
I think it would be good to have the possibility to add public info to user profiles, such as interests and areas of expertise

**Comment by Marsupio** [comment] 2016-09-10 12:35
I need some guidance in order to get my hands on this. Could be PEP a suitable way to do it?

**Comment by iNPUTmice** [comment] 2019-01-12 20:45
duplicate of #1779

**Closed by iNPUTmice** 2019-01-12 20:45 UTC
