### ISSUE TITLE
support XEP-0030 (XMPP service discovery)

### ISSUE THREAD

**Issue by rigid** [siacs/Conversations#1622] opened 2015-12-30 20:03 UTC
i'm not sure which XEP that would be, but it would be awesome :)

**Comment by licaon-kter** [comment] 2015-12-30 20:35
https://github.com/siacs/Conversations#how-do-i-create-an-account ?

**Comment by rigid** [comment] 2015-12-30 22:08
ok, i looked it up. I mean http://xmpp.org/extensions/xep-0030.html

**Comment by iNPUTmice** [comment] 2016-01-01 14:34
Conversations automatically looks up services it knows how to talk to. Like MUC servers or HTTP Upload components.

Please describe your use case for a general service discovery.

**Comment by rigid** [comment] 2016-01-01 15:05
on pidgin i use the XMPP service discovery plugin to register with jabber transports. (irc, facebook, etc)  I'm prompted with a login/password form to register once. After that, the transport adds contacts to my roster, provides MUCs etc.

**Comment by iNPUTmice** [comment] 2016-01-01 15:54
duplicate of #913

**Closed by iNPUTmice** 2016-01-01 15:54 UTC
