### ISSUE TITLE
Feature request: Full encryption of the app and encrypted storage for received files.

### ISSUE THREAD

**Issue by nexus4fun** [siacs/Conversations#1766] opened 2016-03-15 10:31 UTC
Hello, wanted to ask if there is any plans to add full encryption of the app? Something like ChatSecure. Was nice if there was a future to keep received Pictures/Files in an encrypted folder.

**Comment by d9h02f** [comment] 2016-03-15 11:24
Encrypt your device.

**Comment by lovetox** [comment] 2016-03-15 11:48
newer android version have an encrypted harddisk, i think

**Comment by iNPUTmice** [comment] 2016-03-16 09:47
duplicate of #1002

**Closed by iNPUTmice** 2016-03-16 09:47 UTC
