### ISSUE TITLE
Feature Request: XEP-138

### ISSUE THREAD

**Issue by volga629** [siacs/Conversations#2013] opened 2016-09-10 15:18 UTC
#### General information

* **Version:** eg 1.14.1
* **Device:** Google Nexus 6
* **Android Version:** Android 7.0 
* **Server name:**  internal domains
* **Server software:** ejabberd 16.08
* **Conversations source: PlayStore

Hello Everyone,
I would like ask add stream compression feature described in XEP-138.

https://xmpp.org/extensions/xep-0138.html

Thank you.

**Comment by iNPUTmice** [comment] 2016-09-10 15:58
duplicate of #1395

**Closed by iNPUTmice** 2016-09-10 15:58 UTC
