### ISSUE TITLE
Keep audio "drafts"

### ISSUE THREAD

**Issue by paskalito** [siacs/Conversations#3348] opened 2019-01-20 13:09 UTC
#### General information

* **Version:** 2.3.8+fcr
* **Device:** S4
* **Android Version:** Android 7 LOS
* **Conversations source:** fdroid

#### Steps to reproduce

1. Record audio message
2. click on share after you finished
3. go back to the conversasions view

#### Expected result

That my voice message is sent.

#### Actual result

my voice message gets dropped

### My thoughts.

This problem ob loosing voice messages started with the privacy feature of not sending the messages immedeatly after sharing.

Therefore since this change the field "share" when recording voice messages is actually misleading. more accurate would be: "shedule". or a not really implying anything "ok".

with this privacy feature still on an 
#### alternative expectet result would be.
Having my voice message still as a draft, so i can just hit the send button.

### Longterm possible solutions.

- Make it an option if the voice messages get sent immedeatly or if they should be sheduled.

In the Sheduled version.
- the "share" button should be renamed to something matching
- drafts should be kept.

In the old/direct sending version/option
- Everything could be the old way and also stayed named as it is.

**Comment by iNPUTmice** [comment] 2019-01-20 13:15
closing as duplicate of #3239

**Closed by iNPUTmice** 2019-01-20 13:15 UTC
