### ISSUE TITLE
Dark theme support?

### ISSUE THREAD

**Issue by kr428** [siacs/Conversations#529] opened 2014-10-09 08:26 UTC
Is there a chance to have a dark theme support in Conversations? I just saw an old pull request over here which apparently never made it into the app.

**Comment by moorchegue** [comment] 2015-02-28 07:37
Is there any progress on this?

**Comment by h-2** [comment] 2015-04-05 18:03
I agree, it would really, really nice to have :+1:

**Comment by sedrubal** [comment] 2015-07-19 14:35
:+1:

**Comment by mhspace** [comment] 2015-08-06 17:29
@iNPUTmice wrote:
>I'm afraid the market for this is way too niche since all the 'proper' (google) apps don't have a selectable theme either. 

&lt;sarcasm&gt;
I'm afraid the market for Jabber/XMPP is way too niche since there is no google app that works with it.
&lt;/sarcasm&gt;
Talking seriously, there are number of reasons to prefer dark theme:
* accessibility / vision diseases. for example, macular degeneration, posterior cataract (well, my case), etc.
* tastes
* preserving batteries on AMOLED
* something that I've missed

Talking about system-wide support for dark theme, there is no problems with that on desktop GNU/Linux and desktop windows.
But on android the only available option (since lolipop) is 
>A great way to convince me other wise would be to donate to the project and add dark theme as feature wish in the description.

**Comment by mhspace** [comment] 2015-08-06 17:46
@iNPUTmice wrote:
>I'm afraid the market for this is way too niche since all the 'proper' (google) apps don't have a selectable theme either. 

&lt;sarcasm&gt;
I'm afraid the market for Jabber/XMPP is way too niche since there is no google app that works with it.
&lt;/sarcasm&gt;
Talking seriously, there are number of reasons to prefer dark theme:
* accessibility / vision diseases. for example, macular degeneration, posterior cataract (well, my case), etc.
* tastes
* preserving batteries on AMOLED
* something that I've missed

Talking about system-wide support for dark theme, there is no problems with that on desktop GNU/Linux and desktop windows.
But on android the only available option (since lollipop) is 'invert colors' that is similar to OSX/iOS and also is pure bullshit.
Other variants are:
* dark themes for cyanogenmod ([Material Dark (CM12+)](https://play.google.com/store/apps/details?id=com.chummy.jezebel.material.dark.regression), [BlackedOut (CM10/11)](https://play.google.com/store/apps/details?id=com.blackout1911.theme.BlackedOutTheme) etc)
* Use patched for dark theme apps (like ones that [this guys make](http://forum.xda-developers.com/showthread.php?t=2283828))
* use dark theme that certain developer has built in to his own app (like K-9 Mail), hereof this issue.

>A great way to convince me other wise would be to donate to the project and add dark theme as feature wish in the description.

Done.

**Comment by moorchegue** [comment] 2015-08-06 17:50
I kinda like this app, but dislike author's attitude about this. Asked donations were given, the whole work was done, but pull request was closed, no progress since then and even no answers.

**Comment by iNPUTmice** [comment] 2015-08-06 17:54
> the whole work was done by other contributor

that's not true. The PR had issues that were not addressed by the original author.

**Comment by iNPUTmice** [comment] 2015-08-06 18:10
Hi,

I also realized that asking for donations is not the right approach. Sorry about that. This is something that should better be handled by bounty source and open this up to third party contributors. I didn't know about bounty source at the time (or at least had not used it).

I will put every Dollar I received from donations mentioning a dark theme into a bounty source pledge for this issue.
It might take some time to double check everything but afair there weren't that many. (I remember too individuals from the top of my head. But I will double and triple check and then create a bounty.)

**Comment by mhspace** [comment] 2015-08-06 18:36
@iNPUTmice , what is bounty source?

I'm not an android developer, but I patch and rebuild Conversations by myself to support dark theme for near every version:
![screenshot_2015-08-06-21-24-32](https://cloud.githubusercontent.com/assets/930015/9119975/61b05a84-3c82-11e5-80e2-423003c3e4dc.png)
It takes about 20 mins and is not very hard.
But to make it production-ready, you need:
* add an option to choose preferred theme
* update icons to support both themes

Am I missed something? Is it too time consuming?

**Comment by iNPUTmice** [comment] 2015-08-06 18:40
> what is bounty source?

It's crowd funding like kick starter for example but specifically for open source projects and integrated into github. You can reference github issues. And if the github issue gets resolved the one that resolved it gets the 'bounty'.

**Comment by mhspace** [comment] 2015-08-06 21:08
@iNPUTmice wrote:
>I'm afraid the market for this is way too niche since all the 'proper' (google) apps don't have a selectable theme either. 

&lt;sarcasm&gt;
I'm afraid the market for Jabber/XMPP is way too niche since there is no google app that works with it.
&lt;/sarcasm&gt;
Talking seriously, there are number of reasons to prefer dark theme:
* accessibility / vision diseases. for example, macular degeneration, posterior cataract (well, my case), etc.
* tastes
* preserving batteries on AMOLED
* something that I've missed

Talking about system-wide support for dark theme, there is no problems with that on desktop GNU/Linux and desktop windows.
But on android the only available option (since lolipop) is 
>A great way to convince me other wise would be to donate to the project and add dark theme as feature wish in the description.

**Comment by mhspace** [comment] 2015-08-06 21:08
@iNPUTmice wrote:
>I'm afraid the market for this is way too niche since all the 'proper' (google) apps don't have a selectable theme either. 

&lt;sarcasm&gt;
I'm afraid the market for Jabber/XMPP is way too niche since there is no google app that works with it.
&lt;/sarcasm&gt;
Talking seriously, there are number of reasons to prefer dark theme:
* accessibility / vision diseases. for example, macular degeneration, posterior cataract (well, my case), etc.
* tastes
* preserving batteries on AMOLED
* something that I've missed

Talking about system-wide support for dark theme, there is no problems with that on desktop GNU/Linux and desktop windows.
But on android the only available option (since lolipop) is 
>A great way to convince me other wise would be to donate to the project and add dark theme as feature wish in the description.

**Comment by mhspace** [comment] 2015-08-06 21:08
@iNPUTmice wrote:
>I'm afraid the market for this is way too niche since all the 'proper' (google) apps don't have a selectable theme either. 

&lt;sarcasm&gt;
I'm afraid the market for Jabber/XMPP is way too niche since there is no google app that works with it.
&lt;/sarcasm&gt;
Talking seriously, there are number of reasons to prefer dark theme:
* accessibility / vision diseases. for example, macular degeneration, posterior cataract (well, my case), etc.
* tastes
* preserving batteries on AMOLED
* something that I've missed

Talking about system-wide support for dark theme, there is no problems with that on desktop GNU/Linux and desktop windows.
But on android the only available option (since lolipop) is 
>A great way to convince me other wise would be to donate to the project and add dark theme as feature wish in the description.

**Comment by mhspace** [comment] 2015-08-06 21:08
@iNPUTmice wrote:
>I'm afraid the market for this is way too niche since all the 'proper' (google) apps don't have a selectable theme either. 

&lt;sarcasm&gt;
I'm afraid the market for Jabber/XMPP is way too niche since there is no google app that works with it.
&lt;/sarcasm&gt;
Talking seriously, there are number of reasons to prefer dark theme:
* accessibility / vision diseases. for example, macular degeneration, posterior cataract (well, my case), etc.
* tastes
* preserving batteries on AMOLED
* something that I've missed

Talking about system-wide support for dark theme, there is no problems with that on desktop GNU/Linux and desktop windows.
But on android the only available option (since lolipop) is 
>A great way to convince me other wise would be to donate to the project and add dark theme as feature wish in the description.

**Comment by tvall43** [comment] 2015-08-26 06:58
I also would love a dark theme. I use this app on my galaxy gear, and its the only app that isn't a dark theme.

**Comment by krt16s** [comment] 2015-08-29 12:36
@iNPUTmice could you check your paypal account, there should have been a 25EUR donation for this issue

**Comment by iNPUTmice** [comment] 2015-08-30 08:33
@krt16s added that to the BountySource Pledge

**Comment by Matthias84** [comment] 2016-02-09 19:18
I'm sorry to push this issue again, but I also would love to see that design (esp. at night). So the issue is closed, but  without any note, if it will be implemented or not. ~50USD had been collected and also an ressource patch had been suggested.

So are there any plans?

**Comment by benediktg** [comment] 2016-06-04 14:26
Wouldn't #1842 resolve this feature request? I'd appreciate it because the screenshots are already looking nice.

**Comment by Matthias84** [comment] 2016-06-04 14:36
IMHO Yes

**Closed** 2016-06-08 18:19 UTC

**Comment by krt16s** [comment] 2016-07-04 22:25
While the dark theme looks great, I'd rather prefer an option for an all-black / night theme, like:
![conversations-amoled](https://cloud.githubusercontent.com/assets/6763207/16570507/d24704a8-4246-11e6-8c7a-acbaf65daa73.png)

(I just force-rewrite the colors on build, so this is not workign as an PR)

**Comment by moshpirit** [comment] 2016-10-23 16:34
Is there any chance to add a night mode? To use the dark them just during a period of time.

**Comment by rugk** [comment] 2016-11-09 20:29
So I've created a new issue for that: https://github.com/siacs/Conversations/issues/2111
