### ISSUE TITLE
Couldn't read row 0, col -1 from CursorWindow

### ISSUE THREAD

**Issue by dicer** [siacs/Conversations#1549] opened 2015-11-06 12:54 UTC
I can't open Conversations anymore as it crashes with the following log. This is happening after an update from 1.6.7/8 (don't exactly remember) to 1.7.2

I/ActivityManager(  443): Start proc eu.siacs.conversations for activity eu.siacs.conversations/.ui.ConversationActivity: pid=3254 uid=10056 gids={50056, 1028, 1015, 3003}
D/ActivityThread( 3254): handleBindApplication:eu.siacs.conversations
D/ActivityThread( 3254): setTargetHeapUtilization:0.75
D/ActivityThread( 3254): setTargetHeapMinFree:2097152
I/iu.UploadsManager(22199): num updated entries: 0
I/dalvikvm( 3254): Could not find method android.os.PowerManager.isInteractive, referenced from method eu.siacs.conversations.services.XmppConnectionService.isInteractive
W/dalvikvm( 3254): VFY: unable to resolve virtual method 1252: Landroid/os/PowerManager;.isInteractive ()Z
D/dalvikvm( 3254): VFY: replacing opcode 0x6e at 0x0013
E/CursorWindow( 3254): Failed to read row 0, column -1 from a CursorWindow which has 1 rows, 8 columns.
D/AndroidRuntime( 3254): Shutting down VM
W/dalvikvm( 3254): threadid=1: thread exiting with uncaught exception (group=0x41933ce0)
E/AndroidRuntime( 3254): FATAL EXCEPTION: main
E/AndroidRuntime( 3254): Process: eu.siacs.conversations, PID: 3254
E/AndroidRuntime( 3254): java.lang.RuntimeException: Unable to create service eu.siacs.conversations.services.XmppConnectionService: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
E/AndroidRuntime( 3254):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2606)
E/AndroidRuntime( 3254):        at android.app.ActivityThread.access$1800(ActivityThread.java:144)
E/AndroidRuntime( 3254):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
E/AndroidRuntime( 3254):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3254):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3254):        at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime( 3254):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3254):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3254):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime( 3254):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime( 3254):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3254): Caused by: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
E/AndroidRuntime( 3254):        at android.database.CursorWindow.nativeGetString(Native Method)
E/AndroidRuntime( 3254):        at android.database.CursorWindow.getString(CursorWindow.java:434)
E/AndroidRuntime( 3254):        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
E/AndroidRuntime( 3254):        at eu.siacs.conversations.entities.Account.fromCursor(Account.java:185)
E/AndroidRuntime( 3254):        at eu.siacs.conversations.persistance.DatabaseBackend.getAccounts(DatabaseBackend.java:490)
E/AndroidRuntime( 3254):        at eu.siacs.conversations.persistance.DatabaseBackend.onUpgrade(DatabaseBackend.java:308)
E/AndroidRuntime( 3254):        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:257)
E/AndroidRuntime( 3254):        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
E/AndroidRuntime( 3254):        at eu.siacs.conversations.persistance.DatabaseBackend.getAccounts(DatabaseBackend.java:481)
E/AndroidRuntime( 3254):        at eu.siacs.conversations.services.XmppConnectionService.onCreate(XmppConnectionService.java:656)
E/AndroidRuntime( 3254):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2596)
E/AndroidRuntime( 3254):        ... 10 more
W/ActivityManager(  443):   Force finishing activity eu.siacs.conversations/.ui.ConversationActivity
I/iu.SyncManager(22199): NEXT; no task
W/DropBoxManagerService(  443): Dropping: data_app_crash (2221 > 0 bytes)
I/iu.FingerprintManager(22199): Finished generating fingerprints; 14.157 seconds
I/iu.FingerprintManager(22199):   numSeen=12516 numGenerated=0 numDeleted=0 numFailed=0
W/FlurryAgent(31071): FlurryDataSender: report 2fe034ff-6331-4555-95dc-cf0ec962f6db sent. HTTP response: 200
I/WindowManager(  443): Screenshot max retries 4 of Token{41f69df0 ActivityRecord{41d79aa8 u0 eu.siacs.conversations/.ui.ConversationActivity t24 f}} appWin=Window{41d86f70 u0 Starting eu.siacs.conversations} drawState=4
W/WindowManager(  443): Screenshot failure taking screenshot for (720x1280) to layer 21040
I/ActivityManager(  443): Waited long enough for: ServiceRecord{42e88248 u0 com.google.android.googlequicksearchbox/com.google.android.search.core.service.SearchService}
I/ActivityManager(  443): Process com.google.android.partnersetup (pid 3199) has died.
W/ActivityManager(  443): Activity pause timeout for ActivityRecord{41d79aa8 u0 eu.siacs.conversations/.ui.ConversationActivity t24 f}
I/Timeline(28424): Timeline: Activity_idle id: android.os.BinderProxy@42038b40 time:36766939
I/Timeline(  443): Timeline: Activity_windows_visible id: ActivityRecord{4264b780 u0 com.cyanogenmod.trebuchet/org.cyanogenmod.trebuchet.CustomHomeLauncher t1} time:36767350

**Comment by strb** [comment] 2015-11-06 13:33
Hi, thanks for reporting this! If you are building the app yourself I can push a quick fix for you in a Moment. But if you have installed this from Google Play you will unfortunately have to wait around 2 weeks until @iNPUTmice 
returns from his vacation, as only he can publish new versions to the Play store.

**Comment by dicer** [comment] 2015-11-06 13:35
I use the fdroid version. I was just about to look into the code. Do you know which column is wrong? Can I maybe fix this in the DB?

**Comment by strb** [comment] 2015-11-06 13:44
The problem is that the DB upgrade from <17 depends on Account de-serialization, but in version 19 the accounts table was altered, so the version 17 migration depends on the version 19 migration, but they are applied in order from lowest to highest, which leads to this crash.  Executing `ALTER TABLE accounts ADD COLUMN display_name TEXT` should fix this issue for you.

**Comment by strb** [comment] 2015-11-06 13:57
Fixed in c6e54e7e5a3e402553d2f57e2997fb80d029d559

If you need any further assistance in manually resolving this on your end, let me know and I'll do my best to help.

**Closed by strb** 2015-11-06 13:57 UTC

**Comment by strb** [comment] 2015-11-06 14:16
Just realized that this fix might break the subsequent migration to version 19, which will then try to add a column that already exists. If this happens, I guess you could try manually incrementing the database version code from 18 to 19 to skip that migration, which you will have already performed manually. according to [StackOverflow](http://stackoverflow.com/questions/3707797/where-does-android-store-sqlites-database-version), this sits at byte offset 60 in the db file.

**Comment by dicer** [comment] 2015-11-06 14:30
Yeah, I updated the schema. Now it crashes because it wants to do the same update itself. I looked at the DB:
sqlite> pragma user_version;
16
I understand your change so I guess it is not that easy to update the DB. Especially since the update 17 is way more complex then some SQL statements. I think I'll try and install older versions from fdroid to get this resolved.

**Comment by dicer** [comment] 2015-11-06 15:34
Since android wouldn't let me downgrade, I had to uninstall Conversations. Did a backup first, installed 1.6.11 and restored the backup. That upgraded my DB to 17, then upgraded Conv straight to 1.7.2 and am now on DB version 19. All working again.

For anyone running into the same issue, here is a quick rundown of how I solved it on my rooted device. You may wanna use Titanium Backup or one of those app data backup solutions though if you don't know exactly what I am talking about below this point!!

adb shell
su
cd /data/data
tar czf /data/local/tmp/conv.tar.gz eu.siacs.conversations
-> you might wanna backup that conv.tar.gz to your computer!
-> uninstall Conversations
-> Install version 1.6.11
-> start it and force close it in the android settings
adb shell
su
cd /data/data/eu.siacs.conversations
mv /data/local/tmp/conv.tar.gz .
tar xzf conv.tar.gz
ll
-> look at the user and group used for the databases folder. Use that in the chmod step
cd /data/data/eu.siacs.conversations/eu.siacs.conversations
chown u0_axxx:u0_axxx app_KeyStore cache databases files shared_prefs
-> somehow my chown does not support -R or -r so I had to go into all subdirs and their subdirs and so a chown u0_axxx:u0_axxx * there
cd /data/data/eu.siacs.conversations
rm -r app_KeyStore/ cache/ databases/ files/ shared_prefs/
cd eu.siacs.conversations/ 
cp -paRv app_KeyStore/ cache/ databases/ files/ shared_prefs/ ..
cd /data/data/eu.siacs.conversations
ll
-> check that permissions fit
rm -r eu.siacs.conversations/ 
rm conv.tar.gz
