### ISSUE TITLE
Feature-Request: Dont merge messages sent in short time interval

### ISSUE THREAD

**Issue by brandsimon** [siacs/Conversations#3609] opened 2020-01-07 02:04 UTC
Usually people use separate messages for separate matters.
At the moment messages which are sent in a short time interval get automatically merged.
Now it is difficult to quote each matter separately, because everything got merged together into a big blob.

I'd prefer a setting to stop messages from getting merged.
If this feature is something which get merged, I think I can implement this myself. Please let me know your thoughts.

**Comment by jacksgt** [comment] 2020-01-08 09:43
I fully agree with this. Automatically merging messages also makes it more difficult to reply to individual messages, since a single message can no longer simply be quoted.

An example:
```
Alice:
I just had an ice cream.
My mother broke her leg today.

Bob:
Nice.
Really?!?
```

vs. 

```
Alice:
I just had an ice cream.

My mother broke her leg today.

Bob:
> I just had an ice cream.
Nice.

> My mother broke her leg today.
Really?!?
```

Usually, individual messages reflect individual thoughts and thus should also be visually separate. Thus I would also be happy to complete remove the automatic merging of messages.

**Comment by iNPUTmice** [comment] 2020-01-08 10:09
duplicate of #3568. see my response there.

**Closed by iNPUTmice** 2020-01-08 10:09 UTC

**Comment by brandsimon** [comment] 2020-01-08 10:47
Is there something for the future design I can help with?
