### ISSUE TITLE
Show contact presence in conversations list

### ISSUE THREAD

**Issue by sniperle** [siacs/Conversations#1254] opened 2015-06-16 13:21 UTC
It would be great to have the status/availability/presence (on/off) of each person directly shown in the conversations list, not just "only" in the contacts list (when dynamics tags is enabled). Hopefully you can add this (maybe within the enable dynamic tags) feature. Thanks.

**Comment by SamWhited** [comment] 2015-06-16 14:24
Duplicate of #236, #61, #477, and #451 among others.

Also covered in [the FAQ](https://github.com/siacs/Conversations#where-can-i-see-the-status-of-my-contacts-how-can-i-set-a-status-or-priority).

**Closed** 2015-06-19 14:26 UTC
