### ISSUE TITLE
Incomplete message notification displayed on notification drawer

### ISSUE THREAD

**Issue by marveljy** [siacs/Conversations#3264] opened 2018-11-09 03:02 UTC
#### General information

* **Version:** 2.3.5
* **Device:**  Google Nexus 5X
* **Android Version:** Android 7.1.1 Nougat
* **Server name:**  conversations.im
* **Conversations source:**  F-Droid

#### Steps to reproduce

1. Run Conversations
2. Receive multiple messages from one contact

#### Expected result

Notification drawer displays the message (at least the newest message and the message count) correctly. 

#### Actual result

Notification drawer only displays the oldest message and lacks the message count.

#### Debug output

This issue is an unreasonable design instead of bug making program crash. It is significative to improve the code of notification to make user experience better.

**Comment by iNPUTmice** [comment] 2018-11-10 06:56
duplicate of #1559

**Closed by iNPUTmice** 2018-11-10 06:56 UTC
