### ISSUE TITLE
First message not delivered

### ISSUE THREAD

**Issue by sniperle** [siacs/Conversations#820] opened 2014-12-29 13:26 UTC
When I open a chat or reopen an existing chat after a while, the first message sent in that chat is not delivered. Starting with the second message all messages arrive as expected.

**Comment by iNPUTmice** [comment] 2015-01-02 10:51
I'm guessing this is for OTR messages? If so please use a server that has stream management enabled (you should do that anyway) 
duplicate of #635

**Comment by iNPUTmice** [comment] 2015-01-11 15:39
No reaction from OP? closed

**Closed by iNPUTmice** 2015-01-11 15:39 UTC

**Comment by sniperle** [comment] 2015-01-11 17:58
I'm using jabber.org
