### ISSUE TITLE
Add "shut down" menu item.

### ISSUE THREAD

**Issue by skorokithakis** [siacs/Conversations#1092] opened 2015-03-31 15:08 UTC
Sometimes, I just want to shut down the app and log off of everything. Would it be possible to add a "shut down" item to the settings menu?

**Comment by timosl** [comment] 2015-03-31 15:54
Duplicate of #74

**Comment by skorokithakis** [comment] 2015-03-31 16:10
I'd close this as duplicate, but that one is closed as well, and this is enough of a deal breaker for me that I may go back to ChatSecure instead, so I'll leave this open until the dev weighs in.

**Comment by SamWhited** [comment] 2015-03-31 16:26
If you sign out of all your accounts (eg. with the "Disable all accounts" button, or by long pressing and hitting "Disable" on each account), and then swipe the app away, it exits. This is the Android way to do this, and Conversations does it already.

**Closed** 2015-03-31 17:14 UTC
