### ISSUE TITLE
[Feature Request] Review attachments before sending

### ISSUE THREAD

**Issue by santifa** [siacs/Conversations#2282] opened 2017-02-08 12:23 UTC
It would be a nice feature to get the chance to verify attachments before sending.
At the moment an attachment is sent right after the selection or camera app returns.
Like other apps (Signal) a "second" verification may be useful to prevent sending wrong files or low-quality pictures directly from the camera app. This could be done with showing a thumbnail or something else within Conversation and by pressing the send button instead of only selecting the media file.

**Comment by iNPUTmice** [comment] 2017-02-09 11:21
duplicate of #1879

**Closed by iNPUTmice** 2017-02-09 11:21 UTC

**Comment by tmolitor-stud-tu** [comment] 2017-04-21 14:41
See #1879
