### ISSUE TITLE
Implement custom emoticons using XEP 0231

### ISSUE THREAD

**Issue by albjeremias** [siacs/Conversations#3068] opened 2018-06-05 17:00 UTC
source:
https://developer.pidgin.im/ticket/5627

I think all important info is inside! :)

**Comment by licaon-kter** [comment] 2018-06-05 17:27
Use search.

/close as duplicate of #2122

**Comment by albjeremias** [comment] 2018-06-06 07:29
oooh.. i used search.. i saw that one.. but thought it was a different thing... one is stickers other is custom emoji... have you used mastodon custom icons?

**Comment by benrob0329** [comment] 2018-06-06 13:36
@licaon-kter Stickers are definitely not the same thing as custom emoji. (Come on guys, how many people are completely lost with this stuff?)

Stickers are images you can send and subscribe to in "packs", while custom emoji are self-added emoticons used equivalently to normal emoji.

**Comment by licaon-kter** [comment] 2018-06-06 13:47
Read the thread there, 0231 was also mentioned.

**Closed** 2018-06-13 12:17 UTC
