### ISSUE TITLE
Show offline contacts in private groups

### ISSUE THREAD

**Issue by aurabindo** [siacs/Conversations#1849] opened 2016-05-15 13:49 UTC
Offline contacts are only listed for public groups. It makes sense to list it for private groups as well.

**Comment by pravi** [comment] 2016-05-15 14:05
For public conferences, offline contacts doesn't make sense. For members only it helps to know who all are members even when they are offline.

**Comment by pravi** [comment] 2016-05-15 14:10
We are testing omemo for conferences. I added a omemo trusted contact to group, but now @aurobindo cannot chose omemo because he does not have that contact in his roster. He can't add manually too since it is not shown in members list. It would be good to notify each member when new members are added. Also if the new members keys are not trusted, it should be fetched at that point so the conference can continue as an encrypted conference.

**Comment by iNPUTmice** [comment] 2016-05-15 14:20
duplicate of #1775?

**Comment by pravi** [comment] 2016-05-15 14:25
Same issue, but more urgent in omemo context.

**Comment by pravi** [comment] 2016-05-15 14:38
May be this can be retitiled to "new contacts and omemo conferences"

**Closed** 2016-05-15 14:43 UTC
