### ISSUE TITLE
Messages bloked when app is not in foreground

### ISSUE THREAD

**Issue by mikemaikaefer** [siacs/Conversations#2771] opened 2018-01-26 12:55 UTC
#### General information

* **Version:** eg 1.23.3
* **Device:** eg HTC
* **Android Version:** eg Android 4
* **Server name:** eg jabber.at and self hosted
* **Conversations source:** eg PlayStore

Conversations does not receive messages when the app is not in foreground. In this case on the sender side the message is sent, stays in status "waiting" and may need up to several hours to arrive at the other end. When both apps are in foreground during communication the messages arrive immediately and with a delay of only a few seconds.
This is a mess the app is unusable with this bug.

**Comment by iNPUTmice** [comment] 2018-01-26 13:06
Please provide more information on the device in question.

Does enabling the foreground service in the expert options help?

**Comment by mikemaikaefer** [comment] 2018-01-26 13:11
Foreground option is enabled but this does not make difference. Shouldn't this be enabled by default instead of being hidden behind a warning which keeps users away?

Device is a HTC tablet from a no-name vendor I have no idea what hardware it is exactly.

**Comment by iNPUTmice** [comment] 2018-01-26 13:16
> Foreground option is enabled but this does not make difference. Shouldn't this be enabled by default instead of being hidden behind a warning which keeps users away?

No. Usually it is not needed.

Do you have the keep wifi awake during sleep option set? In the wifi settings - not in Conversations.

Try post the output of `adb logcat` (see Readme) when the app is open and when it is closed.

If you use OTR please try to send unencrypted messages as a test.

**Comment by mikemaikaefer** [comment] 2018-01-26 13:31
Don't know about WiFi settings but Whatsapp and Facebook are working without problems. I do not use OTR.
I afraid I don't understand the adb readme, where can I find this app? Is it available in playstore? When I search for "adb" I get dozens of different apps.

**Comment by licaon-kter** [comment] 2018-01-26 15:29
You need a PC and an USB cable.
You need to enable Developer Mode on the device.
You need to install at least ADB and maybe drivers for your device.

I's not an app.

But, maybe you have root access?

**Comment by kollix** [comment] 2018-01-27 12:34
I see the same problem with the following configuration:
- conversations 1.23.3 installed from F-Droid
- conversations expert setting: foreground service enabled
- Phone: Huawei p9 lite, Android 7.0
- Phone setting: WLAN: in standby always on

I attach an adb logcat grepped with "eu.siacs.conversations".
The timeline tests were:
13:16:12  foreground - message arrived
13:16:44 stopped conversations - message arrived
13:17:25 standby + stopped -> no notification!!!
13:18:15 activated phone, app in foreground -> message arrived

When the app is closed, the phone is in standby, I send a message, it will not be received.
Even when I then resume the phone, the notification is not received!!!
I need to explicitely start conversations to receive the previous message.

**Comment by iNPUTmice** [comment] 2018-01-27 13:06
@kollix on Huawai phones you need to add Conversations to the 'protected apps'. That's a different issue. This issue is about HTC phones.

**Comment by whitetornado** [comment] 2018-01-27 13:08
also special settings for Motorola have the same issue. Wi-Fi stays connect
but on 3g and idle no messages

Op 27 jan. 2018 14:06 schreef "Daniel Gultsch" <notifications@github.com>:

**Comment by iNPUTmice** [comment] 2018-01-27 22:28
@kollix can you check if this build: http://gultsch.de/files/Conversations-1.23.4-playstore-release.apk shows a 'Protected Apps' settings in the Conversations settings that deep links into the Huawei protected app screen?

**Comment by kollix** [comment] 2018-01-28 17:38
On Samstag, 27. Jänner 2018 23:28:37 CET Daniel Gultsch wrote:
> @kollix can you check if this build: http://gultsch.de/files/Conversations-1.23.4-playstore-release.apk shows a 'Protected Apps' settings in the Conversations settings that deep links into the Huawei protected app screen?
> 

Yes, in "Settings" as 3rd option I now find "Protected Apps" which leads to the Huawei menu "Lock screen cleanup".

Question: it's not really clear if push notifications shall work even with the F-Droid version.

On https://conversations.im/ I read "Even though Conversations keeps its own connection to the XMPP server and thus is independent of Google’s push messaging system (GCM),..."

and on https://github.com/siacs/Conversations I read
"You need to be running the Play Store version of Conversations and your server needs to support push notifications."

Does the F-Droid version also include the GCM or does it only use an own TCP connection ?
Or does conversations always only use an own connection ?

-- 
Best regards/Schöne Grüße

Martin
A: Because it breaks the logical sequence of discussion
Q: Why is top posting bad?

()  ascii ribbon campaign - against html e-mail 
/\                        - against proprietary attachments

Geschenkideen, Accessoires, Seifen, Kulinarisches: www.lillehus.at

**Comment by kollix** [comment] 2018-01-28 17:41
On Samstag, 27. Jänner 2018 23:28:37 CET Daniel Gultsch wrote:
> @kollix can you check if this build: http://gultsch.de/files/Conversations-1.23.4-playstore-release.apk shows a 'Protected Apps' settings in the Conversations settings that deep links into the Huawei protected app screen?

... however even setting Conversations in this "Protected Apps" aka "Lock screen cleanup" settings to "don't close",
I do NOT receive new messages when the phone is in standby.
Note: this is the F-Droid version 1.23.3.

-- 
Best regards/Schöne Grüße

Martin
A: Because it breaks the logical sequence of discussion
Q: Why is top posting bad?

()  ascii ribbon campaign - against html e-mail 
/\                        - against proprietary attachments

Geschenkideen, Accessoires, Seifen, Kulinarisches: www.lillehus.at

**Comment by licaon-kter** [comment] 2018-01-28 19:31
@kollix 

So you did all three:
Step 1: Go to settings --> advanced settings --> battery manager --> protected apps
Step 2: Go to settings --> apps --> advanced --> ignore battery optimizations,
Step 3: Go to settings --> notification panel & status bar --> notification center, then find the app, then activate "allow notifications" and also "priority display".

...and activated foreground service and still don't receive messages while the device is off?

**Comment by iNPUTmice** [comment] 2018-01-28 19:44
The F-Droid app does not use GCM. However if your OS doesn’t allow apps to run in the background. (The log you posted indicates that) GCM push notifications won't work either.

**Comment by Elmi77** [comment] 2018-01-29 06:15
So you have at least five people with the same problem - i wonder when you start accepting this bug instead for blaming people for reporting it and closing the bug reports without any further actions! It is a shame of an app which costs money...

**Comment by licaon-kter** [comment] 2018-01-29 06:57
@Elmi77 Huawei and Xiaomi (at least) are known to aggresively kill apps, that's not Conversations fault, that's the OEMs fault.

**Comment by Elmi77** [comment] 2018-01-29 07:21
I neither have an huawei nor an xiaomi. The guy who reported this bug here neither has an huawei nor an xiaomi.

But it seems you prefer to ignore this fact while continuing taking money for a buggy, crappy app 👎 

And I would bet this bug report goes the same way like all others before, it will be closed without fixing anything.

**Comment by licaon-kter** [comment] 2018-01-29 09:16
We are still waiting for the log from `the guy who reported this bug` in the first place.
In the mean time... Huawei got discussed, hence my comment(s).

**Comment by mikemaikaefer** [comment] 2018-01-29 09:27
Sorry I don't understand where to get and how to use this adb thingy. Isn't there a logfile written by the app itself which could be used?

**Comment by licaon-kter** [comment] 2018-01-29 10:38
No, use a search to learn how to:
About ADB: https://developer.android.com/studio/command-line/adb.html
Get ADB: https://developer.android.com/studio/releases/platform-tools.html

Open a command line in the folder where `adb` (or `adb.exe` on WIndows) is and run: `adb logcat -v threadstime | grep conversations`

And while that outputs... do something to trigger the bug... send, receive messages, turn off the screen, something...

You can then copy that output, remove personal information (account names/etc) and put it on https://gist.github.com

**Comment by daivat15** [comment] 2018-01-30 09:14
I think a feature should be implemented so that the app writes a log file recording all essential events. This way users reporting bugs and crashes would not have to go through the process of recording the logcat which might seem tedious for them unless absolutely necessary.

**Comment by licaon-kter** [comment] 2018-01-30 10:36
The crashes are reported, see the Settings.

**Comment by mikemaikaefer** [comment] 2018-01-31 09:21
This adb crap is a mess, you can not expect from a normal user to deal with such things which seem to presume detailed technical know how. So I wasted two days with this and with a lot of headaches I found out the problem does not appear when this adb is used. So: how can I run this adb stuff on my smartphone without having USB connected? Or can you integrate it into Conversations since it solves the problem?

**Comment by licaon-kter** [comment] 2018-01-31 09:48
Without cable:
* When connected to a PC run `adb tcpip 5555`
* Disconnect
* Then, **until the next device reboot** _(or you toggle off USB debug or Developer mode)_ you can either use [Logs](https://github.com/tananaev/rootless-logcat) to see the logcat live, filter it by `conversations` and save it or [Remote ADB Shell](https://play.google.com/store/apps/details?id=com.cgutman.androidremotedebugger) to run commands like you did from the PC
 
;)

**Comment by mikemaikaefer** [comment] 2018-01-31 09:53
Sorry, you are kidding??? Do you want me to add this to your app? How about you doing this when I pay for this non-working crap?????

**Comment by licaon-kter** [comment] 2018-01-31 10:13
It's not **my** app, not sure what are you thinking, I was just trying to help you. :neutral_face:

Not sure how the developer could help you without providing some logs.

But like whatever...

**Comment by d9h20f** [comment] 2018-01-31 10:36
@mikemaikaefer I do believe you can ask for a refund if it doesn't work, but all that's happening here is that the developer is asking for more information on how it goes wrong, because he has no other way of reproducing the problem without owning the same no-name tablet.

Also, you asked how to use the adb stuff on your device, @licaon-kter provided an answer, and you got angry at him. No one is trying to cheat you out of your money, it's just the only way to get more information to conjure up a solution.

**Comment by mikemaikaefer** [comment] 2018-01-31 10:51
@d9h20f no, I asked for a working app. All I got from the beginning was a lot of technical stuff I'm not familiar with and I don't understand. I pointed to this fact several times. But after wasting two days with this crap I got even more technical stuff I still do not understand. But what was my question? Yes, also this time I only asked for **repairing** this app. So what is your idea, what can I do exactly **without any technical knowledge and without being a programmer**? Sending a bugreport (as asked) or just giving 1 star and a bad rating on Google Playstore?

**Comment by d9h20f** [comment] 2018-01-31 11:33
Realistically, you can only hope someone with more technical know-how will encounter the same problem and send in more information or even a solution. It's unfortunate, but @iNPUTmice really can't do anything to fix a problem if he doesn't know what the problem is. A side effect of neither having loads of resources nor being extremely popular.

**Comment by iNPUTmice** [comment] 2018-01-31 11:36
@mikemaikaefer Android is unfortunately a pretty  heterogeneous ecosystem. Different vendors have various weird power savings. The fact that it seems to work if your device is on power (plugged into the computer) also indicates that. There is very little I can do about that. 2 Euro on the playstore doesn't buy my a lot of test devices unfortunately. I'll happily refund you your money though if you send me your order number (GPA.something.something) from the Google play receipt.

**Closed by iNPUTmice** 2018-01-31 11:36 UTC

**Comment by mikemaikaefer** [comment] 2018-01-31 11:56
So this is your support? Simply close a bugreport? So Conversations is crap, there is absolutely no reason why somebody should prefer it over WhatsApp or other apps - which are available for free of any charge!
