### ISSUE TITLE
Conversations doesn't recognize ".zone" URLs

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#902] opened 2015-01-18 14:44 UTC
Conversations doesn't recognize links like [this one](https://quitter.zone/notice/13899) because of the ".zone", I guess.
I've tried using HTTP instead of HTTPS but I got the same result. It thinks it's shared as a plain text, no HTML.

**Comment by iNPUTmice** [comment] 2015-01-19 15:22
Seems to be an Android bug. There is nothing I can do about that unfortunatly.

**Comment by SamWhited** [comment] 2015-01-19 15:23
I'm unable to reproduce this, so maybe it's fixed in Android 5.

**Closed by iNPUTmice** 2015-01-19 15:22 UTC

**Comment by moshpirit** [comment] 2015-01-19 15:38
Ok :(
Thanks anyway!
