### ISSUE TITLE
Feature - sending file asynchronously?

### ISSUE THREAD

**Issue by zxiu** [siacs/Conversations#988] opened 2015-02-16 13:19 UTC
As my test with Conversation, when user want to send image/audio.. to another both must be online. With a file uploading API user could send file asynchronously. After a success upload client send the other user a url within the Xmpp message. For example ( ..... < body >this is a title(could be empty)< / body>< photo >< url >http://upload.com/1.jpg</ url> </ photo > .....). 
The other cliend could receive/download/cache anytime when it goes online. 
Will it be possible that Conversation support this feature in future?

**Comment by TameOfGroans** [comment] 2015-02-23 09:05
Have you considered ftp?  Host file for other user to fetch whenever. Optionally use encryption. Else amazon s3 or similar.

**Comment by TameOfGroans** [comment] 2015-02-23 09:06
I hope someone will come in with stanza limitation. You might be pleased to try DATA URI: Base64 encode your file. (send as text)

**Comment by zxiu** [comment] 2015-02-23 09:09
@TameOfGroans I could extend the xmpp packet by myself, surely. But if Conversation could consider to implement it i would like not to reinventing the wheel :D.

**Comment by TameOfGroans** [comment] 2015-02-23 09:48
^ come in == chime in 

spell"fix" is almost as vexatious as Microsoft Word suggestions to simplify grammar to that of a nine year old.  [I no longer microsoft. I use other software. I like that software. Some things are nice. Short sentences are short.]

**Comment by singpolyma** [comment] 2015-06-24 03:18
Could send within the message as text, or use the XMPP OOB file transfer feature, which is designed for this use case.  https://transfer.sh/ might be a good service for this

**Comment by iNPUTmice** [comment] 2015-07-03 12:00
Conversations 1.5 (upcoming) will have build in support to upload files to an HTTP host on the XMPP server. This requires for a special component to be installed on the users server. The source code for that component is available here: https://github.com/siacs/HttpUploadComponent The necessary changes to Conversations are now available in the development branch of Conversations. Automatic download of these files will only happen in non-anonymous MUCs for known contacts. But even in anonymous MUCs the user can long press the link and download the image in place.


I'm closing this issue because it is basically duplicate of #175 (same solution for a slightly different problem)

**Closed by iNPUTmice** 2015-07-03 12:00 UTC
