### ISSUE TITLE
OpenPGP Decrypt Loop with Token

### ISSUE THREAD

**Issue by felmey** [siacs/Conversations#1690] opened 2016-02-10 14:23 UTC
When attempting to use a token (YubiKey NEO) for OpenPGP in Conversations 1.9.3 via F-Droid there is an endless decrypt loop that follows.  Eventually NFC becomes non-responsive and needs to be turned off and then back on for further attempts which also result in an endless decrypt loop.  This occurs on a non-rooted Samsung S5 with OpenKeyChain installed.  Selecting "Cancel" on the token request does take you out of the loop without any crash.

Discussed with Valodim in Freenode #openkeychain and was suggested this may be similar to the following solved issue in K-9 mail: https://github.com/k9mail/k-9/pull/1011
The original K-9 problem (solved in above pull) sounds similar to what I am experiencing within Conversations:  https://github.com/k9mail/k-9/issues/864

**Comment by iNPUTmice** [comment] 2016-02-10 15:07
Pull requests are very welcome. I don't have a yubikey and I'm not really using pgp so i'm not the right guy to test this.
Maybe @fiaxh or @adithyaphilip can help.

**Comment by adithyaphilip** [comment] 2016-02-11 18:39
Unfortunately, I don't have a yubikey either :/ I'll have to give it a pass.

**Comment by thundergreen** [comment] 2016-03-17 06:39
Don't know if this is the same issue but when trying openpgp with a contact conversations asks me the first time for the passphrase .after first message it asks me again to decrypt but without asking the passphrase again.I just kick on decrypt and message will be decrypted .

**Comment by iNPUTmice** [comment] 2017-11-22 12:37
Duplicate of #957

**Closed by iNPUTmice** 2017-11-22 12:37 UTC
Labels: gsoc-teaser, pr-welcome
