### ISSUE TITLE
Sending an image via OMEMO to a not-contacted user results in a 'delivery failed'

### ISSUE THREAD

**Issue by marmistrz** [siacs/Conversations#3209] opened 2018-10-02 08:32 UTC
#### General information

* **Version:** 2.2.9+fcr
* **Device:** OnePlus 3
* **Android Version:** LOS 14.1
* **Server name:** wiuwiu.de (sender) -> neko.im (recipient), but the issue may have occurred with wiuwiu.de recipients too
* **Server software:** prosody 0.10.2
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Take a screenshot, share it with a contact who has not previously been contacted (I think I've used the share intent, not uploaded it directly from Conversations, but I'm not sure)
2. Delivery failed error occurs
3. Enter contact details. No OMEMO fingerprints are present
4. Try sending a text message
5. OMEMO keys are fetched, a pop-up asking to set trust appears
6. Cancel the pop-up, manually trust fprs via contact details, send again
7. now the transfer succeeds

#### Expected result

When trying to share an image, the OMEMO keys should be fetched and a trust pop-up displayed.

#### Other remarks

This issue probably has a different face - if the remote party generates a new OMEMO key, sending an image doesn't show a pop-up to decide about the new fingerprint

#### Debug output

````
10-02 09:30:12.779  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:30:37.935  3358 21414 D conversations: update unread count to 718
10-02 09:30:37.937  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:30:58.226  3358 21414 D conversations: update unread count to 719
10-02 09:30:58.229  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:30:58.848  3358 21414 D conversations: update unread count to 720
10-02 09:30:58.850  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:31:20.852  3358 21414 D conversations: update unread count to 721
10-02 09:31:20.854  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:31:36.827  3358 21414 D conversations: update unread count to 722
10-02 09:31:36.830  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:31:50.450  3358 21414 D conversations: update unread count to 723
10-02 09:31:50.454  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:32:04.821  3358 21414 D conversations: update unread count to 724
10-02 09:32:04.823  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:32:47.874  3358 21414 D conversations: update unread count to 725
10-02 09:32:47.876  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:33:35.708  3358 21414 D conversations: update unread count to 726
10-02 09:33:35.710  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:33:37.822  3358 21414 D conversations: update unread count to 727
10-02 09:33:37.824  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:33:50.142  3358 21414 D conversations: update unread count to 728
10-02 09:33:50.144  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:33:54.600  3358 21414 D conversations: update unread count to 729
10-02 09:33:54.602  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:34:07.561  3358 21414 D conversations: update unread count to 730
10-02 09:34:07.563  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:34:51.004  3358 21414 D conversations: alice@magicbroccoli.de: successfully fetched vCard avatar for conversations@conference.siacs.eu/geofferey
10-02 09:35:13.745  3358  3358 D conversations: alice@magicbroccoli.de send ping (action=ping,lowTimeout=false)
10-02 09:35:13.752  3358  3358 D conversations: bob@magicbroccoli.de send ping (action=ping,lowTimeout=false)
10-02 09:35:13.758  3358  3358 D conversations: chester@wiuwiu.de send ping (action=ping,lowTimeout=false)
10-02 09:35:18.846  3358 21414 D conversations: update unread count to 731
10-02 09:35:18.849  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:35:27.907  3358 21414 D conversations: update unread count to 732
10-02 09:35:27.909  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:35:42.323  3358 21414 D conversations: update unread count to 733
10-02 09:35:42.325  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:35:43.486  3358 21414 D conversations: update unread count to 734
10-02 09:35:43.488  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:36:15.152  3358 21414 D conversations: update unread count to 735
10-02 09:36:15.154  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:36:27.651  3358 21414 D conversations: update unread count to 736
10-02 09:36:27.656  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:36:37.256  3358 21414 D conversations: update unread count to 737
10-02 09:36:37.260  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:36:43.407  3358 21414 D conversations: update unread count to 738
10-02 09:36:43.409  3358 21414 D conversations: alice@magicbroccoli.de: suppressing notification because turned off
10-02 09:40:27.909  3358  3358 D conversations: alice@magicbroccoli.de send ping (action=idle_ping,lowTimeout=false)
10-02 09:40:27.912  3358  3358 D conversations: bob@magicbroccoli.de send ping (action=idle_ping,lowTimeout=false)
10-02 09:40:27.918  3358  3358 D conversations: chester@wiuwiu.de send ping (action=idle_ping,lowTimeout=false)
10-02 09:40:43.595  3358  3358 D conversations: action: android.intent.action.SEND, type:image/png
10-02 09:40:43.607  3358  3358 D conversations: app switched into foreground
10-02 09:40:49.289  3358  3358 D conversations: app switched into background
10-02 09:40:50.276  3358  3358 D conversations: action: android.intent.action.SEND, type:image/png
10-02 09:40:50.314  3358  3358 D conversations: app switched into foreground
10-02 09:40:50.330  3358  3378 D conversations: chester@wiuwiu.de: running mam query with=dan@neko.im, end=2018-10-01T08:56:02.516Z, order=REVERSE, catchup=false, ns=urn:xmpp:mam:2
10-02 09:40:50.364  3358 13000 D conversations: copy image (content://media/external/images/media/936) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/7922be66-ffe1-4a63-8372-6af044683587.jpg
10-02 09:40:50.402  3358 13000 D conversations: reading bitmap with sample size 1
10-02 09:40:50.450  3358  3358 D conversations: received uri permission for content://media/external/images/media/936
10-02 09:40:50.548  3358 13000 D conversations: send file message
10-02 09:40:50.648  3358  3358 D conversations: ConversationFragment.saveMessageDraftStopAudioPlayer()
10-02 09:40:50.648  3358  3358 D conversations: reInit(hasExtras=true)
10-02 09:40:50.648  3358  3358 D conversations: trimming conversation
10-02 09:40:50.652  3358  3358 D conversations: scrolledToBottomAndNoPending=true
10-02 09:40:50.652  3358  3358 D conversations: jump to first unread message
10-02 09:40:50.696  3358  3358 D conversations: ConversationFragment.onBackendConnected()
10-02 09:40:58.948  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@73baa13
10-02 09:40:59.026  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@feb6450
10-02 09:40:59.046  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@12cd46f
10-02 09:40:59.069  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@5aa757c
10-02 09:40:59.081  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@347fe05
10-02 09:40:59.094  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@1eade5a
10-02 09:40:59.127  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@45c488b
10-02 09:40:59.143  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@fe76d68
10-02 09:40:59.175  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@f4f7581
10-02 09:40:59.190  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@d688626
10-02 09:40:59.211  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@5c4e267
10-02 09:40:59.263  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@479f814
10-02 09:40:59.313  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@4fce8bd
10-02 09:40:59.331  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@dc6deb2
10-02 09:40:59.375  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@5333e03
10-02 09:40:59.393  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@d088180
10-02 09:40:59.446  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@d1453b9
10-02 09:40:59.465  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@d4033fe
10-02 09:40:59.485  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@8a1b75f
10-02 09:40:59.569  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@e9d7275
10-02 09:40:59.583  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@d67920a
10-02 09:40:59.626  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Account: chester@wiuwiu.de/Conversations.LLU1 No axolotl session found while parsing received message eu.siacs.conversations.crypto.axolotl.XmppAxolotlMessage@1546a7b
10-02 09:40:59.653  3358 21413 D conversations: chester@wiuwiu.de: finished mam after 50(25) messages. messages left=true count=11095
10-02 09:40:59.653  3358 21413 D conversations: chester@wiuwiu.de: found 0 pending receipt requests
10-02 09:40:59.660  3358 22292 D conversations: uploading to https://upload.wiuwiu.de/upload/Xl66PVf64w88SjRz/eSK-Zv_hSmODcmrwRGg1hw.jpg w/ read timeout of 83s
10-02 09:41:01.260  3358 22292 D conversations: finished uploading file
10-02 09:41:01.284  3358 22292 D conversations: AxolotlService (chester@wiuwiu.de): Cache miss: 7922be66-ffe1-4a63-8372-6af044683587
10-02 09:41:05.912  3358  3358 D conversations: AxolotlService (chester@wiuwiu.de): Cache miss: 7922be66-ffe1-4a63-8372-6af044683587
10-02 09:41:14.015  3358  3358 D conversations: alice@magicbroccoli.de send ping (action=ui,lowTimeout=false)
10-02 09:41:14.016  3358  3358 D conversations: bob@magicbroccoli.de send ping (action=ui,lowTimeout=false)
10-02 09:41:14.017  3358  3358 D conversations: chester@wiuwiu.de send ping (action=ui,lowTimeout=false)
10-02 09:41:15.386  3358  3358 D conversations: reInit(hasExtras=false)
10-02 09:41:15.394  3358  3358 D conversations: scrolledToBottomAndNoPending=true
10-02 09:41:15.394  3358  3358 D conversations: jump to first unread message
10-02 09:41:15.495  3358  3358 D conversations: ConversationFragment.onBackendConnected()
10-02 09:41:24.945  3358  3358 D conversations: AxolotlService (chester@wiuwiu.de): Finding devices without session for dan@neko.im
10-02 09:41:24.947  3358  3358 D conversations: AxolotlService (chester@wiuwiu.de): Found device dan@neko.im:852202397
10-02 09:41:24.952  3358  3358 D conversations: chester@wiuwiu.de: createSessionsIfNeeded() - jids with empty device list: []
10-02 09:41:24.952  3358  3358 I conversations: AxolotlService (chester@wiuwiu.de): Creating axolotl sessions if needed...
10-02 09:41:24.952  3358  3358 D conversations: AxolotlService (chester@wiuwiu.de): Finding devices without session for dan@neko.im
10-02 09:41:24.954  3358  3358 D conversations: AxolotlService (chester@wiuwiu.de): Found device dan@neko.im:852202397
10-02 09:41:24.954  3358  3358 D conversations: AxolotlService (chester@wiuwiu.de): Processing device: dan@neko.im:852202397
10-02 09:41:24.954  3358  3358 I conversations: AxolotlService (chester@wiuwiu.de): Building new session for dan@neko.im:852202397
10-02 09:41:25.221  3358 21413 D conversations: AxolotlService (chester@wiuwiu.de): Received preKey IQ packet, processing...
10-02 09:41:25.548  3358  3358 D conversations: ignoring read callback. mActivityPaused=true
10-02 09:41:31.809  3358  3358 D conversations: reInit(hasExtras=false)
10-02 09:41:31.821  3358  3358 D conversations: scrolledToBottomAndNoPending=true
10-02 09:41:31.821  3358  3358 D conversations: jump to first unread message
10-02 09:41:31.883  3358  3358 D conversations: ConversationFragment.onBackendConnected()
10-02 09:41:49.265  3358  3358 D conversations: app switched into background
10-02 09:41:49.303  3358  3358 D conversations: ConversationFragment.onAttach()
10-02 09:41:49.375  3358  3358 D conversations: alice@magicbroccoli.de send ping (action=ui,lowTimeout=false)
10-02 09:41:49.376  3358  3358 D conversations: bob@magicbroccoli.de send ping (action=ui,lowTimeout=false)
10-02 09:41:49.378  3358  3358 D conversations: chester@wiuwiu.de send ping (action=ui,lowTimeout=false)
10-02 09:41:49.381  3358  3358 D conversations: app switched into foreground
10-02 09:41:49.381  3358  3358 D conversations: ConversationFragment.onBackendConnected()
10-02 09:41:49.381  3358  3358 D conversations: reInit(hasExtras=false)
10-02 09:41:49.386  3358  3358 D conversations: scrolledToBottomAndNoPending=true
10-02 09:41:49.386  3358  3358 D conversations: jump to first unread message
10-02 09:41:52.054  3358  3358 D conversations: app switched into background
10-02 09:41:52.115  3358  3358 D conversations: ConversationFragment.onAttach()
10-02 09:41:52.181  3358  3358 D conversations: app switched into foreground
10-02 09:41:52.181  3358  3358 D conversations: ConversationFragment.onBackendConnected()
10-02 09:41:52.181  3358  3358 D conversations: reInit(hasExtras=false)
10-02 09:41:52.189  3358  3358 D conversations: scrolledToBottomAndNoPending=true
10-02 09:41:52.190  3358  3358 D conversations: jump to first unread message
10-02 09:41:59.099  3358  3358 D conversations: reInit(hasExtras=false)
10-02 09:41:59.115  3358  3358 D conversations: scrolledToBottomAndNoPending=true
10-02 09:41:59.115  3358  3358 D conversations: jump to first unread message
10-02 09:41:59.188  3358  3358 D conversations: ConversationFragment.onBackendConnected()
10-02 09:42:01.131  3358  3358 D conversations: AxolotlService (chester@wiuwiu.de): Cache miss: 7922be66-ffe1-4a63-8372-6af044683587
10-02 09:42:01.164  3358  4754 D conversations: AxolotlService (chester@wiuwiu.de): Generated message, caching: 7922be66-ffe1-4a63-8372-6af044683587
10-02 09:42:01.164  3358  4754 D conversations: AxolotlService (chester@wiuwiu.de): Cache hit: 7922be66-ffe1-4a63-8372-6af044683587
10-02 09:42:03.563  3358 21413 D conversations: chester@wiuwiu.de: omemo key transport message received from dan@neko.im/Conversations.SVPh
10-02 09:42:24.620  3358  3358 D conversations: AxolotlService (chester@wiuwiu.de): Finding devices without session for dan@neko.im
10-02 09:42:24.621  3358  3358 D conversations: AxolotlService (chester@wiuwiu.de): Cache miss: cf2bc252-20e8-45f3-8a24-3aa49162b037
10-02 09:42:24.676  3358  4754 D conversations: AxolotlService (chester@wiuwiu.de): Generated message, caching: cf2bc252-20e8-45f3-8a24-3aa49162b037
10-02 09:42:24.676  3358  4754 D conversations: AxolotlService (chester@wiuwiu.de): Cache hit: cf2bc252-20e8-45f3-8a24-3aa49162b037
10-02 09:42:27.013  3358  3358 D conversations: app switched into background
````

**Comment by iNPUTmice** [comment] 2018-10-02 08:35
duplicate of #3083

**Closed by iNPUTmice** 2018-10-02 08:35 UTC
