### ISSUE TITLE
Invalid certificate dialogs pile up (usability issue)

### ISSUE THREAD

**Issue by bsturmfels** [siacs/Conversations#1891] opened 2016-06-04 02:10 UTC
#### General information

* **Version:** eg 1.12.8
* **Device:** Samsung Galaxy S3
* **Android Version:** Replicant 4.2 (based on CyanogenMod 10.1)
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Connect to a server with an invalid TLS certificate (eg. self-signed, or doesn't match domain).
2. Invalid certificate dialog pops up.
3. Leave the device for a couple of minutes.
4. Multiple invalid certificate dialogs stack up, so that you have to dismiss many times - most people will assume that their action didn't work.

#### Expected result

There's only one dialog and you can dismiss the dialog/accept the certificate with just one selection.

**Comment by iNPUTmice** [comment] 2016-06-04 07:26
> Leave the device for a couple of minutes.

Leave the device in what state? With the App open in foreground? Returned to desktop? I can't reproduce this.

**Comment by bsturmfels** [comment] 2016-06-05 04:49
> Leave the device in what state? With the App open in foreground?

Just tried it again myself. When I see the invalid certificate dialog pop up (in this case due to a hostname mismatch), I just left the phone as-is (app in foreground) for about 20 mins. Came back and had somewhere around 15 dialogs to close (didn't actually count). Tried all three buttons, "abort", "once" and "always" but made no difference - had to action them all.

**Comment by bsturmfels** [comment] 2016-06-05 04:50
Thanks for a great program by the way!

**Comment by iNPUTmice** [comment] 2016-06-05 21:17
Should be fixed in 8e6f054e525356b1f814280f087d5152e98de711.Can you try with this commit?

**Comment by bsturmfels** [comment] 2016-06-19 07:43
Thanks Daniel. I'd love to help test that change, but I don't currently do any Android development so don't have a build environment set up. Sorry to be a drive-by bug reporter.

**Comment by iNPUTmice** [comment] 2016-06-19 08:06
Ok thank you. I'm fairly certain it's fixed.

**Closed by iNPUTmice** 2016-06-19 08:06 UTC
