### ISSUE TITLE
Block an OMEMO key, and you can't unblock it.

### ISSUE THREAD

**Issue by Fenisu** [siacs/Conversations#2092] opened 2016-10-27 16:10 UTC
Well, having a conversation with someone, if you remove/block the OMEMO key, then you will not be able to write to this someone anymore, as to be expected, but let's say that you "mistakenly" removed/blocked it. 

Then you can't get it back by any means. Blocked list does not show the contact as the contact is not blocked, and the key can't be seen anywhere. So I propose that instead of removing the visibility of the key from the application, and silently add the key to a block list, to set a checkbox or something similar to every key to show if it is blocked or not (or maybe text in red color for blocked ones). 

The idea is to be able to "readd" the key without forcing the other user to actually recreate a new key.

**Comment by mimi89999** [comment] 2016-10-29 13:43
@Fenisu You can disable a key using the slider. Removing the key is like marking it as compromised.

**Comment by licaon-kter** [comment] 2016-10-29 16:37
@mimi89999 The issue is that apparently you can't get it back actually.

**Comment by mimi89999** [comment] 2016-10-29 16:38
@licaon-kter After disabling with the slider?

**Comment by licaon-kter** [comment] 2016-10-29 16:56
No idea how @Fenisu removed it exactly.

**Comment by mimi89999** [comment] 2016-10-29 17:04
@licaon-kter Because after disabling it with the slider, normally you should be able to re-enable it.
As for deleting keys, it il like marking them as compromised and that is not reversible. A key marked as compromised should stay like that...

**Comment by Fenisu** [comment] 2016-10-31 09:01
As a natural born clicker, I have to say it is too easy to do something irreversible. Rather than mark permanently as compromised with 1 warning dialog in the middle, why don't make it compromised (with a dialog) but then leave it or put it somewhere (it could be pretty hidden) to be able to unmark it as compromised, with a huge dialog/banner saying that it is not recommended to do so.

Scenario:
You have a contact with many keys and you just want to clean that list of keys, you long press each key and so easy you can mistakenly mark on of those is still active.

I really think that instead of removing it entirely, to let it be there with the slider as deactivated, the entire key text in light greyish red, so if you long press again, you can unmark it as compromised and get it back.

**Comment by mimi89999** [comment] 2016-11-20 14:53
@Fenisu Then make your contact remove his keys from the server... That will be the correct way...

**Closed** 2017-03-04 07:43 UTC
