### ISSUE TITLE
OMEMO: Encrypted message notification

### ISSUE THREAD

**Issue by blacoste** [siacs/Conversations#1901] opened 2016-06-08 20:14 UTC
Issue: 
When a message is OMEMO encrypted but is not addressed to a XMPP listening resource with Conversation client, user is not notified of a encrypted message exchanged.

This situation happens when a new device is added to a set of device and did not yet accomplished the key info excganges or on a MUC.

This is bad because if this situation happens the user is not notified that OMEMO is failing. 

For instance I waste a lot of time believing that Carbon copy was not working and instead it was an OMEMO issue. Sending clear message would solve the issue and we would suddenly understand that the XMPP layer was OK.

OMEMO or Axolotl (can't remember) asks to silently drop this kind of message but this is a protocol requirement, not a GUI one.

Short:
Add a red text "OMEMO enciphered message" in the message conversation instead of nothing.

**Comment by lovetox** [comment] 2016-06-08 21:12
maybe i understand this wrong

but either your device id is in the message, that means the message got encrypted for that device, so the key exchange happend

or you receive a message without your device id. this can have multiple reasons, and i dont think you want to get informed about a message that doesnt has your device id included.

**Comment by bastoon06** [comment] 2016-06-08 21:35
Yes, I think it could add beter clarity.

It is not a frequent situation to receive encrypted messages and cannot decipher them. Correct me if I am wrong but in all cases it should be a temporary situation caused by misconfiguration or pending questions (of trust for instance).

If one of my device was not trusted by a peer, I would be glad to know it instead of having a part of the conversation. Then we could fix together the issue.

**Comment by FriendFX** [comment] 2017-07-14 08:25
Just came across another use case for such notifications: 

A friend of mine (generally tech-savvy but unaware of OMEMO's internal operation) and other friends usually communicate through a few MUCs. Because my friend's phone broke, he sent it in for repair and is now using a replacement mobile. He re-used his account details on the replacement, but of course, his original mobile's OMEMO keys aren't on it, so this replacement mobile now (silently) drops all encrypted messages me and my friends are sending to him in the MUCs and 1:1 chats as well. It took a while for me to figure out what was going on.

I think a clear notification (maybe one per chat room) that he got an encrypted message which couldn't be decrypted because no key was on the mobile for any of the message's device keys would've been very helpful in learning about the problem. 

*[Rant] Wayyy more helpful than us all frantically trying to get him to respond to our - encrypted - messages he didn't even see... if it wasn't for me having learned just enough about OMEMO's inner workings and disabling OMEMO in my messages to him, we'd have never found out and all of us would've abandoned OMEMO or Conversations altogether. [/Rant]*

**Comment by licaon-kter** [comment] 2017-07-14 11:04
@FriendFX Did you get his messages when s/he notified you about the "device change"... you know the usual "Hey, I got another phone blahblah" ?

**Comment by FriendFX** [comment] 2017-07-17 01:12
@licaon-kter Yes, these first messages from his new phone were unencrypted... and I got them. Unfortunately he didn't get mine, I guess because mine were still using his (old phone's) public keys. 

The issue is that I, as an end user, have to know (because he told me that he has a new phone now) that I need to switch to un-encrypted to tell him to activate OMEMO again. And other parties unaware of the phone change (why would he tell everyone about it? He still uses his same old JID) are probably wondering why he doesn't respond to any of their encrypted messages. And he just sits there wondering why he doesn't get any messages from them.

I am sure somewhere there is a smart manual on how to switch phones with Conversations in order to move the existing OMEMO keys safely from an old to a new mobile, but in real life only a tiny fraction of users will be in a position to actually do it correctly when the need arises... unless it's done by the service personnel that issues the "replacement phone".

**Comment by philipflohr** [comment] 2017-08-22 07:03
This problem is quite frequent if users reset their phones or use custom roms. In my opinion Conversations should at least display a warning that a message was received but cannot be shown.

**Comment by jotwewe** [comment] 2018-03-31 11:56
I'd like to support the request stated above: Conversations should display that it wasn't able to decrypt a message sent by user XY. 
Related are the facts that Chatsecure revokes trust in a key in certain cases (https://github.com/ChatSecure/ChatSecure-iOS/issues/814) and that Prosody starts with an empty list of keys (https://github.com/ChatSecure/ChatSecure-iOS/issues/814#issuecomment-377683816).

**Comment by JuniorJPDJ** [comment] 2018-04-06 00:02
I also support the request.
It's must to be clarified.

**Comment by iNPUTmice** [comment] 2018-12-06 12:03
Conversations now displays messages when an omemo messages can not be decrypted (needs `mam:2` support on the server) and when an OMEMO message wasn’t encrypted for this device.

**Closed by iNPUTmice** 2018-12-06 12:03 UTC
