### ISSUE TITLE
Use notifications for MUC invites and delivery errors

### ISSUE THREAD

**Issue by contrapunctus-1** [siacs/Conversations#3483] opened 2019-06-18 04:54 UTC
I request that notifications be used to inform users when
1. They have been invited to an MUC (with buttons to accept or ignore). All too often, I invite people to a room, and people usually don't check their chat list and end up missing the invite. In case of non-anonymous rooms, the JID warning text should go into this notification too.
2. Their message fails to deliver (with the error text and buttons to 'show' (jump to message) and 'resend'). The current way delivery errors are displayed are very easy to miss, and I have seen this with contacts quite often.

**Comment by iNPUTmice** [comment] 2019-06-26 21:55
duplicate of #358 and  #2191

**Closed by iNPUTmice** 2019-06-26 21:55 UTC
