### ISSUE TITLE
http_upload not working with prosody in 1.6.10 (works in 1.6.9)

### ISSUE THREAD

**Issue by aslmx** [siacs/Conversations#1452] opened 2015-10-01 12:39 UTC
Hi,

i recently updated to 1.6.10 (via fdroid market app). I just noticed a few minutes back when i was in a MUC on my prosody, that i could not send any picture into the groupchat.

I quickly restarted Prosody and tried to resolve it this way but the server info in the account dialog still kept saying http_upload - no(t supported).

I disconnected/reconnected a few times no change.

Then i noticed on my other Android phone which uses my second account on the same server, that 

http_upload     yes

was shown in the server info...

On the second phone i was still having 1.6.9.

When i removed 1.6.10 on the first phone and reinstalled 1.6.9 i could also use http_upload again with the first phone.

So my assumption is, something was broken or changed and broke compatibility of http_upload between conversations 1.6.10 and prosody.

i'm running Prosody 0.9.8

Can someone confirm?

br

aslmx

**Comment by alexara** [comment] 2015-10-01 12:44
Duplicate of https://github.com/siacs/Conversations/issues/1435.

**Comment by aslmx** [comment] 2015-10-01 12:45
oh thanks for pointing me to the already existing issue, seems i have not checked properly enough... sry.

**Comment by iNPUTmice** [comment] 2015-10-01 13:03
you need to update the HttpUploadComponent or change the namespace. The
namespace has changed in 1.6.10

>

**Closed** 2015-10-01 13:03 UTC

**Comment by andersruneson** [comment] 2015-10-01 14:00
You need to update serverside component or module. Namespace was updated
according to draft XEP.

**Comment by martinsauter** [comment] 2015-10-01 19:19
Prosody has updated the http_upload module a couple of hours ago to follow this change :-)
